/*
 *  SIGES
 *  Desarrollado por Sofis Solutions
 */
package sv.gob.mined.siges.negocio.mensajes;

public class Errores {
    
    public static final String ERROR_GENERAL = "ERROR_GENERAL";
    public static final String ERROR_OPTIMISTIC_LOCK = "ERROR_OPTIMISTIC_LOCK";
    public static final String ERROR_DATO_VACIO = "ERROR_DATO_VACIO";
    public static final String ERROR_CODIGO_VACIO = "ERROR_CODIGO_VACIO";
    public static final String ERROR_NOMBRE_VACIO = "ERROR_NOMBRE_VACIO";
    public static final String ERROR_DESCRIPCION_VACIO = "ERROR_DESCRIPCION_VACIO";
    public static final String ERROR_LARGO_NOMBRE_255 = "ERROR_LARGO_NOMBRE_255";
    public static final String ERROR_LARGO_NOMBRE_20 = "ERROR_LARGO_NOMBRE_20";
    public static final String ERROR_LARGO_DESCRIPCION_255 = "ERROR_LARGO_DESCRIPCION_255";
    public static final String ERROR_VALOR_VACIO = "ERROR_VALOR_VACIO";
    public static final String ERROR_LARGO_VALOR_25 = "ERROR_LARGO_VALOR_25";
    public static final String ERROR_LARGO_VALOR_255 = "ERROR_LARGO_VALOR_255";
    public static final String ERROR_LARGO_VALOR_500 = "ERROR_LARGO_VALOR_500";
    public static final String ERROR_LARGO_CODIGO_45 = "ERROR_LARGO_CODIGO_45";
    public static final String ERROR_LARGO_CODIGO_4 = "ERROR_LARGO_CODIGO_4";
    public static final String ERROR_LARGO_CODIGO_5 = "ERROR_LARGO_CODIGO_5"; 
    public static final String ERROR_LARGO_CODIGO_6 = "ERROR_LARGO_CODIGO_6";
    public static final String ERROR_LARGO_CODIGO_7 = "ERROR_LARGO_CODIGO_7";
    public static final String ERROR_LARGO_CODIGO_8 = "ERROR_LARGO_CODIGO_8";
    public static final String ERROR_LARGO_CODIGO_10 = "ERROR_LARGO_CODIGO_10";
    public static final String ERROR_LARGO_CODIGO_15 = "ERROR_LARGO_CODIGO_15";
    public static final String ERROR_LARGO_CODIGO_20 = "ERROR_LARGO_CODIGO_20";
    public static final String ERROR_CODIGO_O_NOMBRE_DUPLICADOS = "ERROR_CODIGO_O_NOMBRE_DUPLICADOS";
    public static final String ERROR_CODIGO_DUPLICADO = "ERROR_CODIGO_DUPLICADO";
    public static final String ERROR_NOMBRE_DUPLICADO = "ERROR_NOMBRE_DUPLICADO";
    public static final String ERROR_ENTIDAD_REFERENCIADA = "ERROR_ENTIDAD_REFERENCIADA";
    public static final String ERROR_CANTON_VACIO = "ERROR_CANTON_VACIO";
    public static final String ERROR_MUNICIPIO_VACIO = "ERROR_MUNICIPIO_VACIO";
    public static final String ERROR_DEPARTAMENTO_VACIO = "ERROR_DEPARTAMENTO_VACIO";
    public static final String ERROR_ORDEN_VACIO = "ERROR_ORDEN_VACIO";
    public static final String ERROR_ESCALA_VACIO = "ERROR_ESCALA_VACIO";
    public static final String ERROR_TIPO_ESCALA_VACIO = "ERROR_TIPO_ESCALA_VACIO";
    public static final String ERROR_VALOR_MINIMO_VACIO = "ERROR_VALOR_MINIMO_VACIO";
    public static final String ERROR_MODALIDAD_ATENCION_VACIO="ERROR_MODALIDAD_ATENCION_VACIO";
    public static final String ERROR_ORDEN_NEGATICO="ERROR_ORDEN_NEGATICO";
    public static final String ERROR_LARGO_DESCRIPCION_500 = "ERROR_LARGO_DESCRIPCION_500";
    public static final String ERROR_CODIGO_U_ORDEN_DUPLICADO="ERROR_CODIGO_U_ORDEN_DUPLICADO";
    public static final String ERROR_TIPO_INSTITUCION_VACIO = "ERROR_TIPO_INSTITUCION_VACIO";
    public static final String ERROR_LARGO_NOMBRE_100 = "ERROR_LARGO_NOMBRE_100";
    public static final String ERROR_TELEFONO_VACIO = "ERROR_TELEFONO_VACIO";
    public static final String ERROR_TIPO_TELEFONO_VACIO = "ERROR_TIPO_TELEFONO_VACIO";
    public static final String ERROR_TIPO_ASOCIACION_VACIO = "ERROR_TIPO_ASOCIACION_VACIO";
    public static final String ERROR_NOMBRE_LEGAL_VACIO = "ERROR_NOMBRE_LEGAL_VACIO";
    public static final String ERROR_LARGO_NOMBRE_LEGAL_100 = "ERROR_LARGO_NOMBRE_LEGAL_100";
    public static final String ERROR_ASOCIACION_VACIO = "ERROR_ASOCIACION_VACIO";
    public static final String ERROR_PROYECTO_INSTITUCIONAL_VACIO = "ERROR_PROYECTO_INSTITUCIONAL_VACIO";
    public static final String ERROR_EXISTE_MOTIVO_TRASLADO = "ERROR_EXISTE_MOTIVO_TRASLADO";
    public static final String ERROR_EXISTE_MOTIVO_CAMBIO_SECCION = "ERROR_EXISTE_MOTIVO_CAMBIO_SECCION";
    public static final String ERROR_ARCHIVO_VACIO = "ERROR_ARCHIVO_VACIO";
    public static final String ERROR_NOMBRE_ACCION_VACIO = "ERROR_NOMBRE_ACCION_VACIO";
    public static final String ERROR_LARGO_NOMBRE_ACCION_45 = "ERROR_LARGO_NOMBRE_ACCION_45";
    public static final String ERROR_NUM_VACIO = "ERROR_NUM_VACIO";
    public static final String ERROR_ESTADO_ORIGEN_VACIO = "ERROR_ESTADO_ORIGEN_VACIO";
    public static final String ERROR_ESTADO_DESTINO_VACIO = "ERROR_ESTADO_DESTINO_VACIO";
    public static final String ERROR_ZONA_VACIO = "ERROR_ZONA_VACIO";
    public static final String ERROR_PLANTILLA_VACIO = "ERROR_PLANTILLA_VACIO";
    public static final String ERROR_FECHA_DESDE_VACIO = "ERROR_FECHA_DESDE_VACIO";
    public static final String ERROR_FECHA_HASTA_VACIO = "ERROR_FECHA_HASTA_VACIO";
    public static final String ERROR_LARGO_TEXTO_4000 = "ERROR_LARGO_TEXTO_4000";
    public static final String ERROR_LARGO_DESCRIPCION_1000 = "ERROR_LARGO_DESCRIPCION_1000";
    public static final String ERROR_OPERACION_VACIA = "ERROR_OPERACION_VACIA";
    public static final String ERROR_LARGO_OPERACION_100 = "ERROR_LARGO_OPERACION_100";
    public static final String ERROR_LARGO_DIRECCION_255 = "ERROR_LARGO_DIRECCION_255";
    public static final String ERROR_DIRECCION_VACIO = "ERROR_DIRECCION_VACIO";
    public static final String ERROR_LARGO_NOMBRE_2000 = "ERROR_LARGO_NOMBRE_2000";
    public static final String ERROR_LARGO_OBJETIVOS_500 = "ERROR_LARGO_OBJETIVOS_500";
    public static final String ERROR_TIPO_BENEFICIO_VACIO = "ERROR_TIPO_BENEFICIO_VACIO";
    public static final String ERROR_FECHA_INICIO_VACIO = "ERROR_FECHA_INICIO_VACIO";
    public static final String ERROR_FECHA_FIN_VACIO = "ERROR_FECHA_FIN_VACIO";
    public static final String ERROR_FECHA_INICIO_MAYOR_HASTA = "ERROR_FECHA_INICIO_MAYOR_HASTA";
    public static final String ERROR_ANIO_VACIO = "ERROR_ANIO_VACIO";
    public static final String ERROR_FECHA_DESDE_MAYOR_FECHA_HASTA = "ERROR_FECHA_DESDE_MAYOR_FECHA_HASTA";
    public static final String ERROR_TIPO_FORMULA_VACIO = "ERROR_TIPO_FORMULA_VACIO";
    
    public static final String ERROR_LARGO_PROCESO_20 = "ERROR_LARGO_PROCESO_20";
    public static final String ERROR_PROCESO_VACIO = "ERROR_PROCESO_VACIO";
    
    public static final String ERROR_CLASIFICACION_BIENES_VACIO = "ERROR_CLASIFICACION_BIENES_VACIO";
    public static final String ERROR_CATEGORIA_BIENES_VACIO = "ERROR_CATEGORIA_BIENES_VACIO";
    public static final String ERROR_VIDA_UTIL_VACIO = "ERROR_VIDA_UTIL_VACIO";
    public static final String ERROR_UNIDAD_ACTIVO_FIJO_VACIO = "ERROR_UNIDAD_ACTIVO_FIJO_VACIO";
    public static final String ERROR_TIPO_UNIDAD_VACIO = "ERROR_TIPO_UNIDAD_VACIO";
    public static final String ERROR_TIPO_AMBITO_VACIO = "ERROR_TIPO_AMBITO_VACIO";
    
    public static final String ERROR_UNIDAD_ADMINISTRATIVA_VACIO = "ERROR_UNIDAD_ADMINISTRATIVA_VACIO";
    public static final String ERROR_LARGO_CARGO_100 = "ERROR_LARGO_CARGO_100";
    public static final String ERROR_TIPO_ARCHIVO_VACIO = "ERROR_TIPO_ARCHIVO_VACIO";
    public static final String ERROR_FORMATO_VACIO = "ERROR_FORMATO_VACIO";
    public static final String ERROR_ANCHO_VACIO = "ERROR_ANCHO_VACIO";
    public static final String ERROR_ALTO_VACIO = "ERROR_ALTO_VACIO";
    public static final String ERROR_APLICA_VACIO ="ERROR_APLICA_VACIO";
    public static final String ERROR_OBRA_EXTERIOR_VACIO ="ERROR_OBRA_EXTERIOR_VACIO";
    public static final String ERROR_VALOR_MAXIMO_VACIO = "ERROR_VALOR_MAXIMO_VACIO";

    public static final String ERROR_CARGO_VACIO = "ERROR_CARGO_VACIO";
    public static final String ERROR_LARGO_CARGO_255 = "ERROR_LARGO_CARGO_255";

    public static final String ERROR_SERVICIO_VACIO ="ERROR_SERVICIO_VACIO";
    public static final String ERROR_URL_VACIO ="ERROR_URL_VACIO";
    public static final String ERROR_NOMBRE_CERTIFICADO_VACIO ="ERROR_NOMBRE_CERTIFICADO_VACIO";
    public static final String ERROR_PERSONA_VACIO ="ERROR_PERSONA_VACIO";
    
    public static final String ERROR_LARGO_ORIGEN_TRASNFERENCIA_100 = "ERROR_LARGO_ORIGEN_TRASNFERENCIA_100";
    public static final String ERROR_LARGO_CONVENIO_100 = "ERROR_LARGO_CONVENIO_100";
    public static final String ERROR_LARGO_CONDICIONES_ENTREGA_100 = "ERROR_LARGO_CONDICIONES_ENTREGA_100";
    public static final String ERROR_MONTO_MENOR_IGUAL_CERO = "ERROR_MONTO_MENOR_IGUAL_CERO";
    
    public static final String ERROR_CORREO_INVALIDO = "ERROR_CORREO_INVALIDO";
    public static final String ERROR_CORREO_ALTERNATIVO_INVALIDO = "ERROR_CORREO_ALTERNATIVO_INVALIDO";
    public static final String ERROR_CORREO_COORDINADOR_INVALIDO = "ERROR_CORREO_COORDINADOR_INVALIDO";
    public static final String ERROR_CORREO_RESPONSABLE_ADMINISTRATIVO_INVALIDO = "ERROR_CORREO_RESPONSABLE_ADMINISTRATIVO_INVALIDO";
    public static final String ERROR_ANIO_FUNDACION_MENOR_IGUAL_CERO = "ERROR_ANIO_FUNDACION_MENOR_IGUAL_CERO";
    public static final String ERROR_ANIO_FUNDACION_MAYOR_ANIO_ACTUAL = "ERROR_ANIO_FUNDACION_MAYOR_ANIO_ACTUAL";
    public static final String ERROR_LARGO_RESPONSABLE_INSTITUCIONAL_100 = "ERROR_LARGO_RESPONSABLE_INSTITUCIONAL_100";
    public static final String ERROR_LARGO_NOMBRE_COORDINADOR_GENERAL_100 = "ERROR_LARGO_NOMBRE_COORDINADOR_GENERAL_100";
    public static final String ERROR_LARGO_RESPONSABLE_ADMINISTRATIVO_100 = "ERROR_LARGO_RESPONSABLE_ADMINISTRATIVO_100";
    public static final String ERROR_LARGO_CORREO_50 = "ERROR_LARGO_CORREO_50";
    public static final String ERROR_LARGO_CORREO_ALTERNATIVO_50 = "ERROR_LARGO_CORREO_ALTERNATIVO_50";
    public static final String ERROR_LARGO_CORREO_COORDINADOR_50 = "ERROR_LARGO_CORREO_COORDINADOR_50";
    public static final String ERROR_LARGO_CORREO_RESPONSABLE_ADMINISTRATIVO_50 = "ERROR_LARGO_CORREO_RESPONSABLE_ADMINISTRATIVO_50";
    public static final String ERROR_LARGO_TELEFONO_COORDINADOR_20 = "ERROR_LARGO_TELEFONO_COORDINADOR_20";
    public static final String ERROR_LARGO_TELEFONO_RESPONSABLE_ADMINISTRATIVO_20 = "ERROR_LARGO_TELEFONO_RESPONSABLE_ADMINISTRATIVO_20";
    public static final String ERROR_CORREO_CORREO_ALTERNATIVO_IGUALES = "ERROR_CORREO_CORREO_ALTERNATIVO_IGUALES";
    public static final String ERROR_IP_VACIO = "ERROR_IP_VACIO";
    public static final String ERROR_IP_VACIO_LARGO_15 = "ERROR_IP_VACIO_LARGO_15";
    public static final String ERROR_IP_INVALIDA = "ERROR_IP_INVALIDA";
    public static final String ERROR_SINTAXIS_FORMULA = "ERROR_SINTAXIS_FORMULA";
    public static final String ERROR_PREGUNTA_VACIA = "ERROR_PREGUNTA_VACIA";
    public static final String ERROR_TELEFONO_20 = "ERROR_TELEFONO_20";
    public static final String ERROR_PLAZO_10ANIOS = "ERROR_PLAZO_10ANIOS";
    
    public static final String ERROR_RESPONSABLE_AF_VACIO = "ERROR_RESPONSABLE_AF_VACIO";
    public static final String ERROR_CARGO_RESPONSABLE_AF_VACIO = "ERROR_CARGO_RESPONSABLE_AF_VACIO";
    public static final String ERROR_LARGO_RESPONSABLE_AF_100 = "ERROR_LARGO_RESPONSABLE_AF_100";
    public static final String ERROR_LARGO_CARGO_RESPONSABLE_AF_100 = "ERROR_LARGO_CARGO_RESPONSABLE_AF_100";
    
    public static final String ERROR_PENTAHO_TIPO_COMPONENTE = "ERROR_PENTAHO_TIPO_COMPONENTE";
    public static final String ERROR_TIPO_ACUERDO_APLICA_A_TRAMITE_EXISTENTE = "ERROR_TIPO_ACUERDO_APLICA_A_TRAMITE_EXISTENTE";
    public static final String ERROR_PENTAHO_RUTA = "ERROR_PENTAHO_RUTA";
    public static final String ERROR_PENTAHO_OPERACION = "ERROR_PENTAHO_OPERACION";
    public static final String ERROR_PENTAHO_RUTA_VACIO = "ERROR_PENTAHO_RUTA_VACIO";
    public static final String ERROR_PENTAHO_OPERACION_255 = "ERROR_PENTAHO_OPERACION_255";
    


}