/*
 * Proyecto: Sistema Integrado de Administracion de Proyectos II
 * Organismo: Ministerio de Educacion de El Salvador
 * Desarrollado por: Sofis Solutions
 *
 */
package gob.mined.siap2.web.mb.impl;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

/**
 *
 * @author Sofis Solutions
 */
@Named(value = "ganttTemplates")
@ApplicationScoped
public class GanttTemplates {

    private static final String templateSimple = "  <div class=\"__template__\" type=\"GANTBUTTONS\"><!--"
            + "  <div class=\"ganttButtonBar noprint\">"
            + "    <div class=\"buttons\">"
            + "    <button onclick=\"$('#workSpace').trigger('undo.gantt');\" class=\"button textual\" title=\"undo\"><span class=\"teamworkIcon\">&#39;</span></button>"
            + "    <button onclick=\"$('#workSpace').trigger('redo.gantt');\" class=\"button textual\" title=\"redo\"><span class=\"teamworkIcon\">&middot;</span></button>"
            + "    <span class=\"ganttButtonSeparator\"></span>"
            + "    <button onclick=\"$('#workSpace').trigger('moveUpCurrentTask.gantt');\" class=\"button textual\" title=\"move up\">"
            + "    <span class=\"teamworkIcon\">k</span></button>"
            + "    <button onclick=\"$('#workSpace').trigger('moveDownCurrentTask.gantt');\" class=\"button textual\" title=\"move down\">"
            + "    <span class=\"teamworkIcon\">j</span></button>"
            + "    <span class=\"ganttButtonSeparator\"></span>"
            + "    <button onclick=\"$('#workSpace').trigger('zoomMinus.gantt');\" class=\"button textual\" title=\"zoom out\">"
            + "    <span class=\"teamworkIcon\">)</span></button>"
            + "    <button onclick=\"$('#workSpace').trigger('zoomPlus.gantt');\" class=\"button textual\" title=\"zoom in\"><span class=\"teamworkIcon\">(</span></button>"
            + "    <span class=\"ganttButtonSeparator\"></span>"
            + "    <button onclick=\"ge.gantt.showCriticalPath=!ge.gantt.showCriticalPath; ge.redraw();\" class=\"button textual\" title=\"Critical Path\">"
            + "    <span class=\"teamworkIcon\">&pound;</span></button>"
            + "    </div></div>"
            + "  --></div>"
            + "  <div class=\"__template__\" type=\"TASKSEDITHEAD\"><!--"
            + "  <table class=\"gdfTable\" cellspacing=\"0\" cellpadding=\"0\">"
            + "    <thead>"
            + "    <tr style=\"height:40px\">"
            + "      <th class=\"gdfColHeader\" style=\"width:35px;\"></th>"
            + "      <th class=\"gdfColHeader gdfResizable\" style=\"width:30px;\">Código</th>"
            + "      <th class=\"gdfColHeader gdfResizable\" style=\"width:300px;\">Nombre</th>"
            + "      <th class=\"gdfColHeader gdfResizable\" style=\"width:80px;\">Inicio</th>"
            + "      <th class=\"gdfColHeader gdfResizable\" style=\"width:80px;\">Fin</th>"
            + "      <th class=\"gdfColHeader gdfResizable\" style=\"width:50px;\">Dur.</th>"
            + "      <th class=\"gdfColHeader gdfResizable\" style=\"width:50px;\">Hora Fin</th>"
            + "      <th class=\"gdfColHeader gdfResizable\" style=\"width:50px;\">Dep.</th>"
            + "    </tr>"
            + "    </thead>"
            + "  </table>"
            + "  --></div>"
            + "  <div class=\"__template__\" type=\"TASKROW\"><!--"
            + "  <tr taskId=\"(#=obj.id#)\" class=\"taskEditRow\" level=\"(#=level#)\">"
            + "    <th class=\"gdfCell edit\" align=\"right\" style=\"cursor:pointer;\">"
            + "      <span class=\"taskRowIndex\">(#=obj.getRow()+1#)</span> "
            + "    </th>"
            + "    <td class=\"gdfCell\"><input type=\"text\" name=\"code\" value=\"(#=obj.code?obj.code:''#)\"></td>"
            + "    <td class=\"gdfCell indentCell\" style=\"padding-left:(#=obj.level*10#)px;\">"
            + "      <div class=\"(#=obj.isParent()?'exp-controller expcoll exp':'exp-controller'#)\" align=\"center\"></div>"
            + "      <input type=\"text\" name=\"name\" value=\"(#=obj.name#)\">"
            + "    </td>"
            + "    <td class=\"gdfCell\"><input type=\"text\" name=\"start\"  value=\"\" class=\"date\"></td>"
            + "    <td class=\"gdfCell\"><input type=\"text\" name=\"end\" value=\"\" class=\"date\"></td>"
            + "    <td class=\"gdfCell\"><input type=\"text\" name=\"duration\" value=\"(#=obj.duration#)\"></td>"
            + "    <td class=\"gdfCell\"><input type=\"time\" name=\"horaFin\" value=\"(#=obj.horaFin#)\"></td>"
            + "    <td class=\"gdfCell\"><input type=\"text\" name=\"depends\" value=\"(#=obj.depends#)\" (#=obj.hasExternalDep?\"readonly\":\"\"#)></td>"
            + "  </tr>"
            + "  --></div>"
            + "  <div class=\"__template__\" type=\"TASKEMPTYROW\"><!--"
            + "  <tr class=\"taskEditRow emptyRow\" >"
            + "    <th class=\"gdfCell\" align=\"right\"></th>"
            + "    <td class=\"gdfCell noClip\" align=\"center\"></td>"
            + "    <td class=\"gdfCell\"></td>"
            + "    <td class=\"gdfCell\"></td>"
            + "    <td class=\"gdfCell\"></td>"
            + "    <td class=\"gdfCell\"></td>"
            + "    <td class=\"gdfCell\"></td>"
            + "    <td class=\"gdfCell\"></td>"
            + "    <td class=\"gdfCell\"></td>"
            + "    <td class=\"gdfCell\"></td>"
            + "  </tr>"
            + "  --></div>"
            + "  <div class=\"__template__\" type=\"TASKBAR\"><!--"
            + "  <div class=\"taskBox taskBoxDiv\" taskId=\"(#=obj.id#)\" >"
            + "    <div class=\"layout (#=obj.hasExternalDep?'extDep':''#)\">"
            + "      <div class=\"taskStatus\" status=\"(#=obj.status#)\"></div>"
            + "      <div class=\"taskProgress\" style=\"width:(#=obj.progress>100?100:obj.progress#)%; background-color:(#=obj.progress>100?'red':'rgb(153,255,51);'#);\"></div>"
            + "      <div class=\"milestone (#=obj.startIsMilestone?'active':''#)\" ></div>"
            + "      <div class=\"taskLabel\"></div>"
            + "      <div class=\"milestone end (#=obj.endIsMilestone?'active':''#)\" ></div>"
            + "    </div>"
            + "  </div>"
            + "  --></div>"
            + "  <div class=\"__template__\" type=\"CHANGE_STATUS\"><!--"
            + "    <div class=\"taskStatusBox\">"
            + "      <div class=\"taskStatus cvcColorSquare\" status=\"STATUS_ACTIVE\" title=\"active\"></div>"
            + "      <div class=\"taskStatus cvcColorSquare\" status=\"STATUS_DONE\" title=\"completed\"></div>"
            + "      <div class=\"taskStatus cvcColorSquare\" status=\"STATUS_FAILED\" title=\"failed\"></div>"
            + "      <div class=\"taskStatus cvcColorSquare\" status=\"STATUS_SUSPENDED\" title=\"suspended\"></div>"
            + "      <div class=\"taskStatus cvcColorSquare\" status=\"STATUS_UNDEFINED\" title=\"undefined\"></div>"
            + "    </div>"
            + "  --></div>"
            //modal editar
            + "  <div class=\"__template__\" type=\"TASK_EDITOR\"><!--"
            + "  <div class=\"ganttTaskEditor\">"
            + "  <table width=\"100%\">"
            + "    <tr>"
            + "      <td>"
            + "        <table cellpadding=\"5\">"
            + "          <tr>"
            + "            <td><label for=\"code\">code/short name</label><br><input type=\"text\" name=\"code\" id=\"code\" value=\"\" class=\"formElements form-control\"></td>"
            + "           </tr><tr>"
            + "            <td><label for=\"name\">name</label><br><input type=\"text\" name=\"name\" id=\"name\" value=\"\"  size=\"35\" class=\"formElements form-control\"></td>"
            + "          </tr>"
            + "          <tr></tr>"
            + "            <td>"
            + "              <label for=\"description\">description</label><br>"
            + "              <textarea rows=\"5\" cols=\"30\" id=\"description\" name=\"description\" class=\"formElements form-control\"></textarea>"
            + "            </td>"
            + "          </tr>"
            + "        </table>"
            + "      </td>"
            + "      <td valign=\"top\">"
            + "        <table cellpadding=\"5\">"
            + "          <tr>"
            + "          <td colspan=\"2\"><label for=\"status\">status</label><br><div id=\"status\" class=\"taskStatus\" status=\"\"></div></td>"
            + "          <tr>"
            + "          <td colspan=\"2\">"
            + "          <label for=\"progress\">progress</label><br><input type=\"text\" name=\"progress\" id=\"progress\" value=\"\" size=\"3\" class=\"formElements form-control\"></td>"
            + "          </tr>"
            + "          <tr>"
            + "          <td><label for=\"start\">start</label><br><input type=\"text\" name=\"start\" id=\"start\"  value=\"\" class=\"date\" size=\"10\" class=\"formElements form-control\">"
            + "          <input type=\"checkbox\" id=\"startIsMilestone\"> </td>"
            + "          <td rowspan=\"2\" class=\"graph\" style=\"padding-left:50px\"><label for=\"duration\">dur.</label><br>"
            + "          <input type=\"text\" name=\"duration\" id=\"duration\" value=\"\"  size=\"5\" class=\"formElements form-control\"></td>"
            + "        </tr><tr>"
            + "          <td><label for=\"end\">end</label><br>"
            + "          <input type=\"text\" name=\"end\" id=\"end\" value=\"\" class=\"date\"  size=\"10\" class=\"formElements form-control\"><input type=\"checkbox\" id=\"endIsMilestone\"></td>"
            + "        </table>"
            + "      </td>"
            + "    </tr>"
            + "    </table>"
            + "  <h2>assignments</h2>"
            + "  <table  cellspacing=\"1\" cellpadding=\"0\" width=\"100%\" id=\"assigsTable\">"
            + "    <tr>"
            + "      <th style=\"width:100px;\">name</th>"
            + "      <th style=\"width:70px;\">role</th>"
            + "      <th style=\"width:30px;\">est.wklg.</th>"
            + "      <th style=\"width:30px;\" id=\"addAssig\"><span class=\"teamworkIcon\" style=\"cursor: pointer\">+</span></th>"
            + "    </tr>"
            + "  </table>"
            + "  <div style=\"text-align: right; padding-top: 20px\"><button id=\"saveButton\" class=\"button big\">save</button></div>"
            + "  </div>"
            + "  --></div>"
            //end editar
            + "  <div class=\"__template__\" type=\"ASSIGNMENT_ROW\"><!--"
            + "  <tr taskId=\"(#=obj.task.id#)\" assigId=\"(#=obj.assig.id#)\" class=\"assigEditRow\" >"
            + "    <td ><select name=\"resourceId\"  class=\"formElements form-control\" (#=obj.assig.id.indexOf(\"tmp_\")==0?\"\":\"disabled\"#) ></select></td>"
            + "    <td ><select type=\"select\" name=\"roleId\"  class=\"formElements form-control\"></select></td>"
            + "    <td ><input type=\"text\" name=\"effort\" value=\"(#=getMillisInHoursMinutes(obj.assig.effort)#)\" size=\"5\" class=\"formElements form-control\"></td>"
            + "    <td align=\"center\"><span class=\"teamworkIcon delAssig\" style=\"cursor: pointer\">d</span></td>"
            + "  </tr>"
            + "  --></div>"
            + "  <div class=\"__template__\" type=\"RESOURCE_EDITOR\"><!--"
            + "  <div class=\"resourceEditor\" style=\"padding: 5px;\">"
            + "    <h2>Project team</h2>"
            + "    <table  cellspacing=\"1\" cellpadding=\"0\" width=\"100%\" id=\"resourcesTable\">"
            + "      <tr>"
            + "        <th style=\"width:100px;\">name</th>"
            + "        <th style=\"width:30px;\" id=\"addResource\"><span class=\"teamworkIcon\" style=\"cursor: pointer\">+</span></th>"
            + "      </tr>"
            + "    </table>"
            + "    <div style=\"text-align: right; padding-top: 20px\"><button id=\"resSaveButton\" class=\"button big\">save</button></div>"
            + "  </div>"
            + "  --></div>"
            + "  <div class=\"__template__\" type=\"RESOURCE_ROW\"><!--"
            + "  <tr resId=\"(#=obj.id#)\" class=\"resRow\" >"
            + "    <td ><input type=\"text\" name=\"name\" value=\"(#=obj.name#)\" style=\"width:100%;\" class=\"formElements form-control\"></td>"
            + "    <td align=\"center\"><span class=\"teamworkIcon delRes\" style=\"cursor: pointer\">d</span></td>"
            + "  </tr>"
            + "  --></div>";

    public String printTemplatesSimple() {
        return templateSimple;
    }

}
