/*
 *  SIGES
 *  Desarrollado por Sofis Solutions
 */
package sv.gob.mined.siges.negocio.mensajes;

/**
 * Constantes de mensajes de error
 *
 * @author jgiron
 */
public class Errores {

    public static final String ERROR_GENERAL = "ERROR_GENERAL";
    public static final String ERROR_OPTIMISTIC_LOCK = "ERROR_OPTIMISTIC_LOCK";
    public static final String ERROR_CODIGO_O_NOMBRE_DUPLICADOS = "ERROR_CODIGO_O_NOMBRE_DUPLICADOS";
    public static final String ERROR_CODIGO_DUPLICADO = "ERROR_CODIGO_DUPLICADO";
    public static final String ERROR_NOMBRE_DUPLICADO = "ERROR_NOMBRE_DUPLICADO";
    public static final String ERROR_ENTIDAD_REFERENCIADA = "ERROR_ENTIDAD_REFERENCIADA";
    public static final String ERROR_ARCHIVO_VACIO = "ERROR_ARCHIVO_VACIO";
    public static final String ERROR_DATO_VACIO = "ERROR_DATO_VACIO";
    public static final String ERROR_CODIGO_VACIO = "ERROR_CODIGO_VACIO";
    public static final String ERROR_NOMBRE_VACIO = "ERROR_NOMBRE_VACIO";
    public static final String ERROR_NUMERO_DOCUMENTO_VACIO = "ERROR_NUMERO_DOCUMENTO_VACIO";
    public static final String ERROR_NOMBRE_COMPONENTE_VACIO = "ERROR_NOMBRE_COMPONENTE_VACIO";
    public static final String ERROR_NOMBRE_UNIDAD_VACIO = "ERROR_NOMBRE_UNIDAD_VACIO";
    public static final String ERROR_SEDE_VACIO = "ERROR_SEDE_VACIO";
    public static final String ERROR_TIPO_PARENTESCO_VACIO = "ERROR_TIPO_PARENTESCO";
    public static final String ERROR_TIPO_DOCUMENTO_VACIO = "ERROR_TIPO_DOCUMENTO_VACIO";
    public static final String ERROR_TIPO_MANIFESTACIONO_VACIO = "ERROR_TIPO_MANIFESTACIONO_VACIO";
    public static final String ERROR_MUNICIPIO_VACIO = "ERROR_MUNICIPIO_VACIO";
    public static final String ERROR_MUNICIPIO_NACIMIENTO_VACIO = "ERROR_MUNICIPIO_NACIMIENTO_VACIO";
    public static final String ERROR_DEPARTAMENTO_VACIO = "ERROR_DEPARTAMENTO_VACIO";
    public static final String ERROR_DEPARTAMENTO_NACIMIENTO_VACIO = "ERROR_DEPARTAMENTO_NACIMIENTO_VACIO";
    public static final String ERROR_DIRECCION_VACIA = "ERROR_DIRECCION_VACIA";
    public static final String ERROR_ESTUDIANTE_VACIO = "ERROR_ESTUDIANTE_VACIO";
    public static final String ERROR_PERSONA_VACIA = "ERROR_PERSONA_VACIA";
    public static final String ERROR_PAIS_EMISOR_VACIO = "ERROR_PAIS_EMISOR_VACIO";
    public static final String ERROR_MOTIVO_INASISTENCIA_VACIO = "ERROR_MOTIVO_INASISTENCIA_VACIO";
    public static final String ERROR_SECCION_VACIO = "ERROR_SECCION_VACIO";
    public static final String ERROR_FECHA_VACIO = "ERROR_FECHA_VACIO";
    public static final String ERROR_RELACION_MODALIDAD_VACIA = "ERROR_RELACION_MODALIDAD_VACIA";
    public static final String ERROR_MODALIDAD_EDUCATIVA_VACIO = "ERROR_MODALIDAD_EDUCATIVA_VACIO";
    public static final String ERROR_MODALIDAD_ATENCION_VACIO = "ERROR_MODALIDAD_ATENCION_VACIO";
    public static final String ERROR_DESCRIPCION_VACIO = "ERROR_DESCRIPCION_VACIO";
    public static final String ERROR_LARGO_DESCRIPCION_500 = "ERROR_LARGO_DESCRIPCION_500";
    public static final String ERROR_LARGO_DESCRIPCION_255 = "ERROR_LARGO_DESCRIPCION_255";
    public static final String ERROR_LARGO_DESCRIPCION_50 = "ERROR_LARGO_DESCRIPCION_50";
    public static final String ERROR_LARGO_ESTADO_20 = "ERROR_LARGO_ESTADO_20";
    public static final String ERROR_ESTADO_VACIO = "ERROR_ESTADO_VACIO";

    public static final String ERROR_GRADO_VACIO = "ERROR_GRADO_VACIO";

    public static final String ERROR_OPCION_VACIO = "ERROR_OPCION_VACIO";
    public static final String ERROR_ANIO_VACIO = "ERROR_ANIO_VACIO";
    public static final String ERROR_CONTENIDO_VACIO = "ERROR_CONTENIDO_VACIO";
    public static final String ERROR_PROGRAMA_EDUCATIVO_VACIO = "ERROR_PROGRAMA_EDUCATIVO_VACIO";

    public static final String ERROR_LARGO_NOMBRE_255 = "ERROR_LARGO_NOMBRE_255";
    public static final String ERROR_LARGO_COMPONENTE_255 = "ERROR_LARGO_COMPONENTE_255";
    public static final String ERROR_LARGO_UNIDAD_255 = "ERROR_LARGO_UNIDAD_255";
    public static final String ERROR_LARGO_NOMBRE_500 = "ERROR_LARGO_NOMBRE_500";
    public static final String ERROR_LARGO_DIRECCION_500 = "ERROR_LARGO_DIRECCION_500";
    public static final String ERROR_LARGO_CODIGO_45 = "ERROR_LARGO_CODIGO_45";
    public static final String ERROR_LARGO_CODIGO_4 = "ERROR_LARGO_CODIGO_4";
    public static final String ERROR_LARGO_CODIGO_5 = "ERROR_LARGO_CODIGO_5";
    public static final String ERROR_LARGO_CODIGO_10 = "ERROR_LARGO_CODIGO_10";
    public static final String ERROR_LARGO_CODIGO_15 = "ERROR_LARGO_CODIGO_15";
    public static final String ERROR_LARGO_CODIGO_20 = "ERROR_LARGO_CODIGO_20";
    public static final String ERROR_LARGO_CONTENIDO_5000 = "ERROR_LARGO_CONTENIDO_5000";
    public static final String ERROR_PLAN_ESTUDIO_VACIO = "ERROR_PLAN_ESTUDIO_VACIO";
    public static final String ERROR_ESCALA_CALIFICACION_VACIO = "ERROR_ESCALA_CALIFICACION_VACIO";
    public static final String ERROR_FECHA_DESDE_MAYOR_HASTA = "ERROR_FECHA_DESDE_MAYOR_HASTA";
    public static final String ERROR_PRIMER_NOMBRE_VACIO = "ERROR_PRIMER_NOMBRE_VACIO";
    public static final String ERROR_PRIMER_APELLIDO_VACIO = "ERROR_PRIMER_APELLIDO_VACIO";
    public static final String ERROR_PRIMER_NOMBRE_100 = "ERROR_PRIMER_NOMBRE_100";
    public static final String ERROR_SEGUNDO_NOMBRE_100 = "ERROR_SEGUNDO_NOMBRE_100";
    public static final String ERROR_TERCER_NOMBRE_100 = "ERROR_TERCER_NOMBRE_100";
    public static final String ERROR_PRIMER_APELLIDO_100 = "ERROR_PRIMER_APELLIDO_100";
    public static final String ERROR_SEGUNDO_APELLIDO_100 = "ERROR_SEGUNDO_APELLIDO_100";
    public static final String ERROR_TERCER_APELLIDO_100 = "ERROR_TERCER_APELLIDO_100";
    public static final String ERROR_SEXO_VACIO = "ERROR_SEXO_VACIO";
    public static final String ERROR_FECHA_NACIMIENTO_VACIO = "ERROR_FECHA_NACIMIENTO_VACIO";
    public static final String ERROR_ESTADO_CIVIL_VACIO = "ERROR_ESTADO_CIVIL_VACIO";
    public static final String ERROR_ETNIA_VACIO = "ERROR_ETNIA_VACIO";
    public static final String ERROR_TELEFONO_VACIO = "ERROR_TELEFONO_VACIO";

    public static final String ERROR_VALORACION_VACIO = "ERROR_VALORACION_VACIO";
    public static final String ERROR_VALORACION_500 = "ERROR_VALORACION_500";
    public static final String ERROR_TIPO_VALORACION_VACIO = "ERROR_TIPO_VALORACION_VACIO";
    public static final String ERROR_FECHA_VALORACION_VACIO = "ERROR_FECHA_VALORACION_VACIO";
    public static final String ERROR_FECHA_MAYOR_HOY = "ERROR_FECHA_MAYOR_HOY";
    public static final String ERROR_CATEGORIA_VACIO = "ERROR_CATEGORIA_VACIO";
    public static final String ERROR_CARGO_VACIO = "ERROR_CARGO_VACIO";
    public static final String ERROR_JORNADA_VACIO = "ERROR_JORNADA_VACIO";
    public static final String ERROR_HASTA_VACIO = "ERROR_HASTA_VACIO";
    public static final String ERROR_DESDE_VACIO = "ERROR_DESDE_VACIO";
    public static final String ERROR_INSTITUCION_VACIO = "ERROR_INSTITUCION_VACIO";
    public static final String ERROR_ESCOLARIDAD_VACIO = "ERROR_ESCOLARIDAD_VACIO";
    public static final String ERROR_SISTEMA_GESTION_CONTENIDO_VACIO = "ERROR_SISTEMA_GESTION_CONTENIDO_VACIO";
    public static final String ERROR_IDIOMA_VACIO = "ERROR_IDIOMA_VACIO";
    public static final String ERROR_NIVEL_IDIOMA_VACIO = "ERROR_NIVEL_IDIOMA_VACIO";
    public static final String ERROR_ESTUDIOS_REALIZADOS_VACIO = "ERROR_ESTUDIOS_REALIZADOS_VACIO";

    public static final String ERROR_TIPO_VACIO = "ERROR_TIPO_VACIO";
    public static final String ERROR_PAIS_VACIO = "ERROR_PAIS_VACIO";
    public static final String ERROR_CARRERA_VACIO = "ERROR_CARRERA_VACIO";
    public static final String ERROR_ESPECIALIDAD_VACIO = "ERROR_ESPECIALIDAD_VACIO";
    public static final String ERROR_INSTITUCION_ESTUDIO_VACIO = "ERROR_INSTITUCION_ESTUDIO_VACIO";
    public static final String ERROR_MODALIDAD_VACIO = "ERROR_MODALIDAD_VACIO";
    public static final String ERROR_ANIO_TITULACION_VACIO = "ERROR_ANIO_TITULACION_VACIO";
    public static final String ERROR_CURSO_ACREDITADO_VACIO = "ERROR_CURSO_ACREDITADO_VACIO";
    public static final String ERROR_ALCANCE_CAPACITACION_VACIO = "ERROR_ALCANCE_CAPACITACION_VACIO";
    public static final String ERROR_DURACION_HORAS_VACIO = "ERROR_DURACION_HORAS_VACIO";
    public static final String ERROR_ESTUDIOS_VACIO = "ERROR_ESTUDIOS_VACIO";
    public static final String ERROR_NOMBRE_CAPACITACION_VACIO = "ERROR_NOMBRE_CAPACITACION_VACIO";
    public static final String ERROR_TIPO_CAPACITACION_VACIO = "ERROR_TIPO_CAPACITACION_VACIO";
    public static final String ERROR_APROBADO_VACIO = "ERROR_APROBADO_VACIO";
    public static final String ERROR_CALIFICACION_VACIO = "ERROR_CALIFICACION_VACIO";
    public static final String ERROR_LARGO_CALIFICACION_20 = "ERROR_LARGO_CALIFICACION_20";
    public static final String ERROR_MODULO_VACIO = "ERROR_MODULO_VACIO";
    public static final String ERROR_NIVEL_VACIO = "ERROR_NIVEL_VACIO";
    public static final String ERROR_NIE_VACIO = "ERROR_NIE_VACIO";
    public static final String ERROR_TIPO_CALENDARIO_VACIO = "ERROR_TIPO_CALENDARIO_VACIO";
    public static final String ERROR_ANIO_LECTIVO_VACIO = "ERROR_ANIO_LECTIVO_VACIO";
    public static final String ERROR_FECHA_INICIO_VACIA = "ERROR_FECHA_INICIO_VACIA";
    public static final String ERROR_FECHA_FIN_VACIA = "ERROR_FECHA_FIN_VACIA";
    public static final String ERROR_RANGO_DE_FECHAS = "ERROR_RANGO_DE_FECHAS";
    public static final String ERROR_RANGO_SUPERA_MAXIMO = "ERROR_RANGO_SUPERA_MAXIMO";
    public static final String ERROR_TIPO_ACTIVIDAD_VACIO = "ERROR_TIPO_ACTIVIDAD_VACIO";
    public static final String ERROR_MOTIVO_RETIRO_VACIO = "ERROR_MOTIVO_RETIRO_VACIO";
    public static final String ERROR_FECHA_INGRESO_GOB_MAYOR = "ERROR_FECHA_INGRESO_GOB_MAYOR";
    public static final String ERROR_FECHA_INGRESO_MINED_MAYOR = "ERROR_FECHA_INGRESO_MINED_MAYOR";
    public static final String ERROR_FECHA_DESDE_MAYOR = "ERROR_FECHA_DESDE_MAYOR";
    public static final String ERROR_FECHA_HASTA_MAYOR = "ERROR_FECHA_HASTA_MAYOR";

    public static final String ERROR_ANIO_DUPLICADO = "ERROR_ANIO_DUPLICADO";
    public static final String ERROR_LEY_SALARIO_VACIO = "ERROR_LEY_SALARIO_VACIO";
    public static final String ERROR_FUENTE_FINANCIAMIENTO_VACIO = "ERROR_FUENTE_FINANCIAMIENTO_VACIO";
    public static final String ERROR_INSTITUCION_PAGA_SALARIO_VACIO = "ERROR_INSTITUCION_PAGA_SALARIO_VACIO";
    public static final String ERROR_TIPO_INSTITUCION_PAGA_VACIO = "ERROR_TIPO_INSTITUCION_PAGA_VACIO";
    public static final String ERROR_TIPO_CONTRATO_VACIO = "ERROR_TIPO_CONTRATO_VACIO";
    public static final String ERROR_FECHA_DESDE_VACIO = "ERROR_FECHA_DESDE_VACIO";
    public static final String ERROR_FECHA_HASTA_VACIO = "ERROR_FECHA_HASTA_VACIO";
    public static final String ERROR_HORA_INGRESO_VACIO = "ERROR_HORA_INGRESO_VACIO";
    public static final String ERROR_HORA_SALIDA_VACIO = "ERROR_HORA_SALIDA_VACIO";
    public static final String ERROR_SALARIO_MENSUAL_VACIO = "ERROR_SALARIO_MENSUAL_VACIO";
    public static final String ERROR_MODO_PAGO_VACIO = "ERROR_MODO_PAGO_VACIO";
    public static final String ERROR_ESTADO_CONTRATACION_VACIO = "ERROR_ESTADO_CONTRATACION_VACIO";
    public static final String ERROR_TIPO_INSTITUCION_VACIO = "ERROR_TIPO_INSTITUCION_VACIO";
    public static final String ERROR_CALENDARIO_VACIO = "ERROR_CALENDARIO_VACIO";
    public static final String ERROR_CANTIDAD_DE_RANGOS_SUPERA_PERMITIDOS_EN_PERIODO = "ERROR_CANTIDAD_DE_RANGOS_SUPERA_PERMITIDOS_EN_PERIODO";
    public static final String ERROR_IDENTIFICACIONES_VACIO = "ERROR_IDENTIFICACIONES_VACIO";
    public static final String ERROR_ELIMINAR_ARCHIVO = "ERROR_ELIMINAR_ARCHIVO";
    public static final String ERROR_PATH_VACIO = "ERROR_PATH_VACIO";
    public static final String ERROR_LARGO_PATH_500 = "ERROR_LARGO_PATH_500";
    public static final String ERROR_ANIO_INICIO_MENOR_1800 = "ERROR_ANIO_INICIO_MENOR_1800";
    public static final String ERROR_ANIO_INICIO_MAYOR_ACTUAL = "ERROR_ANIO_INICIO_MAYOR_ACTUAL";
    public static final String ERROR_LARGO_CORREO_100 = "ERROR_LARGO_CORREO_100";
    public static final String ERROR_DUI_INCORRECTO = "ERROR_DUI_INCORRECTO";
    public static final String ERROR_CUN_INCORRECTO = "ERROR_CUN_INCORRECTO";
    public static final String ERROR_NIE_INCORRECTO = "ERROR_NIE_INCORRECTO";
    public static final String ERROR_DUI_VACIO = "ERROR_DUI_VACIO";
    public static final String ERROR_PARTIDA_NACIMIENTO_NUMERO_VACIO = "ERROR_PARTIDA_NACIMIENTO_NUMERO_VACIO";
    public static final String ERROR_PARTIDA_NACIMIENTO_LIBRO_VACIO = "ERROR_PARTIDA_NACIMIENTO_LIBRO_VACIO";
    public static final String ERROR_PARTIDA_NACIMIENTO_FOLIO_VACIO = "ERROR_PARTIDA_NACIMIENTO_FOLIO_VACIO";
    public static final String ERROR_PARTIDA_NACIMIENTO_ANIO_VACIO = "ERROR_PARTIDA_NACIMIENTO_ANIO_VACIO";
    public static final String ERROR_PARTIDA_NACIMIENTO_ANIO_MAYOR_ACTUAL = "ERROR_PARTIDA_NACIMIENTO_ANIO_MAYOR_ACTUAL";
    public static final String ERROR_NACIONALIDAD_VACIA = "ERROR_NACIONALIDAD_VACIA";
    public static final String ERROR_RESPONSABLE_VACIO = "ERROR_RESPONSABLE_VACIO";
    public static final String ERROR_PROPIETARIO_VACIO = "ERROR_PROPIETARIO_VACIO";
    public static final String ERROR_LARGO_SITIO_WEB_100 = "ERROR_LARGO_SITIO_WEB_100";
    public static final String ERROR_LARGO_CODIGO_60 = "ERROR_LARGO_CODIGO_60";
    public static final String ERROR_SEGURIDAD = "ERROR_SEGURIDAD";
    public static final String ERROR_CANTIDAD_VACIO = "ERROR_CANTIDAD_VACIO";
    public static final String ERROR_OBSERVACION_VACIO = "ERROR_OBSERVACION_VACIO";
    public static final String ERROR_INASISTENCIA_MOTIVO_VACIO = "ERROR_INASISTENCIA_MOTIVO_VACIO";
    public static final String ERROR_DENOMINACION_VACIO = "ERROR_DENOMINACION_VACIO";
    public static final String ERROR_TIPO_TRABAJO_VACIO = "ERROR_TIPO_TRABAJO_VACIO";
    public static final String ERROR_TITULO_VACIO = "ERROR_TITULO_VACIO";
    public static final String ERROR_TITULO_255 = "ERROR_TITULO_255";
    public static final String ERROR_ORDEN_VACIO = "ERROR_ORDEN_VACIO";
    public static final String ERROR_LARGO_TRATAMIENTO_500 = "ERROR_LARGO_TRATAMIENTO_500";
    public static final String ERROR_LARGO_OBSERVACIONES_255 = "ERROR_LARGO_OBSERVACIONES_255";
    public static final String ERROR_OBSERVACIONES_VACIO = "ERROR_OBSERVACIONES_VACIO";
    public static final String ERROR_CONSTRAINT_EXCEPTION = "ERROR_CONSTRAINT_EXCEPTION";
    public static final String ERROR_DUI_DUPLICADO = "ERROR_DUI_DUPLICADO";
    public static final String ERROR_CUN_DUPLICADO = "ERROR_CUN_DUPLICADO";
    public static final String ERROR_NIP_DUPLICADO = "ERROR_NIP_DUPLICADO";
    public static final String ERROR_NIE_DUPLICADO = "ERROR_NIE_DUPLICADO";
    public static final String ERROR_MODALIDAD_EDUCATIVA_MODALIDAD_ATENCION = "ERROR_MODALIDAD_EDUCATIVA_MODALIDAD_ATENCION";
    public static final String ERROR_COMPONENTE_PLAN_ESTUDIO_VACIO = "ERROR_COMPONENTE_PLAN_ESTUDIO_VACIO";
    public static final String ERROR_AFP_VACIA = "ERROR_AFP_VACIA";
    public static final String ERROR_NUMERO_DOCUMENTO_50 = "ERROR_NUMERO_DOCUMENTO_50";
    public static final String ERROR_CORREO_ELECTRONICO_100 = "ERROR_CORREO_ELECTRONICO_100";
    public static final String ERROR_TIPO_TELEFONO_VACIO = "ERROR_TIPO_TELEFONO_VACIO";
    public static final String ERROR_LARGO_DIRECCION_255 = "ERROR_LARGO_DIRECCION_255";
    public static final String ERROR_ZONA_VACIO = "ERROR_ZONA_VACIO";
    public static final String ERROR_FECHA_NACIMIENTO_MAYOR_ACTUAL = "ERROR_FECHA_NACIMIENTO_MAYOR_ACTUAL";
    public static final String ERROR_FECHA_INGRESO_VACIO = "ERROR_FECHA_INGRESO_VACIO";
    public static final String ERROR_FECHA_INGRESO_MAYOR_ACTUAL = "ERROR_FECHA_INGRESO_MAYOR_ACTUAL";
    public static final String ERROR_EMAIL_FORMATO_INVALIDO = "ERROR_EMAIL_FORMATO_INVALIDO";
    public static final String ERROR_ESTUDIANTE_PROPIO_REFERENTE = "ERROR_ESTUDIANTE_PROPIO_REFERENTE";
    public static final String ERROR_ESTUDIANTE_PROPIO_FAMILIAR = "ERROR_ESTUDIANTE_PROPIO_FAMILIAR";
    public static final String ERROR_MATRICULA_ABIERTA_ESTUDIANTE = "ERROR_MATRICULA_ABIERTA_ESTUDIANTE";
    public static final String ERROR_LUGAR_TRABAJO_255 = "ERROR_LUGAR_TRABAJO_255";
    public static final String ERROR_SECCION_NO_ABIERTA = "ERROR_SECCION_NO_ABIERTA";
    public static final String ERROR_JORNADA_LABORAL_20 = "ERROR_JORNADA_LABORAL_20";
    public static final String ERROR_SALARIO_VACIO = "ERROR_SALARIO_VACIO";
    public static final String ERROR_LARGO_FACTOR_RIESGO_255 = "ERROR_LARGO_FACTOR_RIESGO_255";
    public static final String ERROR_TIPO_ORGANISMO_ADMINISTRATIVO_VACIO = "ERROR_TIPO_ORGANISMO_ADMINISTRATIVO_VACIO";
    public static final String ERROR_LARGO_CORREO_2_100 = "ERROR_LARGO_CORREO_2_100";
    public static final String ERROR_FECHA_SUPERPONE = "ERROR_FECHA_SUPERPONE";
    public static final String ERROR_NUP_DUPLICADO = "ERROR_NUP_DUPLICADO";
    public static final String ERROR_NIT_DUPLICADO = "ERROR_NIT_DUPLICADO";
    public static final String ERROR_ISSS_DUPLICADO = "ERROR_ISSS_DUPLICADO";
    public static final String ERROR_INPEP_DUPLICADO = "ERROR_INPEP_DUPLICADO";
    public static final String ERROR_OPTIMISTIC_LOCK_MATRICULA = "ERROR_OPTIMISTIC_LOCK_MATRICULA";
    public static final String ERROR_ESTUDIANTE_PERSONA_DUPLICADA = "ERROR_ESTUDIANTE_PERSONA_DUPLICADA";
    public static final String ERROR_CAMBIAR_PLAN_ESTUDIO_SECCION_CON_ESTUDIANTES = "ERROR_CAMBIAR_PLAN_ESTUDIO_SECCION_CON_ESTUDIANTES";
    public static final String ERROR_CAMBIAR_ANIO_LECTIVO_SECCION_CON_ESTUDIANTES = "ERROR_CAMBIAR_ANIO_LECTIVO_SECCION_CON_ESTUDIANTES";
    public static final String ERROR_CAMBIAR_JORNADA_SECCION_CON_ESTUDIANTES = "ERROR_CAMBIAR_JORNADA_SECCION_CON_ESTUDIANTES";
    public static final String ERROR_ACLARACION_FIRMA_VACIO = "ERROR_ACLARACION_FIRMA_VACIO";
    public static final String ERROR_FECHA_DOCUMENTO_VACIO = "ERROR_FECHA_DOCUMENTO_VACIO";
    public static final String ERROR_COMENTARIO_VACIO = "ERROR_COMENTARIO_VACIO";
    public static final String ERROR_TIPO_REPRESENTANTE_VACIO = "ERROR_TIPO_REPRESENTANTE_VACIO";
    public static final String ERROR_FIRMA_VACIO = "ERROR_FIRMA_VACIO";
    public static final String ERROR_SELLO_VACIO = "ERROR_SELLO_VACIO";
    public static final String ERROR_CANTIDAD_ESTUDIANTES_CERO = "ERROR_CANTIDAD_ESTUDIANTES_CERO";
    public static final String ERROR_NUMERO_CORRELATIVO = "ERROR_NUMERO_CORRELATIVO";
    public static final String ERROR_SEDE_SOLICITANTE_VACIO = "ERROR_SEDE_SOLICITANTE_VACIO";
    public static final String ERROR_SERVICIO_EDUCATIVO_SOLICITADO_VACIO = "ERROR_SERVICIO_EDUCATIVO_SOLICITADO_VACIO";
    public static final String ERROR_SEDE_ORIGEN_VACIO = "ERROR_SEDE_ORIGEN_VACIO";
    public static final String ERROR_ESTADO_SOLICITUD_TRASLADO_VACIO = "ERROR_ESTADO_SOLICITUD_TRASLADO_VACIO";
    public static final String ERROR_USUARIO_SOLICITUD_TRASLADO_VACIO = "ERROR_USUARIO_SOLICITUD_TRASLADO_VACIO";
    public static final String ERROR_RESOLUCION_VACIO = "ERROR_RESOLUCION_VACIO";
    public static final String ERROR_LARGO_RESOLUCION_500 = "ERROR_LARGO_RESOLUCION_500";
    public static final String ERROR_MOTIVO_TRASLADO_VACIO = "ERROR_MOTIVO_TRASLADO_VACIO";
    public static final String ERROR_SEDE_IGUAL_TRASLADO = "ERROR_SEDE_IGUAL_TRASLADO";
    public static final String ERROR_DEFINICION_TITULO_VACIO = "ERROR_DEFINICION_TITULO_VACIO";
    public static final String ERROR_SECCION_SOLICITUD_IMPRESION_VACIO = "ERROR_SECCION_SOLICITUD_IMPRESION_VACIO";
    public static final String ERROR_TITULAR_AUTENTICA_VACIO = "ERROR_TITULAR_AUTENTICA_VACIO";
    public static final String ERROR_DIRECTOR_SELLO_VACIO = "ERROR_DIRECTOR_SELLO_VACIO";
    public static final String ERROR_MINISTRO_SELLO_VACIO = "ERROR_MINISTRO_SELLO_VACIO";
    public static final String ERROR_SOLICITUD_TRASLADO_ACTIVA = "ERROR_SOLICITUD_TRASLADO_ACTIVA";
    public static final String ERROR_SERVICIO_EDUCATIVO_ORIGEN_VACIO = "ERROR_SERVICIO_EDUCATIVO_ORIGEN_VACIO";
    public static final String ERROR_MATRICULA_ACTUAL_VACIO = "ERROR_MATRICULA_ACTUAL_VACIO";
    public static final String ERROR_CALCULO_NOTA_INSTITUCIONAL_VACIO = "ERROR_CALCULO_NOTA_INSTITUCIONAL_VACIO";
    public static final String ERROR_FUNCION_REDONDEO_VACIO = "ERROR_FUNCION_REDONDEO_VACIO";
    public static final String ERROR_SEDE_SOLICITANTE_SIN_CALENDARIO = "ERROR_SEDE_SOLICITANTE_SIN_CALENDARIO";
    public static final String ERROR_FECHA_TRASLADO_FUERA_DE_CALENDARIO_SEDE_SOLICITANTE = "ERROR_FECHA_TRASLADO_FUERA_DE_CALENDARIO_SEDE_SOLICITANTE";
    public static final String ERROR_LARGO_OBSERVACIONES_250 = "ERROR_LARGO_OBSERVACIONES_250";
    public static final String ERROR_LARGO_NOTA_4000 = "ERROR_LARGO_NOTA_4000";

    public static final String ERROR_FECHA_TRASLADO_VACIA = "ERROR_FECHA_TRASLADO_VACIA";
    public static final String ERROR_SELLO_FIRMA_SEDE_TIPO_EXISTENTE = "ERROR_SELLO_FIRMA_SEDE_TIPO_EXISTENTE";
    public static final String ERROR_CALENDARIO_ANIO_TIPO_EXISTENTE = "ERROR_CALENDARIO_ANIO_TIPO_EXISTENTE";
    public static final String ERROR_LARGO_INSTITUCION_255 = "ERROR_LARGO_INSTITUCION_255";
    public static final String ERROR_INSTITUCION_255 = "ERROR_INSTITUCION_255";
    public static final String ERROR_LARGO_CARGO_100 = "ERROR_LARGO_CARGO_100";
    public static final String ERROR_LARGO_OBSERVACIONES_500 = "ERROR_LARGO_OBSERVACIONES_500";
    public static final String ERROR_TIPO_IDENTIFICACION_VACIO = "ERROR_TIPO_IDENTIFICACION_VACIO";
    public static final String ERROR_RANGO_DE_FECHAS_NO_COINCIDE_ANIO = "ERROR_RANGO_DE_FECHAS_NO_COINCIDE_ANIO";
    public static final String ERROR_NO_EXISTE_PATRON_CORREO_CATALOGO = "ERROR_NO_EXISTE_PATRON_CORREO_CATALOGO";
    public static final String ERROR_SECCION_CERRADA = "ERROR_SECCION_CERRADA";
    public static final String ERROR_GRADO_ACTUAL_MENOR_GRADO_ULTIMA_MATRICULA = "ERROR_GRADO_ACTUAL_MENOR_GRADO_ULTIMA_MATRICULA";
    public static final String ERROR_MODALIDADES_DIFIEREN_ULTIMA_MATRICULA = "ERROR_MODALIDADES_DIFIEREN_ULTIMA_MATRICULA";
    public static final String ERROR_RANGO_FECHA_FUERA_DE_RANGO_CALENDARIO = "ERROR_RANGO_FECHA_FUERA_DE_RANGO_CALENDARIO";
    public static final String ERROR_PROYECTO_INSTITUCIONAL_VACIO = "ERROR_PROYECTO_INSTITUCIONAL_VACIO";
    public static final String ERROR_IDENTIFICACION_DUPLICADA = "ERROR_IDENTIFICACION_DUPLICADA";
    public static final String ERROR_AMBITO_VACIO = "ERROR_AMBITO_VACIO";
    public static final String ERROR_AMBITO_INCORRECTO = "ERROR_AMBITO_INCORRECTO";
    public static final String ERROR_MATRICULA_YA_CERRADA = "ERROR_MATRICULA_YA_CERRADA";
    public static final String ERROR_HORARIO_ESCOLAR_VACIO = "ERROR_HORARIO_ESCOLAR_VACIO";
    public static final String ERROR_DOCENTE_VACIO = "ERROR_DOCENTE_VACIO";
    public static final String ERROR_RANGO_DE_FECHAS_NO_COINCIDE_ANIO_INTERACIONAL = "ERROR_RANGO_DE_FECHAS_NO_COINCIDE_ANIO_INTERACIONAL";
    public static final String ERROR_MATRICULA_SIN_CERRAR = "ERROR_MATRICULA_SIN_CERRAR";
    public static final String ERROR_FECHA_RETIRO_MENOR_INGRESO = "ERROR_FECHA_RETIRO_MENOR_INGRESO";
    public static final String ERROR_PARTIDA_NACIMIENTO_DUPLICADA = "ERROR_PARTIDA_NACIMIENTO_DUPLICADA";
    public static final String ERROR_TIPO_ACCION_VACIO = "ERROR_TIPO_ACCION_VACIO";
    public static final String ERROR_TIPO_APOYO_VACIO = "ERROR_TIPO_APOYO_VACIO";
    public static final String ERROR_TIPO_PROVEEDOR_VACIO = "ERROR_TIPO_PROVEEDOR_VACIO";
    public static final String ERROR_NOMBRE_PROVEEDOR_VACIO = "ERROR_NOMBRE_PROVEEDOR_VACIO";
    public static final String ERROR_LARGO_NOMBRE_PROVEEDOR_255 = "ERROR_LARGO_NOMBRE_PROVEEDOR_255";
    public static final String ERROR_TIPO_RIESGO_VACIO = "ERROR_TIPO_RIESGO_VACIO";
    public static final String ERROR_GRADO_RIESGO_VACIO = "ERROR_GRADO_RIESGO_VACIO";
    public static final String ERROR_FECHA_INICIO_MAYOR_FIN = "ERROR_FECHA_INICIO_MAYOR_FIN";

    public static final String ERROR_DEPARTAMENTO_PARTIDA_VACIO = "ERROR_DEPARTAMENTO_PARTIDA_VACIO";
    public static final String ERROR_MUNICIPIO_PARTIDA_VACIO = "ERROR_MUNICIPIO_PARTIDA_VACIO";

    public static final String ERROR_LARGO_DESCRIPCION_1000 = "ERROR_LARGO_DESCRIPCION_1000";

    public static final String ERROR_NUMERO_CUENTA_VACIO = "ERROR_NUMERO_CUENTA_VACIO";
    public static final String ERROR_CUENTA_COMENTARIO_VACIO = "ERROR_CUENTA_COMENTARIO_VACIO";
    public static final String ERROR_CUENTA_COMENTARIO_4000 = "ERROR_CUENTA_COMENTARIO_4000";

    public static final String ERROR_MCB_MONTO = "ERROR_MCB_MONTO";
    public static final String ERROR_MCB_TIPO_MOVIMIENTO = "ERROR_MCB_TIPO_MOVIMIENTO";
    public static final String ERROR_MCB_CUENTA_BANCARIA = "ERROR_MCB_CUENTA_BANCARIA";
    public static final String ERROR_MCB_DETALLE = "ERROR_MCB_DETALLE";
    public static final String ERROR_MCB_DETALLE_255 = "ERROR_MCB_DETALLE_255";
    public static final String ERROR_MCB_FECHA = "ERROR_MCB_FECHA";

    public static final String ERROR_TITULAR_VACIO = "ERROR_TITULAR_VACIO";
    public static final String ERROR_TITULAR_250 = "ERROR_TITULAR_250";
    public static final String ERROR_BANCO_VACIO = "ERROR_BANCO_VACIO";
    public static final String ERROR_DIRECCION_DEP_VACIO = "ERROR_DIRECCION_DEP_VACIO";
    public static final String ERROR_TRANSFERENCIA_CED = "ERROR_TRANSFERENCIA_CED";

    public static final String ERROR_NIT_VACIO = "ERROR_NIT_VACIO";
    public static final String ERROR_NIT_50 = "ERROR_NIT_50";
    public static final String ERROR_TELEFONO_20 = "ERROR_TELEFONO_20";
    public static final String ERROR_FAX_20 = "ERROR_FAX_20";
    public static final String ERROR_IP_50 = "ERROR_IP_50";
    public static final String ERROR_TIPO_CUENTA_BAC = "ERROR_TIPO_CUENTA_BAC";

    public static final String ERROR_COMPRA_CANTIDAD_VACIA = "ERROR_COMPRA_CANTIDAD_VACIA";
    public static final String ERROR_COMPRA_INSUMO_VACIO = "ERROR_COMPRA_INSUMO_VACIO";
    public static final String ERROR_COMPRA_DESCRIPCION_VACIA = "ERROR_COMPRA_DESCRIPCION_VACIA";
    public static final String ERROR_COMPRA_PRECIO_VACIO = "ERROR_COMPRA_PRECIO_VACIO";
    public static final String ERROR_COMPRA_FECHA_VACIA = "ERROR_COMPRA_FECHA_VACIA";
    public static final String ERROR_SUBAREA_INVERSION_VACIO = "ERROR_SUBAREA_INVERSION_VACIO";
    public static final String ERROR_FUENTE_INGRESO_VACIO = "ERROR_FUENTE_INGRESO_VACIO";
    public static final String ERROR_MONTO_VACIO = "ERROR_MONTO_VACIO";
    public static final String ERROR_ACTIVIDAD_VACIO = "ERROR_ACTIVIDAD_VACIO";

    public static final String ERROR_SAC_GOES_VACIO = "ERROR_SAC_GOES_VACIO";
    public static final String ERROR_SAC_GOES_45 = "ERROR_SAC_GOES_45";
    public static final String ERROR_SAC_UFI_VACIO = "ERROR_SAC_UFI_VACIO";
    public static final String ERROR_SAC_UFI_45 = "ERROR_SAC_UFI_45";
    public static final String ERROR_COMPROMISO_VACIO = "ERROR_COMPROMISO_VACIO";
    public static final String ERROR_COMPROMISO_45 = "ERROR_COMPROMISO_45";

    public static final String ERROR_SOL_TRANS_REQUERIMIENTO = "ERROR_SOL_TRANS_REQUERIMIENTO";
    public static final String ERROR_TRANS_CED_REQUERIMIENTO = "ERROR_TRANS_CED_REQUERIMIENTO";
    public static final String ERROR_MONTO_REQUERIMIENTO = "ERROR_MONTO_REQUERIMIENTO";

    public static final String ERROR_RUBRO_VACIO = "ERROR_RUBRO_VACIO";
    public static final String ERROR_DESCRIPCION_INGRESO_VACIO = "ERROR_DESCRIPCION_INGRESO_VACIO";
    public static final String ERROR_DESCRIPCION_255 = "ERROR_DESCRIPCION_255";
    public static final String ERROR_CUENTA_COMENTARIO_255 = "ERROR_CUENTA_COMENTARIO_255";

    public static final String ERROR_FACTURA_VACIA = "ERROR_FACTURA_VACIA";
    public static final String EROR_MODO_PAGO_VACIO = "EROR_MODO_PAGO_VACIO";
    public static final String ERROR_NUMERO_CHEQUE = "ERROR_NUMERO_CHEQUE";
    public static final String ERROR_FECHA_PAGO = "ERROR_FECHA_PAGO";
    public static final String ERROR_MCC_CAJA_CHICA = "ERROR_MCC_CAJA_CHICA";

    public static final String ERROR_NUMERO_FACTURA_VACIO = "ERROR_NUMERO_FACTURA_VACIO";
    public static final String ERROR_NUMERO_FACTURA_45 = "ERROR_NUMERO_FACTURA_45";
    public static final String ERROR_FACTURA_SEDE_VACIO = "ERROR_FACTURA_SEDE_VACIO";
    public static final String ERROR_FACTURA_ITEM_VACIO = "ERROR_FACTURA_ITEM_VACIO";
    public static final String ERROR_FACTURA_SUBTOTAL_VACIO = "ERROR_FACTURA_SUBTOTAL_VACIO";
    public static final String ERROR_FACTURA_FECHA_VACIO = "ERROR_FACTURA_FECHA_VACIO";
    public static final String ERROR_FACTURA_ITEM_MOVIMIENTOS_VACIO = "ERROR_FACTURA_ITEM_MOVIMIENTOS_VACIO";
    public static final String ERROR_FACTURA_ITEM_PLAN_VACIO = "ERROR_FACTURA_ITEM_PLAN_VACIO";
    public static final String ERROR_FACTURA_PROVEEDOR_VACIO = "ERROR_FACTURA_PROVEEDOR_VACIO";
    public static final String ERROR_FACTURA_TIPO_VACIO = "ERROR_FACTURA_TIPO_VACIO";

    public static final String ERROR_NOTA_CREDITO_VACIA = "ERROR_NOTA_CREDITO_VACIA";
    public static final String ERROR_NOTA_CREDITO_45 = "ERROR_NOTA_CREDITO_45";
    public static final String ERROR_NOTA_CREDITO_FECHA_VACIO = "ERROR_NOTA_CREDITO_FECHA_VACIO";

    public static final String ERROR_PROVEEDOR_NOMBRE_VACIO = "ERROR_PROVEEDOR_NOMBRE_VACIO";
    public static final String ERROR_PROVEEDOR_NIT_VACIO = "ERROR_PROVEEDOR_NIT_VACIO";
    public static final String ERROR_PROVEEDOR_CODIGO_VACIO = "ERROR_PROVEEDOR_CODIGO_VACIO";
    public static final String ERROR_PROVEEDOR_DIRECCION_VACIO = "ERROR_PROVEEDOR_DIRECCION_VACIO";
    public static final String ERROR_PROVEEDOR_TELEFONO_VACIO = "ERROR_PROVEEDOR_TELEFONO_VACIO";

    public static final String ERROR_DEPARTAMENTO_DUPLICADO = "ERROR_DEPARTAMENTO_DUPLICADO";

    public static final String ERROR_ANIO_FISCAL_VACIO = "ERROR_ANIO_FISCAL_VACIO";
    public static final String ERROR_SEDE_VACIA = "ERROR_SEDE_VACIA";
    public static final String ERROR_SUBCOMPONENTE_VACIA = "ERROR_SUBCOMPONENTE_VACIA";

    public static final String ERROR_TIPO_RETIRO_VACIO = "ERROR_TIPO_RETIRO_VACIO";
    public static final String ERROR_CHEQUE_RETIRO_VACIO = "ERROR_CHEQUE_RETIRO_VACIO";
    public static final String ERROR_MONTO_APROBADO_CERO = "ERROR_MONTO_APROBADO_CERO";
    public static final String ERROR_FACTURA_TIPO_DOC_VACIO = "ERROR_FACTURA_TIPO_DOC_VACIO";
    public static final String ERROR_ESTADO_DESEMBOLSO_VACIO = "ERROR_ESTADO_DESEMBOLSO_VACIO";
    public static final String ERROR_DET_DESEMBOLSO_VACIO = "ERROR_DET_DESEMBOLSO_VACIO";
    public static final String ERROR_FUENTE_INGRESO_VACIA = "ERROR_FUENTE_INGRESO_VACIA";
    public static final String ERROR_MOV_DESEMBOLSO_CED = "ERROR_MOV_DESEMBOLSO_CED";

    public static final String ERROR_LIQUIDACION_COMPONENTE_VACIO = "ERROR_LIQUIDACION_COMPONENTE_VACIO";
    public static final String ERROR_LIQUIDACION_SEDE_VACIO = "ERROR_LIQUIDACION_SEDE_VACIO";
    public static final String ERROR_LIQUIDACION_ANIO_VACIO = "ERROR_LIQUIDACION_ANIO_VACIO";
    public static final String ERROR_MOV_LIQ_MOTIVO_VACIO = "ERROR_MOV_LIQ_MOTIVO_VACIO";
    public static final String ERROR_NIT_DUPLICADOS = "ERROR_NIT_DUPLICADOS";
    public static final String ERROR_EVALUACION_LIQ_VACIO = "ERROR_EVALUACION_LIQ_VACIO";
    public static final String ERROR_MONTO_CERO = "ERROR_MONTO_CERO";
    public static final String ERROR_COMPRA_METEDO_VACIO = "ERROR_COMPRA_METEDO_VACIO";
    public static final String ERROR_LIQUIDACION_INGRESOS_GUARDAR = "ERROR_LIQUIDACION_INGRESOS_GUARDAR";

    public static final String ERROR_DESEMBOLSO_CED_CUENTA = "ERROR_DESEMBOLSO_CED_CUENTA";

    public static final String ERROR_CHEQUERA_SEDE_CUENTA_VACIA = "ERROR_CHEQUERA_SEDE_CUENTA_VACIA";
    public static final String ERROR_CHEQUERA_SERIE_VACIA = "ERROR_CHEQUERA_SERIE_VACIA";
    public static final String ERROR_CHEQUERA_INICIAL_VACIO = "ERROR_CHEQUERA_INICIAL_VACIO";
    public static final String ERROR_CHEQUERA_FINAL_VACIO = "ERROR_CHEQUERA_FINAL_VACIO";
    public static final String ERROR_CHEQUERA_FECHA_VACIA = "ERROR_CHEQUERA_FECHA_VACIA";
    public static final String ERROR_CHEQUERA_INICIAL_FINAL_INVALIDO = "ERROR_CHEQUERA_INICIAL_FINAL_INVALIDO";
    public static final String ERROR_CHEQUERA_DUPLICADA = "ERROR_CHEQUERA_DUPLICADA";
    public static final String ERROR_PLAN_COMPRA_OBSERVACION_VACIA = "ERROR_PLAN_COMPRA_OBSERVACION_VACIA";
    public static final String ERROR_PRESUPUESTO_OBSERVACION_VACIA = "ERROR_PRESUPUESTO_OBSERVACION_VACIA";

    public static final String ERROR_EVALUACION_LIQUIDACION_VACIA = "ERROR_EVALUACION_LIQUIDACION_VACIA";
    public static final String ERROR_EVALUACION_ITEM_VACIA = "ERROR_EVALUACION_ITEM_VACIA";
    public static final String ERROR_MONTO_NEGATIVO = "ERROR_MONTO_NEGATIVO";
    public static final String ERROR_CHEQUERA_RANGO_INVALIDO = "ERROR_CHEQUERA_RANGO_INVALIDO";
    public static final String ERROR_CHEQUERA_VALORES_FIJOS = "ERROR_CHEQUERA_VALORES_FIJOS";

    public static final String ERROR_NUM_CUENTA_DUPLICADO = "ERROR_NUM_CUENTA_DUPLICADO";
    public static final String ERROR_CHEQUE_NO_EXITE = "ERROR_CHEQUE_NO_EXITE";

}
