/*
 *  SIGES
 *  Desarrollado por Sofis Solutions
 */
package sv.gob.mined.siges.web.constantes;

public class Constantes {

    public static final String AYUDA_CACHE = "AYUDA_CACHE";
    public static final String SEDES_LAZY_CACHE = "SEDES_LAZY_CACHE";
    public static final String ORG_LAZY_CACHE = "ORG_LAZY_CACHE";

    public static final String SECTOR_ECONOMICO_CACHE = "SECTOR_ECONOMICO_CACHE";
    public static final String MODALIDAD_ATENCION_CACHE = "MODALIDAD_ATENCION_CACHE";
    public static final String ESCALA_CALIFICACION_CACHE = "ESCALA_CALIFICACION_CACHE";
    public static final String SUBMODALIDAD_ATENCION_CACHE = "SUBMODALIDAD_ATENCION_CACHE";
    public static final String PROGRAMA_EDUCATIVO_CACHE = "PROGRAMA_EDUCATIVO_CACHE";
    public static final String CLASIFICACION_CACHE = "CLASIFICACION_CACHE";
    public static final String MOTIVO_INASISTENCIA_CACHE = "MOTIVO_INASISTENCIA_CACHE";
    public static final String SEXO_CACHE = "SEXO_CACHE";
    public static final String ETNIA_CACHE = "ETNIA_CACHE";
    public static final String MEDIO_TRANSPORTE_CACHE = "MEDIO_TRANSPORTE_CACHE";
    public static final String ESTADO_CIVIL_CACHE = "ESTADO_CIVIL_CACHE";
    public static final String TIPO_TELEFONO_CACHE = "TIPO_TELEFONO_CACHE";
    public static final String TIPO_IDENTIFICACION_CACHE = "TIPO_IDENTIFICACION_CACHE";
    public static final String PAIS_CACHE = "PAIS_CACHE";
    public static final String DEPARTAMENTO_CACHE = "DEPARTAMENTO_CACHE";
    public static final String MUNICIPIO_CACHE = "MUNICIPIO_CACHE";
    public static final String CANTON_CACHE = "CANTON_CACHE";
    public static final String CASERIO_CACHE = "CASERIO_CACHE";
    public static final String ZONA_CACHE = "ZONA_CACHE";
    public static final String TIPO_MANIFESTACION_CACHE = "TIPO_MANIFESTACION_CACHE";
    public static final String JORNADA_LABORAL_CACHE = "JORNADA_LABORAL_CACHE";
    public static final String AREA_INDICADOR_CACHE = "AREA_INDICADOR_CACHE";
    public static final String AREA_ASIGNATURA_MODULO_CACHE = "AREA_ASIGNATURA_MODULO_CACHE";
    public static final String CALIFICACION_CACHE = "CALIFICACION_CACHE";
    public static final String NIVEL_EMPLEADO_CACHE = "NIVEL_EMPLEADO_CACHE";
    public static final String CATEGORIA_EMPLEADO_CACHE = "CATEGORIA_EMPLEADO_CACHE";
    public static final String CARGO_CACHE = "CARGO_CACHE";
    public static final String TIPO_CONTRATO_CACHE = "TIPO_CONTRATO_CACHE";
    public static final String LEY_SALARIO_CACHE = "LEY_SALARIO_CACHE";
    public static final String FUENTE_FINANCIAMIENTO_CACHE = "FUENTE_FINANCIAMIENTO_CACHE";
    public static final String INSTITUCION_PAGA_SALARIO_CACHE = "INSTITUCION_PAGA_SALARIO_CACHE";
    public static final String TIPO_INSTITUCION_PAGA_CACHE = "TIPO_INSTITUCION_PAGA_CACHE";
    public static final String TIPO_NOMBRAMIENTO_CACHE = "TIPO_NOMBRAMIENTO_CACHE";
    public static final String MODO_PAGO_CACHE = "MODO_PAGO_CACHE";
    public static final String SISTEMA_GESTION_CONTENIDO_CACHE = "SISTEMA_GESTION_CONTENIDO_CACHE";
    public static final String IDIOMA_CACHE = "IDIOMA_CACHE";
    public static final String NIVEL_IDIOMA_CACHE = "NIVEL_IDIOMA_CACHE";
    public static final String ESCOLARIDAD_CACHE = "ESCOLARIDAD_CACHE";
    public static final String TIPO_ESTUDIO_CACHE = "TIPO_ESTUDIO_CACHE";
    public static final String CARRERA_CACHE = "CARRERA_CACHE";
    public static final String ESPECIALIDAD_CACHE = "ESPECIALIDAD_CACHE";
    public static final String MODALIDAD_ESTUDIO_CACHE = "MODALIDAD_ESTUDIO_CACHE";
    public static final String TIPO_CAPACITACION_CACHE = "TIPO_CAPACITACION_CACHE";
    public static final String ALCANCE_CAPACITACION_CACHE = "ALCANCE_CAPACITACION_CACHE";
    public static final String PROFESION_CACHE = "PROFESION_CACHE";
    public static final String TIPO_TRABAJO_CACHE = "TIPO_TRABAJO_CACHE";
    public static final String DEPENDENCIA_ECONOMICA_CACHE = "DEPENDENCIA_ECONOMICA_CACHE";
    public static final String TIPO_SANGRE_CACHE = "TIPO_SANGRE_CACHE";
    public static final String DISCAPACIDAD_CACHE = "DISCAPACIDAD_CACHE";
    public static final String TRASTORNO_APRENDIZAJE_CACHE = "TRASTORNO_APRENDIZAJE_CACHE";
    public static final String OCUPACION_CACHE = "OCUPACION_CACHE";
    public static final String MOTIVO_RETIRO_CACHE = "MOTIVO_RETIRO_CACHE";
    public static final String TIPO_PARENTESCO_CACHE = "TIPO_PARENTESCO_CACHE";
    public static final String NIVEL_FORMACION_DOCENTE_CACHE = "NIVEL_FORMACION_DOCENTE_CACHE";
    public static final String CONFIGURACION_CACHE = "CONFIGURACION_CACHE";
    public static final String CONFIGURACION_CACHE_CODIGO = "CONFIGURACION_CACHE_CODIGO";
    public static final String CONFIGURACION_FIRMA_ELECTRONICA_CACHE_CODIGO = "CONFIGURACION_FIRMA_ELECTRONICA_CACHE_CODIGO";
    public static final String CATEGORIA_FORMACION_DOCENTE_CACHE = "CATEGORIA_FORMACION_DOCENTE_CACHE";
    public static final String MODULO_FORMACION_DOCENTE_CACHE = "MODULO_FORMACION_DOCENTE_CACHE";
    public static final String NACIONALIDAD_CACHE = "NACIONALIDAD_CACHE";
    public static final String TIPO_CALLE_CACHE = "TIPO_CALLE_CACHE";
    public static final String SERVICIO_INFRAESTRUCTURA_CACHE = "SERVICIO_INFRAESTRUCTURA_CACHE";
    public static final String TIPO_ORGANISMO_ADMINISTRATIVO_CACHE = "TIPO_ORGANISMO_ADMINISTRATIVO_CACHE";
    public static final String AFP_CACHE = "AFP_CACHE";
    public static final String MOTIVO_TRASLADO_CACHE = "MOTIVO_TRASLADO_CACHE";
    public static final String TIPO_SERVICIO_SANITARIO_CACHE = "TIPO_SERVICIO_SANITARIO_CACHE";
    public static final String TIPO_REPRESENTANTE_CACHE = "TIPO_REPRESENTANTE_CACHE";
    public static final String CARGO_TITULAR_CACHE = "CARGO_TITULAR_CACHE";
    public static final String MOTIVO_INASISTENCIA_PERSONAL_CACHE = "MOTIVO_INASISTENCIA_PERSONAL_CACHE";
    public static final String TIPO_ACCION_CACHE = "TIPO_ACCION_CACHE";
    public static final String TIPO_APOYO_CACHE = "TIPO_APOYO_CACHE";
    public static final String TIPO_PROVEEDOR_CACHE = "TIPO_PROVEEDOR_CACHE";
    public static final String GRADO_RIESGO_CACHE = "GRADO_RIESGO_CACHE";
    public static final String ACCION_CACHE = "ACCION_CACHE";
    public static final String PROYECTO_INSTITUCIONAL_CACHE = "PROYECTO_INSTITUCIONAL_CACHE";
    public static final String VELOCIDAD_INTERNET_CACHE = "VELOCIDAD_INTERNET_CACHE";
    public static final String ORGANISMO_COORDINACION_ESCOLAR_CACHE = "ORGANISMO_COORDINACION_ESCOLAR_CACHE";
    public static final String RECURSOS_CACHE = "RECURSOS_CACHE";
    public static final String CATEGORIAS_CURSO_CACHE = "CATEGORIAS_CURSO";
    public static final String TIPOS_MODULO_CACHE = "TIPOS_MODULO";
    public static final String CARGO_OAE_CACHE = "CARGO_OAE_CACHE";
    public static final String GLOSARIOS_CACHE = "GLOSARIOS_CACHE";
    public static final String GRADO_AFECTACION_CACHE = "GRADO_AFECTACION_CACHE";
    public static final String TIPO_RIESGO_CACHE = "TIPO_RIESGO_CACHE";
    public static final String DEFINICION_TITULO_CACHE = "DEFINICION_TITULO_CACHE";
    public static final String PREGUNTAS_CIERRE_ANIO_CACHE = "PREGUNTAS_CIERRE_ANIO_CACHE";
    public static final String PLANTILLAS_CACHE = "PLANTILLAS_CACHE";
    public static final String FORMULAS_CACHE = "FORMULAS_CACHE";
    public static final String MOTIVO_FALLECIMIENTO_CACHE = "MOTIVO_FALLECIMIENTO_CACHE";
    public static final String CARGA_MAXIMO_NIVEL_EDUCATIVO_ALCANZADO = "CARGA_MAXIMO_NIVEL_EDUCATIVO_ALCANZADO";
    public static final String ESTADO_PROCESO_LEGALIZACION_CACHE = "ESTADO_PROCESO_LEGALIZACION_CACHE";
    public static final String MINISTERIO_OTORGANTE_CACHE = "MINISTERIO_OTORGANTE_CACHE";
    public static final String NATURALEZA_CONTRATO_CACHE = "NATURALEZA_CONTRATO_CACHE";
    public static final String TIPO_ACUERDO = "TIPO_ACUERDO";
    public static final String CATEGORIA_VIOLENCIA_CACHE = "CATEGORIA_VIOLENCIA_CACHE";
    public static final String IMPLEMENTADORA = "IMPLEMENTADORA";
    public static final String MOTIVO_ANULACION_TITULO = "MOTIVO_ANULACION_TITULO";
    public static final String TIPO_ALFABETIZADOR = "TIPO_ALFABETIZADOR";
    public static final String MOTIVO_REIMPRESION = "MOTIVO_REIMPRESION";
    public static final String ASOCIACIONES_CACHE = "ASOCIACIONES_CACHE";
    public static final String TITULO_ANTERIOR_CACHE = "TITULO_ANTERIOR_CACHE";
    public static final String IMPLEMENTADORA_CACHE = "IMPLEMENTADORA_CACHE";
    public static final String TIPO_ACUERDO_CACHE = "TIPO_ACUERDO";
    public static final String ESTADO_DATO_CONTRATACION_CACHE = "ESTADO_DATO_CONTRATACION_CACHE";
    public static final String PERFIL_CACHE = "PERFIL_CACHE";
    public static final String REFERENCIAS_CACHE = "REFERENCIAS_CACHE";
    public static final String TERAPIAS_CACHE = "TERAPIAS_CACHE";
    public static final String MOTIVOS_SELECCION_CACHE = "MOTIVOS_SELECCION_CACHE";
    public static final String CALIDAD_INGRESO_APLICANTE_CACHE = "CALIDAD_INGRESO_APLICANTE_CACHE";
    public static final String IDENTIFICACION_OAE_CACHE = "IDENTIFICACION_OAE_CACHE";
    public static final String ENFERMEDAD_NO_TRANSMITIBLE_CACHE = "ENFERMEDAD_NO_TRANSMITIBLE_CACHE";
    public static final String TIEMPO_COMIDA_DIA_CACHE = "TIEMPO_COMIDA_DIA_CACHE";

    public static final String COMPANIAS_TELECOMUNICACION_CACHE = "COMPANIAS_TELECOMUNICACION_CACHE";
    public static final String ELEMENTOS_HOGAR_CACHE = "ELEMENTOS_HOGAR_CACHE";
    public static final String FUENTES_ABASTECIMIENTO_AGUA = "FUENTES_ABASTECIMIENTO_AGUA";
    public static final String MATERIALES_PISO_CACHE = "MATERIALES_PISO_CACHE";
    public static final String MOTIVO_CIERRE_SEDE_CACHE = "MOTIVO_CIERRE_SEDE_CACHE";
    
    //Centros cache
    public static final String ORG_CURRICULAR_CACHE = "ORG_CURRICULAR_CACHE";
    public static final String NIVEL_CACHE = "NIVEL_CACHE";
    public static final String CICLO_CACHE = "CICLO_CACHE";
    public static final String MODALIDAD_CACHE = "MODALIDAD_CACHE";
    public static final String OPCION_CACHE = "OPCION_CACHE";
    public static final String REL_MOD_ED_MOD_ATEN_CACHE = "REL_MOD_ED_MOD_ATEN_CACHE";
    public static final String REL_OPCION_PROG_CACHE = "REL_OPCION_PROG_CACHE";
    public static final String GRADO_CACHE = "GRADO_CACHE";
    public static final String ANIO_LECTIVO_CACHE = "ANIO_LECTIVO_CACHE";
    public static final String RANGO_FECHA_CACHE = "RANGO_FECHA_CACHE";
    public static final String REL_GRADO_PLAN_ESTUDIO_CACHE = "REL_GRADO_PLAN_ESTUDIO_CACHE";
    public static final String COMPONENTE_PLAN_GRADO_CACHE = "COMPONENTE_PLAN_GRADO_CACHE";
    public static final String CALENDARIO_CACHE = "CALENDARIO_CACHE";
    public static final String COMPONENTE_PLAN_ESTUDIO_NUMERICO_CURSADO_ESTUDIANTE_CACHE = "COMPONENTE_PLAN_ESTUDIO_NUMERICO_CURSADO_ESTUDIANTE_CACHE";
    public static final String COMPONENTE_PLAN_ESTUDIO_NUMERICO_ACTUALES_ORD_ESTUDIANTE_CACHE = "COMPONENTE_PLAN_ESTUDIO_NUMERICO_ACTUALES_ORD_ESTUDIANTE_CACHE";
    public static final String COMPONENTE_PLAN_ESTUDIO_CONCEPTUAL_CURSADO_ESTUDIANTE_CACHE = "COMPONENTE_PLAN_ESTUDIO_CONCEPTUAL_CURSADO_ESTUDIANTE_CACHE";
    public static final String PROBABILIDAD_DESERCION_ESTUDIANTE_CACHE = "PROBABILIDAD_DESERCION_ESTUDIANTE_CACHE";

    //Graficos
    public static final String GRAFICO_ALERTAS_ESTUDIANTE = "GRAFICO_ALERTAS_ESTUDIANTE";
    public static final String GRAFICO_ASISTENCIAS_ESTUDIANTE_POR_ANIO = "GRAFICO_ASISTENCIAS_ESTUDIANTE_POR_ANIO";
    public static final String GRAFICO_CALIFICACIONES_APR_NUMERICAS_ESTUDIANTE_POR_GRADO_CONTRA_PROMEDIO_NACIONAL = "GRAFICO_CALIFICACIONES_APR_NUMERICAS_ESTUDIANTE_POR_GRADO_CONTRA_PROMEDIO_NACIONAL";
    public static final String GRAFICO_CALIFICACIONES_APR_NUMERICAS_ESTUDIANTE_POR_GRADO_Y_COMPONENTE = "GRAFICO_CALIFICACIONES_APR_NUMERICAS_ESTUDIANTE_POR_GRADO_Y_COMPONENTE";
    public static final String GRAFICO_CALIFICACIONES_ORD_ACTUALES_NUMERICAS_ESTUDIANTE_POR_GRADO_Y_COMPONENTE = "GRAFICO_CALIFICACIONES_ORD_ACTUALES_NUMERICAS_ESTUDIANTE_POR_GRADO_Y_COMPONENTE";
    public static final String GRAFICO_CALIFICACIONES_APR_CONCEPTUALES_ESTUDIANTE_POR_GRADO_Y_COMPONENTE = "GRAFICO_CALIFICACIONES_APR_CONCEPTUALES_ESTUDIANTE_POR_GRADO_Y_COMPONENTE";
    public static final String GRAFICO_ASISTENCIAS_ESTUDIANTE_POR_MES_EN_ANIO = "GRAFICO_ASISTENCIAS_ESTUDIANTE_POR_MES_EN_ANIO";
    public static final String GRAFICO_MOT_INASISTENCIAS_ESTUDIANTE_POR_ANIO = "GRAFICO_MOT_INASISTENCIAS_ESTUDIANTE_POR_ANIO";
    public static final String GRAFICO_MOT_INASISTENCIAS_ESTUDIANTE_POR_MES_EN_ANIO = "GRAFICO_MOT_INASISTENCIAS_ESTUDIANTE_POR_MES_EN_ANIO";
    public static final String GRAFICO_EVOLUCION_ENCUESTAS_MATRICULAS = "GRAFICO_EVOLUCION_ENCUESTAS_MATRICULAS";
    public static final String GRAFICO_EVOLUCION_ENCUESTAS_SEXO = "GRAFICO_EVOLUCION_ENCUESTAS_SEXO";

    public static final String TIPO_DOCUMENTO_DOCENTE = "TIPO_DOCUMENTO_DOCENTE";
    public static final String CODIGO_PAIS_EL_SALVADOR = "SV";
    public static final String CODIGO_SEXO_MASCULINO = "1";
    public static final String CODIGO_SEXO_FEMENINO = "2";
    public static final Long PK_SEXO_MASCULINO = 1L;
    public static final Long PK_SEXO_FEMENINO = 2L;
    public static final Long PK_FUENTE_ABASTECIMIENTO_AGUA_OTRA = 7L;
    public static final Long PK_SERVICIO_SANITARIO_OTRO = 4L;
    public static final Long PK_MATERIAL_PISO_OTRO = 6L;
    public static final String VALIDAR_OTRO_CODIGO = "OTRO";
    public static final String CODIGO_NACIONALIDAD_EL_SALVADOR = "1";
    public static final String CODIGO_IDENTIFICACION_PASAPORTE = "1";
    public static final Integer EDAD_PERSONA_MAYOR = 18;
    public static final String CODIGO_IMPORTAR_CALIFICACIONES_ASINC = "IMPORTAR_CALIFICACIONES_ASINC";
    public static final String CARGA_ARCHIVOS = "CARGA_ARCHIVOS";
    public static final String TAMANIO_ARCHIVO_IMPORT = "TAMANIO_ARCHIVO_IMPORT";
    public static final String TAMANIO_ARCHIVO_IMPORT_PAES = "TAMANIO_ARCHIVO_IMPORT_PAES";
    public static final String TIPO_ARCHIVO_IMPORT = "TIPO_ARCHIVO_IMPORT";
    public static final String CANT_FILAS_ARCHIVO_IMPORT = "CANT_FILAS_ARCHIVO_IMPORT";
    public static final String CONFIG_DIA_MES_INGRESO_MATRICULA_NACIONAL = "DIA_MES_INGRESO_MATRICULA_NACIONAL";
    public static final String CONFIG_DIA_MES_INGRESO_MATRICULA_INTERNACIONAL = "DIA_MES_INGRESO_MATRICULA_INTERNACIONAL";
    public static final String CONFIG_MENSAJE_CIERRE_ANIO = "MENSAJE_CIERRE_ANIO";
    public static final String CONFIG_MENSAJE_EVOLUCION_ESTUDIANTE = "MENSAJE_EVOLUCION_ESTUDIANTE";
    public static final String CONFIG_MENSAJE_EVOLUCION_ESTUDIANTE_ALERTAS_TEMPRANAS = "MENSAJE_EVOLUCION_ESTUDIANTE_ALERTAS";
    public static final String CONFIG_MENSAJE_EVOLUCION_ESTUDIANTE_PREDICTIBILIDAD_DESERCION = "MENSAJE_EVOLUCION_ESTUDIANTE_DESERCION";
    public static final String CONFIG_MENSAJE_ENCUESTA_ESTUDIANTE = "MENSAJE_ENCUESTA_ESTUDIANTE";
    public static final String CONFIG_RANGO_COLORES_GAUGE_PREDICTIBILIDAD_DESERCION = "RANGO_COLORES_GAUGE_PREDICTIBILIDAD_DESERCION";
    public static final String CONFIG_BUSQUEDA_PERSONAS_LUCENE_HABILITADA = "BUSQUEDA_PERSONAS_LUCENE_HABILITADA";
    public static final String CONFIG_BUSQUEDA_PERSONAS_SIMILARES_LUCENE_HABILITADA = "BUSQUEDA_PERSONAS_SIMILARES_LUCENE_HABILITADA";
    public static final String CONFIG_DIAS_ANTICIPO_ALERTA_VENCIMIENTO_OAE = "DIAS_ANTICIPO_ALERTA_VENCIMIENTO_OAE";
    public static final String CONFIG_DIAS_VISUALIZACION_CAMBIO_ESTADO_ALERTAS_OAE = "DIAS_VISUALIZACION_CAMBIO_ESTADO_ALERTAS_OAE";

    public static final String PLANTILLA_EXCEL_IMPORTACION_MATRICULAS = "EXCEL_IMPORTACION_MATRICULAS";
    public static final String TAMANIO_ARCHIVO_REPOSICION_TITULO = "TAMANIO_ARCHIVO_REPOSICION_TITULO";
    public static final String TIPO_ARCHIVO_REPOSICION_TITULO = "TIPO_ARCHIVO_REPOSICION_TITULO";

    public static final String CALENDARIO_NACIONAL = "01";
    public static final String CALENDARIO_INTERNACIONAL = "02";

    public static final Integer CERO = 0;
    public static final Integer UNO = 1;

    public static final String ARCHIVO_SELLO_FIRMA = "01";

    public static final String CODIGO_ROL_PADRE = "PADRE";
    public static final String CODIGO_PASAPORTE = "1";
    public static final String CODIGO_CARNE_RESIDENTE = "5";
    public static final String CODIGO_NIVEL_EDUCACION_MEDIA = "04";
    public static final String CODIGO_IMPORTAR_BIT_MATRICULA_ASINC = "IMPORTAR_BIT_MATRICULA_ASINC";

    public static final String ALTO_ARCHIVO_SELLO_FIRMA_IMPORT = "ALTO_ARCHIVO_SELLO_FIRMA_IMPORT";
    public static final String ANCHO_ARCHIVO_SELLO_FIRMA_IMPORT = "ANCHO_ARCHIVO_SELLO_FIRMA_IMPORT";
    public static final String TIPO_ARCHIVO_SELLO_FIRMA_IMPORT = "TIPO_ARCHIVO_SELLO_FIRMA_IMPORT";
    public static final String CERRAR_ANIO_PROMOCION_CON_PENDIENTES = "CERRAR_ANIO_PROMOCION_CON_PENDIENTES";
    public static final String MENSAJE_CIERRE_SECCION = "MENSAJE_CIERRE_SECCION";
    public static final String MENSAJE_PROMOCION = "MENSAJE_PROMOCION";
    public static final String HABILITAR_CONTROL_DIA_LECTIVO = "HABILITAR_CONTROL_DIA_LECTIVO";
    public static final String MENSAJE_SOLICITUD_IMPRESION = "MENSAJE_SOLICITUD_IMPRESION";

    public static final String CONFIG_FIRMA_ELECTRONICA_CONFIRMACION_PROMOCION = "CONF_PROMOCION";
    public static final String CONFIG_FIRMA_ELECTRONICA_CONFIRMACION_APROBACION = "CONF_APROBACION";
    public static final String CARGO_MINISTRO = "C026";
    public static final String CARGO_AUTENTICA = "AUT";
    public static final String TIPO_REPRESENTANTE_DIRECTOR = "DIR";
    public static final String PROCESAR_PROMOCIONES_ASINC = "PROCESAR_PROMOCIONES_ASINC";
    public static final String TITULO_FECHA_VALIDEZ_DESDE = "TITULO_FECHA_VALIDEZ_DESDE";
    public static final String SOLICITUD_CAMBIO_CALIFICACION_MAT = "SOLICITUD_CAMBIO_CALIFICACION_MAT";
    public static final String SOLICITUD_CAMBIO_CALIFICACION_CAL = "SOLICITUD_CAMBIO_CALIFICACION_CAL";
    public static final String SOLICITUD_HABILITACION_PERIODO_MAT = "SOLICITUD_HABILITACION_PERIODO_MAT";
    public static final String CONFIG_DIA_MES_CIERRE_MATRICULA_NACIONAL = "DIA_MES_CIERRE_MATRICULA_NACIONAL";
    public static final String CONFIG_DIA_MES_CIERRE_MATRICULA_INTERNACIONAL = "DIA_MES_CIERRE_MATRICULA_INTERNACIONAL";

    public static final String CONFIG_DIA_MES_CIERRE_MATRICULA_NACIONAL_PRIMER_COHORTE = "DIA_MES_CIERRE_MATRICULA_NACIONAL_COHORTE";
    public static final String CONFIG_DIA_MES_CIERRE_MATRICULA_INTERNACIONAL_PRIMER_COHORTE = "DIA_MES_CIERRE_MATRICULA_INT_COHORTE";

    public static final String CONFIG_CONSUMO_SERVICIO_DUI_RNPN_HABILITADO = "CONSUMO_SERVICIO_DUI_RNPN_HABILITADO";
    public static final String CONFIG_CONSUMO_SERVICIO_CUN_RNPN_HABILITADO = "CONSUMO_SERVICIO_CUN_RNPN_HABILITADO";
    public static final String CONFIG_CONSUMO_SERVICIO_PARTIDA_NAC_RNPN_HABILITADO = "CONSUMO_SERVICIO_PARTIDA_NAC_RNPN_HABILITADO";

    public static final String IMPORTACION_CALIFICACION_MSJ = "IMPORTACION_CALIFICACION_MSJ";
    public static final String PLANTILLA_IMPORTACION_CALIFICACIONES = "PLANTILLA_IMPORTACION_CALIFICACIONES";
    public static final String PLANTILLA_IMPORTACION_ASISTENCIAS = "PLANTILLA_IMPORTACION_ASISTENCIAS";
    public static final String MENSAJE_MATRIZ_COMPARATIVA = "MENSAJE_MATRIZ_COMPARATIVA";
    public static final String IMPORTACION_CALIFICACION_VARIOS_COMPONENTES = "IMPORTACION_CALIFICACION_VARIOS_COMPONENTES";
    public static final String IMPORTACION_CALIFICACIONES_UNICO_COMP = "IMPORTACION_CALIFICACIONES_UNICO_COMP";
    public static final String IMPORTACION_CALIFICACIONES_MAS_DE_UN_COMP = "IMPORTACION_CALIFICACIONES_MAS_DE_UN_COMP";
    public static final String CODIGO_SISTEMA_CONTENIDO_NINGUNO = "LMS0";
    public static final String FICHA_SALUD_MSJ_CONF = "FICHA_SALUD_MSJ_CONF";
    public static final String PLANTILLA_IMPORTACION_CALIFICACIONES_HISTORICO = "PLANTILLA_IMPORT_CALIFICACIONES_HISTORICO";
}
