/*
 *  SIGES
 *  Desarrollado por Sofis Solutions
 */
package sv.gob.mined.siges.negocio.mensajes;


public class Errores {

    public static final String ERROR_GENERAL = "ERROR_GENERAL";
    public static final String ERROR_OPTIMISTIC_LOCK = "ERROR_OPTIMISTIC_LOCK";
    
    public static final String ERROR_DATO_VACIO = "ERROR_DATO_VACIO";
    public static final String ERROR_CODIGO_VACIO = "ERROR_CODIGO_VACIO";
    public static final String ERROR_NOMBRE_VACIO = "ERROR_NOMBRE_VACIO";
    public static final String ERROR_DESCRIPCION_VACIO = "ERROR_DESCRIPCION_VACIO";
    public static final String ERROR_VALOR_VACIO = "ERROR_VALOR_VACIO";
    
    public static final String ERROR_LARGO_VALOR_25 = "ERROR_LARGO_VALOR_25";
    public static final String ERROR_LARGO_DESCRIPCION_255 = "ERROR_LARGO_DESCRIPCION_255";
    public static final String ERROR_LARGO_DESCRIPCION_500 = "ERROR_LARGO_DESCRIPCION_500";
    public static final String ERROR_LARGO_NOMBRE_255 = "ERROR_LARGO_NOMBRE_255";
    public static final String ERROR_LARGO_NOMBRE_20 = "ERROR_LARGO_NOMBRE_20";
    public static final String ERROR_LARGO_VALOR_255 = "ERROR_LARGO_VALOR_255";
    public static final String ERROR_LARGO_VALOR_500 = "ERROR_LARGO_VALOR_500";
    public static final String ERROR_LARGO_CODIGO_45 = "ERROR_LARGO_CODIGO_45";
    public static final String ERROR_LARGO_CODIGO_4 = "ERROR_LARGO_CODIGO_4";
    public static final String ERROR_LARGO_CODIGO_5 = "ERROR_LARGO_CODIGO_5";
    public static final String ERROR_LARGO_CODIGO_6 = "ERROR_LARGO_CODIGO_6";
    public static final String ERROR_LARGO_CODIGO_8 = "ERROR_LARGO_CODIGO_8";
    public static final String ERROR_LARGO_CODIGO_10 = "ERROR_LARGO_CODIGO_10";
    public static final String ERROR_LARGO_CODIGO_20 = "ERROR_LARGO_CODIGO_20";
    public static final String ERROR_LARGO_CODIGO_50 = "ERROR_LARGO_CODIGO_50";
    
    public static final String ERROR_CODIGO_O_NOMBRE_DUPLICADOS = "ERROR_CODIGO_O_NOMBRE_DUPLICADOS";
    public static final String ERROR_CODIGO_DUPLICADO = "ERROR_CODIGO_DUPLICADO";
    public static final String ERROR_NOMBRE_DUPLICADO = "ERROR_NOMBRE_DUPLICADO";
    
    public static final String ERROR_ENTIDAD_REFERENCIADA = "ERROR_ENTIDAD_REFERENCIADA";
    
    public static final String ERROR_SEGURIDAD = "ERROR_SEGURIDAD";
    public static final String ERROR_CONSTRAINT_EXCEPTION = "ERROR_CONSTRAINT_EXCEPTION";
    public static final String ERROR_CODIGO_INVENTARIO_DUPLICADO = "ERROR_CODIGO_INVENTARIO_DUPLICADO";
    public static final String ERROR_NUMERO_SERIE_DUPLICADO = "ERROR_NUMERO_SERIE_DUPLICADO";
    public static final String ERROR_NUMERO_PLACA_DUPLICADO = "ERROR_NUMERO_PLACA_DUPLICADO";
    public static final String ERROR_NUMERO_MOTOR_DUPLICADO = "ERROR_NUMERO_MOTOR_DUPLICADO";
    public static final String ERROR_NUMERO_CHASIS_DUPLICADO = "ERROR_NUMERO_CHASIS_DUPLICADO";

    public static final String ERROR_CODIGO_DESCARGO_DUPLICADO = "ERROR_CODIGO_DESCARGO_DUPLICADO";
    public static final String ERROR_CODIGO_TRASLADO_DUPLICADO = "ERROR_CODIGO_TRASLADO_DUPLICADO";
    
    public static final String ERROR_DEPARTAMENTO_VACIO = "ERROR_DEPARTAMENTO_VACIO";
    public static final String ERROR_MUNICIPIO_VACIO = "ERROR_MUNICIPIO_VACIO";
    
    public static final String ERROR_TIPO_UNIDAD_VACIO = "ERROR_TIPO_UNIDAD_VACIO";
    public static final String ERROR_CATEGORIA_VACIO = "ERROR_CATEGORIA_VACIO";
    public static final String ERROR_NUM_PLACA_VACIO = "ERROR_NUM_PLACA_VACIO";
    public static final String ERROR_NUM_SERIE_VACIO = "ERROR_NUM_SERIE_VACIO";
    public static final String ERROR_NUM_CHASIS_VACIO = "ERROR_NUM_CHASIS_VACIO";
    public static final String ERROR_NUM_MOTOR_VACIO = "ERROR_NUM_MOTOR_VACIO";
    
    public static final String ERROR_UNIDAD_ACTIVO_FIJO_VACIO = "ERROR_UNIDAD_ACTIVO_FIJO_VACIO";
    public static final String ERROR_UNIDAD_ADMINISTRATIVA_VACIO = "ERROR_UNIDAD_ADMINISTRATIVA_VACIO";
    public static final String ERROR_TIPO_BIEN_VACIO = "ERROR_TIPO_BIEN_VACIO";
    public static final String ERROR_CODIGO_CORRELATIVO_VACIO = "ERROR_CODIGO_CORRELATIVO_VACIO";
    public static final String ERROR_CODIGO_INVENTARIO_VACIO = "ERROR_CODIGO_INVENTARIO_VACIO";
    public static final String ERROR_ESTADO_CALIDAD_VACIO = "ERROR_ESTADO_CALIDAD_VACIO";
    public static final String ERROR_ASIGNADOA_VACIO = "ERROR_ASIGNADOA_VACIO";
    public static final String ERROR_FORMA_ADQUISICION_VACIO = "ERROR_FORMA_ADQUISICION_VACIO";
    public static final String ERROR_FUENTE_FINANCIAMIENTO_VACIO = "ERROR_FUENTE_FINANCIAMIENTO_VACIO";
    public static final String ERROR_PROYECTO_VACIO = "ERROR_PROYECTO_VACIO";
    public static final String ERROR_FECHA_ADQUISICION_VACIO = "ERROR_FECHA_ADQUISICION_VACIO";
    public static final String ERROR_VALOR_ADQUISICION_VACIO = "ERROR_VALOR_ADQUISICION_VACIO";
    public static final String ERROR_ES_VALOR_ESTIMADO_VACIO = "ERROR_ES_VALOR_ESTIMADO_VACIO";
    public static final String ERROR_BIEN_VACIO = "ERROR_BIEN_VACIO";
    public static final String ERROR_CODIGO_TIPO_BIEN_VACIO = "ERROR_CODIGO_TIPO_BIEN_VACIO";
    public static final String ERROR_CODIGO_UNIDAD_ADMINISTRATIVA_VACIO = "ERROR_CODIGO_UNIDAD_ADMINISTRATIVA_VACIO";
    public static final String ERROR_CANTIDAD_LOTE_CERO = "ERROR_CANTIDAD_LOTE_CERO";
    public static final String ERROR_ESTADO_BIEN_VACIO = "ERROR_ESTADO_BIEN_VACIO";
    public static final String ERROR_ESTADO_TIPO_DESCARGO = "ERROR_ESTADO_TIPO_DESCARGO";
    public static final String ERROR_TIPO_ACTIVO = "ERROR_TIPO_ACTIVO";
    public static final String ERROR_ESTADO_BIEN_CODIGO_VACIO = "ERROR_ESTADO_BIEN_CODIGO_VACIO";
    public static final String ERROR_FECHA_DESCARGO_VACIO = "ERROR_FECHA_DESCARGO_VACIO";
    public static final String ERROR_CODIGO_DESCARGO_VACIO = "ERROR_CODIGO_DESCARGO_VACIO";
    
    public static final String ERROR_UNIDAD_ADMINISTRATIVA_ORIGEN_VACIO = "ERROR_UNIDAD_ADMINISTRATIVA_ORIGEN_VACIO";
    public static final String ERROR_UNIDAD_ADMINISTRATIVA_DESTINO_VACIO = "ERROR_UNIDAD_ADMINISTRATIVA_DESTINO_VACIO";
    public static final String ERROR_CODIGO_TRASLADO_VACIO = "ERROR_CODIGO_TRASLADO_VACIO";
    public static final String ERROR_FECHA_TRASLADO_VACIO = "ERROR_FECHA_TRASLADO_VACIO";
    public static final String ERROR_OPCION_DESCARGO_PERMUTA = "ERROR_OPCION_DESCARGO_PERMUTA";
    public static final String ERROR_SOLICITUD_VACIO = "ERROR_SOLICITUD_VACIO";
    public static final String ERROR_DESCAGO_VACIO = "ERROR_DESCAGO_VACIO";
    public static final String ERROR_TRASLADO_VACIO = "ERROR_TRASLADO_VACIO";
    public static final String ERROR_ESTADO_VACIO = "ERROR_ESTADO_VACIO";
    
    public static final String ERROR_ANIO_VACIO = "ERROR_ANIO_VACIO";
    public static final String ERROR_MES_VACIO = "ERROR_MES_VACIO";
    public static final String ERROR_NUMERO_DIAS_DEPRECIADOS_VACIO = "ERROR_NUMERO_DIAS_DEPRECIADOS_VACIO";
    public static final String ERROR_MONTO_DEPRECIACION_VACIO = "ERROR_MONTO_DEPRECIACION_VACIO";
    
    public static final String ERROR_UNIDAD_DESTINO_VACIO = "ERROR_UNIDAD_DESTINO_VACIO";
    public static final String ERROR_FECHA_RETORNO_VACIO = "ERROR_FECHA_RETORNO_VACIO";
    public static final String ERROR_FECHA_RETORNO_MENOR_FECHA_TRASLADO = "ERROR_FECHA_RETORNO_MENOR_FECHA_TRASLADO";
    
    public static final String ERROR_FECHA_ADQUISICION_MAYOR_FECHA_ACTUAL = "ERROR_FECHA_ADQUISICION_MAYOR_FECHA_ACTUAL";
    public static final String ERROR_FECHA_ADQUISICION_MENOR_FECHA_LIMITE_MENOR = "ERROR_FECHA_ADQUISICION_MENOR_FECHA_LIMITE_MENOR";
    
    public static final String ERROR_FECHA_LIQUIDACION_MAYOR_FECHA_ACTUAL = "ERROR_FECHA_LIQUIDACION_MAYOR_FECHA_ACTUAL";
    public static final String ERROR_FECHA_LIQUIDACION_MENOR_FECHA_LIMITE_MENOR = "ERROR_FECHA_LIQUIDACION_MENOR_FECHA_LIMITE_MENOR";
    public static final String ERROR_FECHA_LIQUIDACION_VACIO = "ERROR_FECHA_LIQUIDACION_VACIO";
            
    public static final String ERROR_FECHA_DESCARGO_MAYOR_FECHA_ACTUAL = "ERROR_FECHA_DESCARGO_MAYOR_FECHA_ACTUAL";
    public static final String ERROR_FECHA_DESCARGO_MENOR_FECHA_LIMITE_MENOR = "ERROR_FECHA_DESCARGO_MENOR_FECHA_LIMITE_MENOR";
    public static final String ERROR_FECHA_TRASLADO_MAYOR_FECHA_ACTUAL = "ERROR_FECHA_TRASLADO_MAYOR_FECHA_ACTUAL";
    public static final String ERROR_FECHA_TRASLADO_MENOR_FECHA_LIMITE_MENOR = "ERROR_FECHA_TRASLADO_MENOR_FECHA_LIMITE_MENOR";
    public static final String ERROR_DESTINO_UNIDAD_IGUAL_ORIGEN = "ERROR_DESTINO_UNIDAD_IGUAL_ORIGEN";
    
    public static final String ERROR_NOMBRE_AUTORIZA_VACIO = "ERROR_NOMBRE_AUTORIZA_VACIO";
    public static final String ERROR_NOMBRE_RECIBE_VACIO = "ERROR_NOMBRE_RECIBE_VACIO";
    public static final String ERROR_CARGO_AUTORIZA_VACIO = "ERROR_CARGO_AUTORIZA_VACIO";
    public static final String ERROR_CARGO_RECIBE_VACIO = "ERROR_CARGO_RECIBE_VACIO";
    
    public static final String ERROR_LARGO_NOMBRE_AUTORIZA_100 = "ERROR_LARGO_NOMBRE_AUTORIZA_100";
    public static final String ERROR_LARGO_CARGO_AUTORIZA_100 = "ERROR_LARGO_CARGO_AUTORIZA_100";
    public static final String ERROR_LARGO_NOMBRE_RECIBE_100 = "ERROR_LARGO_NOMBRE_RECIBE_100";
    public static final String ERROR_LARGO_CARGO_RECIBE_100 = "ERROR_LARGO_CARGO_RECIBE_100";
    
    public static final String ERROR_VALOR_ADQUISICION_CERO_MENOR_CERO= "ERROR_VALOR_ADQUISICION_CERO_MENOR_CERO";
    public static final String ERROR_CODIGO_CORRELATIVO_CERO= "ERROR_CODIGO_CORRELATIVO_CERO";
    public static final String ERROR_ANIO_MAYOR_ACTUAL = "ERROR_ANIO_MAYOR_ACTUAL";
    public static final String ERROR_MES_MAYOR_ACTUAL = "ERROR_MES_MAYOR_ACTUAL";
    
    public static final String ERROR_FUENTE_FINANCIAMIENTO_ORIGEN_VACIO= "ERROR_FUENTE_FINANCIAMIENTO_ORIGEN_VACIO";
    public static final String ERROR_FUENTE_FINANCIAMIENTO_DESTINO_VACIO = "ERROR_FUENTE_FINANCIAMIENTO_DESTINO_VACIO";
    
    public static final String ERROR_FECHA_RETORNO_MAYOR_FECHA_TRASLADO_1_MES = "ERROR_FECHA_RETORNO_MAYOR_FECHA_TRASLADO_1_MES";
    public static final String ERROR_ELIMINAR_BIEN_CON_DEPRECIACION = "ERROR_ELIMINAR_BIEN_CON_DEPRECIACION";
    
    public static final String ERROR_ANIO_MENOR_LIMITE_MENOR_A_1960= "ERROR_ANIO_MENOR_LIMITE_MENOR_A_1960";
    
    public static final String ERROR_MOTIVO_RECHAZO_VACIO = "ERROR_MOTIVO_RECHAZO_VACIO";
    public static final String ERROR_LARGO_MOTIVO_RECHAZO_500 = "ERROR_LARGO_MOTIVO_RECHAZO_500";
    public static final String ERROR_LISTA_BIENES_DESCARGAR_VACIO = "ERROR_LISTA_BIENES_DESCARGAR_VACIO";
    public static final String ERROR_LISTA_BIENES_TRASLADAR_VACIO = "ERROR_LISTA_BIENES_TRASLADAR_VACIO";
    public static final String ERROR_BIEN_NO_PERTENECE_UNIDAD= "ERROR_BIEN_NO_PERTENECE_UNIDAD";
    public static final String ERROR_ID_INMUEBLE_VACIO = "ERROR_ID_INMUEBLE_VACIO";
    public static final String ERROR_CATEGORIA_VALOR_MAXIMO_VACIO = "ERROR_CATEGORIA_VALOR_MAXIMO_VACIO";
    public static final String ERROR_VALOR_ADQUISICION_MAYOR_CATEGORIA_VALOR_MAXIMO_VACIO = "ERROR_VALOR_ADQUISICION_MAYOR_CATEGORIA_VALOR_MAXIMO_VACIO";
    public static final String ERROR_OPCION_DESCARGO = "ERROR_OPCION_DESCARGO";
    
    public static final String ERROR_ESTADO_TIPO_TRASLADO = "ERROR_ESTADO_TIPO_TRASLADO";
    public static final String ERROR_TAREA_EXISTE_PENDIENTE_PROCESAR_O_EN_PROCESO = "ERROR_TAREA_EXISTE_PENDIENTE_PROCESAR_O_EN_PROCESO";
    public static final String ERROR_LIMITE_TAREAS_NO_FINALIZADAS = "ERROR_LIMITE_TAREAS_NO_FINALIZADAS";
    public static final String ERROR_PERSONA_VACIO ="ERROR_PERSONA_VACIO";
    public static final String ERROR_DUI_VACIO = "ERROR_DUI_VACIO";
    public static final String ERROR_DUI_INCORRECTO = "ERROR_DUI_INCORRECTO";
    public static final String ERROR_VIDA_UTIL = "ERROR_VIDA_UTIL";
    public static final String ERROR_VIDA_UTIL_CERO = "ERROR_VIDA_UTIL_CERO";
    
    
    public static final String ERROR_ACTA_DESCARGO_VACIO = "ERROR_ACTA_DESCARGO_VACIO";
    
    public static final String ERROR_ACTA_FECHA_ACUERDO_VACIO = "ERROR_ACTA_FECHA_ACUERDO_VACIO";
    public static final String ERROR_ACTA_NUMERO_ACUERDO_VACIO = "ERROR_ACTA_NUMERO_ACUERDO_VACIO";
    public static final String ERROR_ACTA_SE_AUTORIZA_VACIO = "ERROR_ACTA_SE_AUTORIZA_VACIO";
    
    
    
}
