/*
 *  SIGES
 *  Desarrollado por Sofis Solutions
 */
package sv.gob.mined.siges.web.mensajes;

import java.util.Locale;
import java.util.ResourceBundle;

public class Mensajes {

    private static final String MENSAJES = "sv.gob.mined.siges.web.mensajes.MensajesMultipleResourceBundle";
    private static ResourceBundle bundle = ResourceBundle.getBundle(MENSAJES, new Locale("es"));

    public static String obtenerMensaje(String key) {
        return bundle.getString(key);
    }

    public static final String GUARDADO_CORRECTO = "GUARDADO_CORRECTO";
    public static final String ANIO_LECTIVO_CERRADO_CORRECTO = "ANIO_LECTIVO_CERRADO_CORRECTO";
    public static final String USUARIO_CREADO_CORRECTO = "USUARIO_CREADO_CORRECTO";
    public static final String ELIMINADO_CORRECTO = "ELIMINADO_CORRECTO";
    public static final String ENVIADO_CORRECTO = "ENVIADO_CORRECTO";
    public static final String ERROR_GENERAL = "ERROR_GENERAL";
    public static final String USUARIO_INCORRECTO = "USUARIO_INCORRECTO";
    public static final String IDENTIFICACION_NO_INGRESADA = "IDENTIFICACION_NO_INGRESADA";
    public static final String PERSONA_NO_ENCONTRADA = "PERSONA_NO_ENCONTRADA";
    public static final String MULTIPLES_PERSONAS_CON_MISMA_IDENTIFICACION = "MULTIPLES_PERSONAS_CON_MISMA_IDENTIFICACION";
    public static final String NIE_GENERADO = "NIE_GENERADO";
    public static final String DATOS_INCORRECTOS = "DATOS_INCORRECTOS";
    public static final String ERROR_SECCION_VACIO = "ERROR_SECCION_VACIO";
    public static final String ERROR_SECCION_SIN_PLAN_ESTUDIO = "ERROR_SECCION_SIN_PLAN_ESTUDIO";
    public static final String ERROR_NO_SE_ENCONTRARON_ESTUDIANTES = "ERROR_NO_SE_ENCONTRARON_ESTUDIANTES";
    public static final String ERROR_SEGURIDAD = "ERROR_SEGURIDAD";
    public static final String ERROR_DUI_INCORRECTO = "ERROR_DUI_INCORRECTO";
    public static final String ERROR_ESTUDIANTE_SIN_SECCION = "ERROR_ESTUDIANTE_SIN_SECCION";
    public static final String ERROR_DATOS_ESCALAFON_VACIO = "ERROR_DATOS_ESCALAFON_VACIO";
    public static final String ERROR_FILAS_HORARIO = "ERROR_FILAS_HORARIO";
    public static final String ERROR_NIE_VACIO = "ERROR_NIE_VACIO";

    public static final String ERROR_SERVICIO_EDUCATIVO_VACIO = "ERROR_SERVICIO_EDUCATIVO_VACIO";
    public static final String ERROR_SERVICIOS_MULTIPLES = "ERROR_SERVICIOS_MULTIPLES";
    public static final String ERROR_CAMBIO_SECCION_VACIO = "ERROR_CAMBIO_SECCION_VACIO";
    public static final String ERROR_SEDE_IGUAL_TRASLADO = "ERROR_SEDE_IGUAL_TRASLADO";
    public static final String ERROR_SOLICITUD_TRASLADO_ACTIVA = "ERROR_SOLICITUD_TRASLADO_ACTIVA";
    public static final String ERROR_ACCION_VACIO = "ERROR_ACCION_VACIO";

    public static final String ERROR_PERSONA_RETIRADO = "ERROR_PERSONA_RETIRADO";
    public static final String ERROR_MOTIVO_TRASLADO_VACIO = "ERROR_MOTIVO_TRASLADO_VACIO";
    public static final String ERROR_MATRICULA_ACTUAL_VACIO = "ERROR_MATRICULA_ACTUAL_VACIO";
    public static final String ERROR_COMPONENTE_PLAN_ESTUDIO_SIN_CALCULO_NOTA_INSTITUCIONAL = "ERROR_COMPONENTE_PLAN_ESTUDIO_SIN_CALCULO_NOTA_INSTITUCIONAL";
    public static final String ERROR_COMPONENTE_PLAN_ESTUDIO_SIN_FUNCION_REDONDEO = "ERROR_COMPONENTE_PLAN_ESTUDIO_SIN_FUNCION_REDONDEO";
    public static final String ERROR_NO_HAY_ANIO_LECTIVO_HABILITADO = "ERROR_NO_HAY_ANIO_LECTIVO_HABILITADO";
    public static final String ERROR_NO_HAY_SECCIONES_PARA_LOS_DATOS_SELECCIONADOS = "ERROR_NO_HAY_SECCIONES_PARA_LOS_DATOS_SELECCIONADOS";
    public static final String ERROR_IDENTIFICACIONES_OBLIGATORIA_VACIA = "ERROR_IDENTIFICACIONES_OBLIGATORIA_VACIA";
    public static final String ERROR_SERVICIO_EDUCATIVO_NO_ENCONTRADO = "ERROR_SERVICIO_EDUCATIVO_NO_ENCONTRADO";
    public static final String ERROR_MATRICULA_ABIERTA_ESTUDIANTE = "ERROR_MATRICULA_ABIERTA_ESTUDIANTE";
    public static final String APROBADO_CORRECTO = "APROBADO_CORRECTO";
    public static final String ERROR_DATOS_OBLIGATORIOS_VACIO = "ERROR_DATOS_OBLIGATORIOS_VACIO";
    public static final String ERROR_FILTRO_GRADO_VACIO = "ERROR_FILTRO_GRADO_VACIO";
    public static final String ERROR_FECHA_OTORGADO_VACIO = "ERROR_FECHA_OTORGADO_VACIO";
    public static final String ERROR_SEDE_VACIO = "ERROR_SEDE_VACIO";
    public static final String ERROR_CREACION_USUARIO_ALLEGADO = "ERROR_CREACION_USUARIO_ALLEGADO";
    public static final String ERROR_VALIDAR_ACTIVIADADES = "ERROR_VALIDAR_ACTIVIADADES";
    public static final String ERROR_COMPONENTE_PLAN_ESTUDIO_FORMULA_APROBACION = "ERROR_COMPONENTE_PLAN_ESTUDIO_FORMULA_APROBACION";
    public static final String ERROR_GRADO_SIN_FORMULA = "ERROR_GRADO_SIN_FORMULA";
    public static final String ERROR_ESCALA_CALIFICACION_ASOCIADA_NO_TIENE_VALOR_MINIMO = "ERROR_ESCALA_CALIFICACION_ASOCIADA_NO_TIENE_VALOR_MINIMO";
    public static final String WARNING_ESTUDIANTE_SOLO_LECTURA_PERTENECE_OTRA_INSTITUCION = "WARNING_ESTUDIANTE_SOLO_LECTURA_PERTENECE_OTRA_INSTITUCION";
    public static final String ERROR_NIE_ESTUDIANTE_NO_EXISTE = "ERROR_NIE_ESTUDIANTE_NO_EXISTE";
    public static final String ERROR_SECCION_IMPORT_VACIO = "ERROR_SECCION_IMPORT_VACIO";
    public static final String ERROR_FECHA_IMPORT_VACIO = "ERROR_FECHA_IMPORT_VACIO";
    public static final String ERROR_NIE_IMPORT_VACIO = "ERROR_NIE_IMPORT_VACIO";
    public static final String ERROR_NO_SE_ENCONTRO_ESTUDIANTE = "ERROR_NO_SE_ENCONTRO_ESTUDIANTE";
    public static final String ERROR_NO_SE_ENCONTRO_PERSONAL = "ERROR_NO_SE_ENCONTRO_PERSONAL";
    public static final String CAMBIO_ESTADO_APROBADO = "CAMBIO_ESTADO_APROBADO";
    public static final String CAMBIO_ESTADO_RECHAZADO = "CAMBIO_ESTADO_RECHAZADO";
    public static final String WARNING_RESPONSABLE_ES_PERSONAL_DE_SEDE = "WARNING_RESPONSABLE_ES_PERSONAL_DE_SEDE";
    public static final String ERROR_SECCION_DESTINO_VACIO = "ERROR_SECCION_DESTINO_VACIO";
    public static final String ERROR_LISTA_ESTUDIANTES_VACIO = "ERROR_LISTA_ESTUDIANTES_VACIO";
    public static final String ERROR_USUARIO_ALLEGADO_EXISTE = "ERROR_USUARIO_ALLEGADO_EXISTE";
    public static final String ERROR_MATRICULA_VACIO = "ERROR_MATRICULA_VACIO";
    public static final String ERROR_NO_EXISTEN_COMPONENTES_PLAN_GRADO = "ERROR_NO_EXISTEN_COMPONENTES_PLAN_GRADO";
    public static final String ERROR_CALIFICACIONES_PENDIENTES = "ERROR_CALIFICACIONES_PENDIENTES";
    public static final String ERROR_FECHA_INGRESO_VACIO = "ERROR_FECHA_INGRESO_VACIO";
    public static final String ERROR_ESTUDIANTE_VACIO = "ERROR_ESTUDIANTE_VACIO";
    public static final String WARNING_NUEVOS_ESTUDIANTES_EN_SECCION_SIN_CONTROL_ASISTENCIA = "WARNING_NUEVOS_ESTUDIANTES_EN_SECCION_SIN_CONTROL_ASISTENCIA";
    public static final String ERROR_FECHA_VACIO = "ERROR_FECHA_VACIO";
    public static final String ERROR_CODIGO_COMPONENTE_PLAN_ESTUDIO_IMPORT_VACIO = "ERROR_CODIGO_COMPONENTE_PLAN_ESTUDIO_IMPORT_VACIO";
    public static final String ERROR_RANGO_FECHA_IMPORT_VACIO = "ERROR_RANGO_FECHA_IMPORT_VACIO";
    public static final String ERROR_CALIFICACION_IMPORT_VACIO = "ERROR_CALIFICACION_IMPORT_VACIO";
    public static final String ERROR_NIE_NO_NUMERICO = "ERROR_NIE_NO_NUMERICO";
    public static final String ERROR_FECHA_FORMATO_INCORRECTO = "ERROR_FECHA_FORMATO_INCORRECTO";
    public static final String ERROR_ARCHIVO_VACIO = "ERROR_ARCHIVO_VACIO";
    public static final String VALIDACION_ARCHIVO = "VALIDACION_ARCHIVO";
    public static final String ARCHIVO_EXITOSAMENTE_COLA = "ARCHIVO_EXITOSAMENTE_COLA";
    public static final String ERROR_EDAD_MAXIMA_MAYOR_100 = "ERROR_EDAD_MAXIMA_MAYOR_100";
    public static final String ERROR_PERIODO_MATRICULA_CERRADO = "ERROR_PERIODO_MATRICULA_CERRADO";
    public static final String ERROR_IDENTIFICACION_DUPLICADA = "ERROR_IDENTIFICACION_DUPLICADA";
    public static final String ERROR_IDENTIFICACION_DUPLICADA_OAE = "ERROR_IDENTIFICACION_DUPLICADA_OAE";
    public static final String ERROR_MATRICULA_ANULADA = "ERROR_MATRICULA_ANULADA";

    public static final String ERROR_DIMENSIONES_IMAGENES = "ERROR_DIMENSIONES_IMAGENES";
    public static final String ERROR_CONFIGURACION_ARCHIVO_VACIO = "ERROR_CONFIGURACION_ARCHIVO_VACIO";
    public static final String WARNING_CONTROL_ASISTENCIA_ANIO_LECTIVO_CERRADO = "WARNING_CONTROL_ASISTENCIA_ANIO_LECTIVO_CERRADO";
    public static final String WARNING_CALIFICACION_RANGO_FECHA_DESHABILITADO = "WARNING_CALIFICACION_RANGO_FECHA_DESHABILITADO";
    public static final String ERROR_TRASLADO_DIFERENTE_GRADO = "ERROR_TRASLADO_DIFERENTE_GRADO";
    public static final String ERROR_SUB_MODALIDAD_VACIO = "ERROR_SUB_MODALIDAD_VACIO";
    public static final String ERROR_IDENTIFICACIONES_OBLIGATORIA_NIP_VACIA = "ERROR_IDENTIFICACIONES_OBLIGATORIA_NIP_VACIA";
    public static final String ERROR_NO_SE_ENCONTRARON_EQUIVALENCIAS = "ERROR_NO_SE_ENCONTRARON_EQUIVALENCIAS";
    public static final String ERROR_NUMERO_PERIODO_MENOR_RANGO_FECHA = "ERROR_NUMERO_PERIODO_MENOR_RANGO_FECHA";
    public static final String ERROR_RETIRO_TRASLADO_EN_PROCESO = "ERROR_RETIRO_TRASLADO_EN_PROCESO";
    public static final String ERROR_NO_PUEDE_CAMBIAR_FECHA = "ERROR_NO_PUEDE_CAMBIAR_FECHA";
    public static final String WARNING_NO_HAY_SECCIONES = "WARNING_NO_HAY_SECCIONES";
    public static final String ERROR_VALIDAR_MATRICULA = "ERROR_VALIDAR_MATRICULA";
    public static final String ERROR_SECCIONES_NO_EQUIVALENTES = "ERROR_SECCIONES_NO_EQUIVALENTES";
    public static final String ERROR_ANIO_SECCIONES_DIFIERE = "ERROR_ANIO_SECCIONES_DIFIERE";
    public static final String ARCHIVOS_PENDIENTES_PROCESADOS = "ARCHIVOS_PENDIENTES_PROCESADOS";
    public static final String ERROR_ESTUDIANTE_PROMOVIDO = "ERROR_ESTUDIANTE_PROMOVIDO";
    public static final String ANIO_CERRADO_EXITO = "ANIO_CERRADO_EXITO";
    public static final String WARNING_SECCION_CERRADO = "WARNING_SECCION_CERRADO";
    public static final String EXISTE_ESTUDIANTE_SIN_PERIODOS = "EXISTE_ESTUDIANTE_SIN_PERIODOS";
    public static final String NOTA_INSTITUCIONAL_GENERADA_CORRECTAMENTE = "NOTA_INSTITUCIONAL_GENERADA_CORRECTAMENTE";
    public static final String NOTA_APROBACION_GENERADA_CORRECTAMENTE = "NOTA_APROBACION_GENERADA_CORRECTAMENTE";
    public static final String WARNING_GUARDAR_CAMBIOS = "WARNING_GUARDAR_CAMBIOS";
    public static final String ERROR_PERSONAL_VACIO = "ERROR_PERSONAL_VACIO";
    public static final String ERROR_EXISTE_CONTROL_ASISTENCIA_PARA_FECHA = "ERROR_EXISTE_CONTROL_ASISTENCIA_PARA_FECHA";
    public static final String ERROR_EXISTE_CONTROL_ASISTENCIA_PARA_DIA = "ERROR_EXISTE_CONTROL_ASISTENCIA_PARA_DIA";
    public static final String CAMBIO_ESTADO_AMPLIAR_DATOS = "CAMBIO_ESTADO_AMPLIAR_DATOS";
    public static final String TOTAL_MENOR_FLUJO = "TOTAL_MENOR_FLUJO";
    public static final String ERROR_MONTO_MAYOR_FORMULACION = "ERROR_MONTO_MAYOR_FORMULACION";
    public static final String ERROR_MONTO_APROBADO_MAYOR_FORMULACION = "ERROR_MONTO_APROBADO_MAYOR_FORMULACION";

    public static final String ERROR_REQS_CED_GUARDAR = "ERROR_REQS_CED_GUARDAR";
    public static final String ERROR_REQS_CED_LIST_GUARDAR = "ERROR_REQS_CED_LIST_GUARDAR";
    public static final String ERROR_DET_REQ_CED_GUARDAR = "ERROR_DET_REQ_CED_GUARDAR";
    public static final String ERROR_VERIFICAR_SALDOS = "ERROR_VERIFICAR_SALDOS";
    public static final String ERROR_VERIFICAR_SALDOS_TRANSFERENCIAS = "ERROR_VERIFICAR_SALDOS_TRANSFERENCIAS";
    public static final String ERROR_PRESUPUESTO_SIN_MOVIMIENTOS = "ERROR_PRESUPUESTO_SIN_MOVIMIENTOS";
    public static final String ERROR_EGRESOS_MONTO_APROBADO = "ERROR_EGRESOS_MONTO_APROBADO";

    public static final String ERROR_RECIBO_SIN_PEA = "ERROR_RECIBO_SIN_PEA";
    public static final String ERROR_RECIBO_SIN_DOC = "ERROR_RECIBO_SIN_DOC";
    public static final String ERROR_RECIBO_ESTADO_DOC = "ERROR_RECIBO_ESTADO_DOC";
    public static final String ERROR_RECIBO_OBTENER = "ERROR_RECIBO_OBTENER";
    public static final String ERROR_DEPARTAMENTO_DUPLICADO = "ERROR_DEPARTAMENTO_DUPLICADO";
    public static final String ERROR_VERIFICAR_SALDOS_EGRESOS_APROBADOS = "ERROR_VERIFICAR_SALDOS_EGRESOS_APROBADOS";
    public static final String ERROR_MONTO_APROBADO_PLAN_COMPRA = "ERROR_MONTO_APROBADO_PLAN_COMPRA";
    public static final String ERROR_INSUMOS_VACIOS = "ERROR_INSUMOS_VACIOS";

    public static final String ERROR_LISTA_DET_DESEMBOLSO = "ERROR_LISTA_DET_DESEMBOLSO";
    public static final String ERROR_PORCENTAJE_DET_DESEMBOLSO = "ERROR_PORCENTAJE_DET_DESEMBOLSO";
    public static final String ANULADO_ELIMINADO_CORRECTO = "ANULADO_ELIMINADO_CORRECTO";
    public static final String ERROR_SAC_UFI_IMPORT_VACIO = "ERROR_SAC_UFI_IMPORT_VACIO";
    public static final String ERROR_SAC_GOES_IMPORT_VACIO = "ERROR_SAC_GOES_IMPORT_VACIO";
    public static final String ERROR_ID_REQ_IMPORT_VACIO = "ERROR_ID_REQ_IMPORT_VACIO";
    public static final String ERROR_COMPROMISO_IMPORT_VACIO = "ERROR_COMPROMISO_IMPORT_VACIO";
    public static final String ERROR_IMPORT_REQ_SAC = "ERROR_IMPORT_REQ_SAC";
    public static final String IMPORT_REQ_SAC_CORRECTA = "IMPORT_REQ_SAC_CORRECTA";
    public static final String DESEMBOLSO_MOVIMIENTO_GUARDAR = "DESEMBOLSO_MOVIMIENTO_GUARDAR";
    public static final String ERROR_PRESUPUESTO_NO_EXITE = "ERROR_PRESUPUESTO_NO_EXITE";
    public static final String ERROR_LIQUIDACION_GUARDAR = "ERROR_LIQUIDACION_GUARDAR";
    public static final String ERROR_MOV_LIQUIDACION_EMPTY = "ERROR_MOV_LIQUIDACION_EMPTY";
    public static final String ERROR_MOV_LIQUIDACION_ESTADO = "ERROR_MOV_LIQUIDACION_ESTADO";
    public static final String ERROR_MOV_LIQUIDACION_LIST = "ERROR_MOV_LIQUIDACION_LIST";
    public static final String ERROR_MOV_LIQ_MOTIVO_VACIO = "ERROR_MOV_LIQ_MOTIVO_VACIO";
    public static final String ERROR_LIQUIDACION_INGRESOS_GUARDAR = "ERROR_LIQUIDACION_INGRESOS_GUARDAR";
    public static final String ERROR_DESEMBOLSO_CED_CUENTA = "ERROR_DESEMBOLSO_CED_CUENTA";
    public static final String ERROR_PLAN_COMPRAS_VACIO = "ERROR_PLAN_COMPRAS_VACIO";
    public static final String ERROR_PLAN_NO_APROBADO = "ERROR_PLAN_NO_APROBADO";

    public static final String ERROR_FACTURA_MOVIMIENTOS = "ERROR_FACTURA_MOVIMIENTOS";
    public static final String ERROR_EVALUACION_LIQUIDACION_VACIA = "ERROR_EVALUACION_LIQUIDACION_VACIA";
    public static final String ERROR_EVALUACION_ITEM_VACIA = "ERROR_EVALUACION_ITEM_VACIA";
    public static final String ERROR_ESTADO_REQ = "ERROR_ESTADO_REQ";
    public static final String ERROR_CHEQUERA_NO_EXITE = "ERROR_CHEQUERA_NO_EXITE";
    public static final String ERROR_CHEQUE_NO_EXITE = "ERROR_CHEQUE_NO_EXITE";
    public static final String ERROR_COMENTARIO_ELIMINACION_PAGO_VACIO = "ERROR_COMENTARIO_ELIMINACION_PAGO_VACIO";
    public static final String ERROR_CHEQUERA_RANGO_INVALIDO = "ERROR_CHEQUERA_RANGO_INVALIDO";

    public static final String ERROR_ID_RUBRO_VACIO = "ERROR_ID_RUBRO_VACIO";
    public static final String ERROR_DESCRIPCION_INGRESO_VACIA = "ERROR_DESCRIPCION_INGRESO_VACIA";
    public static final String ERROR_MONTO_INGRESO_VACIO = "ERROR_MONTO_INGRESO_VACIO";

    public static final String ERROR_LIQUIDACION_EXISTE = "ERROR_LIQUIDACION_EXISTE";
    public static final String ERROR_NEGATIVO_EGRESOS_MONTO_APROBADO = "ERROR_NEGATIVO_EGRESOS_MONTO_APROBADO";
    public static final String ERROR_MONTO_AUTORIZADO_MENOR = "ERROR_MONTO_AUTORIZADO_MENOR";
    public static final String ERROR_CAJA_CHICA_OTROS_INGRESOS = "ERROR_CAJA_CHICA_OTROS_INGRESOS";
    public static final String ERROR_CAJA_CHICA_SUBCOMPONENTE = "ERROR_CAJA_CHICA_SUBCOMPONENTE";
    public static final String ERROR_PRESUPUESTO_LIQUIDACIONES_PENDIENTES = "ERROR_PRESUPUESTO_LIQUIDACIONES_PENDIENTES";

}
