/*
 * Proyecto: Sistema Integrado de Administracion de Proyectos II
 * Organismo: Ministerio de Educacion de El Salvador
 * Desarrollado por: Sofis Solutions
 *
 */
package gob.mined.siap2.entities.constantes;

/**
 * Esta clase incluye constantes de configuración del sistema.
 *
 * @author Sofis Solutions
 */
public class ConstantesConfiguracion {

    public static final boolean DEBUG_CONSULTAS_JPA = true;

    public static final String CODIGO_CONTRASENIA_INICIAL = "PASSWORD_INICIAL";
    public static final String WSDL_CONSULTA_OT = "WSDL_CONSULTA_OT";

    public static final  String CUMPLIMIENTO_COMIENZO_COLOR_VERDE = "CUMPLIMIENTO_COMIENZO_COLOR_VERDE";
    public static final  String CUMPLIMIENTO_COMIENZO_COLOR_AMARILLO = "CUMPLIMIENTO_COMIENZO_COLOR_AMARILLO";

    public static final  String RUTA_ARCHIVOS = "RUTA_ARCHIVOS";
    public static final  String REPORTE_RUTA_LOGO = "REPORTE_RUTA_LOGO";

    public static final  String NOTIFICACION_POA_VALIDO = "NOTIFICACION_POA_VALIDO";
    public static final  String NOTIFICACION_POA_PARA_VALIDAR = "NOTIFICACION_POA_PARA_VALIDAR";
    public static final  String PLAZO_PAUZA_ITEM = "PLAZO_PAUZA_ITEM";

    public static final  String REPRESENTANTE_MINED_ORDEN_COMPRA = "REPRESENTANTE_MINED_ORDEN_COMPRA";
    public static final  String AUTORIZADO_MINED_INVITACION_PROVEEDOR = "AUTORIZADO_MINED_INVITACION_PROVEEDOR";
    public static final  String TEXTO_INVITACIONES_PROVEEDOR = "TEXTO_INVITACIONES_PROVEEDOR";

    public static final  String URL_RECUPERAR_CONTRASENIA = "URL_RECUPERAR_CONTRASENIA";
    public static final  String TEXTO_RECUPERAR_CONTRASENIA = "TEXTO_RECUPERAR_CONTRASENIA";

    public static final  String ANIO_TECHO_CATEGORIA_PRESUPUESTAL = "ANIO_TECHO_CATEGORIA_PRESUPUESTAL";
    public static final  String CANTIDAD_AMOS_PLANIFICACION = "CANTIDAD_AMOS_PLANIFICACION";

    public static final  String CONTRASENIA_LARGO_MINIMO = "PWD_LARGO_MINIMO";
    public static final  String CONTRASENIA_CANTIDAD_MINIMA_CARACTERES_ESPECIALES = "PWD_CANTIDAD_MINIMA_CARACTERES_ESPECIALES";
    public static final  String CONTRASENIA_CANTIDAD_MINIMA_MAYUSCULAS = "PWD_CANTIDAD_MINIMA_MAYUSCULAS";
    public static final  String CONTRASENIA_CANTIDAD_MINIMA_MINUSCULAS = "PWD_CANTIDAD_MINIMA_MINUSCULAS";
    public static final  String CONTRASENIA_CANTIDAD_MINIMA_DIGITOS = "PWD_CANTIDAD_MINIMA_DIGITOS";

    public static final  String CODIGO_TIPO_DE_ARCHIVO_PRORROGA = "CODIGO_TIPO_DE_ARCHIVO_PRORROGA";
    public static final  String CODIGO_TIPO_DE_ARCHIVO_DESEMBOLSO = "CODIGO_TIPO_DE_ARCHIVO_DESEMBOLSO";
    public static final  String CODIGO_TIPO_DE_ARCHIVO_ENMIENDA = "CODIGO_TIPO_DE_ARCHIVO_ENMIENDA";

    public static final  String ASUNTO_MAIL_NUEVO_USUARIO = "ASUNTO_MAIL_NUEVO_USUARIO";
    public static final  String TEMPLATE_MENSAJE_MAIL_NUEVO_USUARIO = "TEMPLATE_MENSAJE_MAIL_NUEVO_USUARIO";

    public static final  String CONTENIDO_REPORTE_ORDEN_INICIO = "CONTENIDO_REPORTE_ORDEN_INICIO";

    public static final  String REPORTE_QUEDAN_NOTA_PIE_PAGINA = "REPORTE_QUEDAN_NOTA_PIE_PAGINA";

    public static final  String NIT_DEL_MINISTERIO = "NIT_DEL_MINISTERIO";

    public static final  String DENOMINACION_MONEDA = "DENOMINACION_MONEDA";
    public static final  String SIMBOLO_MONEDA = "SIMBOLO_MONEDA";

    public static final  String CONTENIDO_CONSTANCIA_ANUAL_RETENCION_POR_PROVEEDOR = "CONTENIDO_CONSTANCIA_ANUAL_RETENCION_POR_PROVEEDOR";
    
    public static final  String CODIGO_INGRESO_PROVEEDOR_ES_PERSONA_FISICA = "11";
    
    public static final  String CODIGO_INGRESO_PROVEEDOR_ES_PERSONA_JURIDICA = "12";
    
    public static final String TITULO_MINISTERIO_REPORTES = "TITULO_MINISTERIO_REPORTES";
    
    public static final String ACLARACION_MONEDA_MONTOS_REPORTES = "ACLARACION_MONEDA_MONTOS_REPORTES";
    
    public static final String RETENCION_IMPUESTO_PROY_CALIDAD_ACTUA = "RETENCION_IMPUESTO_PROY_CALIDAD_ACTUA";
    
    public static final String RETENCION_IMPUESTO_PROY_MODALIDAD = "RETENCION_IMPUESTO_PROY_MODALIDAD";
    
    public static final String RETENCION_IMPUESTO_PROY_CODIGO_DOC = "RETENCION_IMPUESTO_PROY_CODIGO_DOC";
    
    /*Títulos y áreas de los reportes pdf*/
    
    public static final String REPORTE_AREA_CERT_DISP_PRESUP_INSUMO = "REPORTE_AREA_CERT_DISP_PRESUP_INSUMO";

    public static final String REPORTE_TITULO_CERT_DISP_PRESUP_INSUMO = "REPORTE_TITULO_CERT_DISP_PRESUP_INSUMO";
    
    public static final String REPORTE_AREA_ANEXO_DOCUMENTO_COMPRA = "REPORTE_AREA_ANEXO_DOCUMENTO_COMPRA";
    
    public static final String REPORTE_TITULO_ANEXO_DOCUMENTO_COMPRA = "REPORTE_TITULO_ANEXO_DOCUMENTO_COMPRA";
    
    public static final String REPORTE_AREA_POLIZA_CONCENTRACION = "REPORTE_AREA_POLIZA_CONCENTRACION";
    
    public static final String REPORTE_TITULO_POLIZA_CONCENTRACION = "REPORTE_TITULO_POLIZA_CONCENTRACION";
    
    public static final String REPORTE_AREA_DOCUMENTO_ORDEN_COMPRA = "REPORTE_AREA_DOCUMENTO_ORDEN_COMPRA";
    
    public static final String REPORTE_TITULO_DOCUMENTO_ORDEN_COMPRA="REPORTE_TITULO_DOCUMENTO_ORDEN_COMPRA";
    
    public static final String REPORTE_AREA_INVITACION_PROVEEDRES = "REPORTE_AREA_INVITACION_PROVEEDRES";
    
    public static final String REPORTE_TITULO_INVITACION_PROVEEDRES = "REPORTE_TITULO_INVITACION_PROVEEDRES";
    
    public static final String REPORTE_AREA_RESERVA_FONDOS = "REPORTE_AREA_RESERVA_FONDOS";
    
    public static final String REPORTE_TITULO_RESERVA_FONDOS = "REPORTE_TITULO_RESERVA_FONDOS";
    
    public static final String REPORTE_AREA_PAC = "REPORTE_AREA_PAC";
    
    public static final String REPORTE_TITULO_PAC = "REPORTE_TITULO_PAC";
    
    public static final String REPORTE_AREA_PAC_GLOBAL = "REPORTE_AREA_PAC_GLOBAL";
    
    public static final String REPORTE_TITULO_PAC_GLOBAL = "REPORTE_TITULO_PAC_GLOBAL";
    
    public static final String REPORTE_AREA_PEP_GLOBAL = "REPORTE_AREA_PEP_GLOBAL";
    
    public static final String REPORTE_TITULO_PEP_GLOBAL = "REPORTE_TITULO_PEP_GLOBAL";
    
    public static final String REPORTE_TITULO_PEP_POA = "REPORTE_TITULO_PEP_POA";
    
    public static final String REPORTE_AREA_ACTA_RECEPCION = "REPORTE_AREA_ACTA_RECEPCION";
    
    public static final String REPORTE_TITULO_ACTA_RECEPCION = "REPORTE_TITULO_ACTA_RECEPCION";
    
    public static final String REPORTE_AREA_ACTA_ANTICIPO = "REPORTE_AREA_ACTA_ANTICIPO";
    
    public static final String REPORTE_TITULO_ACTA_ANTICIPO = "REPORTE_TITULO_ACTA_ANTICIPO";
    
    public static final String REPORTE_AREA_ACTA_DEVOLUCION = "REPORTE_AREA_ACTA_DEVOLUCION";
    
    public static final String REPORTE_TITULO_ACTA_DEVOLUCION = "REPORTE_TITULO_ACTA_DEVOLUCION";
    
    public static final String REPORTE_AREA_QUEDAN = "REPORTE_AREA_QUEDAN";
    
    public static final String REPORTE_TITULO_QUEDAN = "REPORTE_TITULO_QUEDAN";
    
    public static final String REPORTE_AREA_ANP_GRAL = "REPORTE_AREA_ANP_GRAL";
    
    public static final String REPORTE_TITULO_ANP_GRAL = "REPORTE_TITULO_ANP_GRAL";
    
    public static final String REPORTE_AREA_AC_GRAL = "REPORTE_AREA_AC_GRAL";
    
    public static final String REPORTE_TITULO_AC_GRAL = "REPORTE_TITULO_AC_GRAL";
    
    public static final String REPORTE_AREA_PROYECTO = "REPORTE_AREA_PROYECTO";
    
    public static final String REPORTE_TITULO_PROYECTO = "REPORTE_TITULO_PROYECTO";    
    
    public static final String REPORTE_AREA_ORDEN_INICIO = "REPORTE_AREA_ORDEN_INICIO";
    
    public static final String REPORTE_TITULO_ORDEN_INICIO = "REPORTE_TITULO_ORDEN_INICIO";        
    
    public static final String REPORTE_AREA_COMPROBANTE_REC_EXP_PAGO = "REPORTE_AREA_COMPROBANTE_REC_EXP_PAGO";
    
    public static final String REPORTE_TITULO_COMPROBANTE_REC_EXP_PAGO = "REPORTE_TITULO_COMPROBANTE_REC_EXP_PAGO";
    
    public static final String REPORTE_AREA_RETENCION_IMPUESTO_POR_PROYECTO = "REPORTE_AREA_RETENCION_IMPUESTO_POR_PROYECTO";
    
    public static final String REPORTE_TITULO_RETENCION_IMPUESTO_POR_PROYECTO = "REPORTE_TITULO_RETENCION_IMPUESTO_POR_PROYECTO";    
    
    public static final String REPORTE_AREA_RETENCION_IMPUESTO_POR_PROVEEDOR = "REPORTE_AREA_RETENCION_IMPUESTO_POR_PROVEEDOR";
    
    public static final String REPORTE_TITULO_RETENCION_IMPUESTO_POR_PROVEEDOR = "REPORTE_TITULO_RETENCION_IMPUESTO_POR_PROVEEDOR";    
    
    public static final String REPORTE_AREA_CONST_ANUAL_RETENCION_IMPUESTO_POR_PROVEEDOR = "REPORTE_AREA_CONST_ANUAL_RETENCION_IMPUESTO_POR_PROVEEDOR";
    
    public static final String REPORTE_TITULO_CONST_ANUAL_RETENCION_IMPUESTO_POR_PROVEEDOR = "REPORTE_TITULO_CONST_ANUAL_RETENCION_IMPUESTO_POR_PROVEEDOR";    
    
    public static final String REPORTE_AREA_FICHA_CONTRATO = "REPORTE_AREA_FICHA_CONTRATO";
    
    public static final String REPORTE_TITULO_FICHA_CONTRATO = "REPORTE_TITULO_FICHA_CONTRATO";        
    
    public static final String REPORTE_AREA_COMPROMISO_PRESUPUESTARIO = "REPORTE_AREA_COMPROMISO_PRESUPUESTARIO";
    
    public static final String REPORTE_TITULO_COMPROMISO_PRESUPUESTARIO = "REPORTE_TITULO_COMPROMISO_PRESUPUESTARIO";
    
    public static final String REPORTE_AREA_REPROGRAMACION = "REPORTE_AREA_REPROGRAMACION";
    
    public static final String REPORTE_TITULO_COMPROMISO_REPROGRAMACION = "REPORTE_TITULO_COMPROMISO_REPROGRAMACION";
    
    public static final String REPORTE_AREA_SEGUIMIENTO_PROY_ADMINISTRATIVO_MENSUAL = "REPORTE_AREA_SEGUIMIENTO_PROY_ADMINISTRATIVO_MENSUAL";
    
    public static final String REPORTE_TITULO_SEGUIMIENTO_PROY_ADMINISTRATIVO_MENSUAL = "REPORTE_TITULO_SEGUIMIENTO_PROY_ADMINISTRATIVO_MENSUAL";    
    
    public static final String REPORTE_AREA_SEGUIMIENTO_PROY_ADMINISTRATIVO_TRIMESTRAL = "REPORTE_AREA_SEGUIMIENTO_PROY_ADMINISTRATIVO_TRIMESTRAL";
    
    public static final String REPORTE_TITULO_SEGUIMIENTO_PROY_ADMINISTRATIVO_TRIMESTRAL = "REPORTE_TITULO_SEGUIMIENTO_PROY_ADMINISTRATIVO_TRIMESTRAL";
    
    public static final String REPORTE_AREA_POI = "REPORTE_AREA_POI";
    
    public static final String REPORTE_TITULO_POI = "REPORTE_TITULO_POI";
    
    public static final String REPORTE_AREA_MATRIZ_RIESGO = "REPORTE_AREA_MATRIZ_RIESGO";
    
    public static final String REPORTE_TITULO_MATRIZ_RIESGO = "REPORTE_TITULO_MATRIZ_RIESGO";
    
    public static final String REPORTE_AREA_COMPROMISO_PARA_PROGRAMACION_PAGOS = "REPORTE_AREA_COMPROMISO_PARA_PROGRAMACION_PAGOS";
    
    public static final String REPORTE_TITULO_COMPROMISO_PARA_PROGRAMACION_PAGOS = "REPORTE_TITULO_COMPROMISO_PARA_PROGRAMACION_PAGOS";
    
    public static final String REPORTE_AREA_CERTIFICADO_DISPONIBILIDAD_PROCESO = "REPORTE_AREA_CERTIFICADO_DISPONIBILIDAD_PROCESO";
    
    public static final String REPORTE_TITULO_CERTIFICADO_DISPONIBILIDAD_PROCESO = "REPORTE_TITULO_CERTIFICADO_DISPONIBILIDAD_PROCESO";
    
    public static final String CODIGO_PAIS_PROVEEDOR_EL_SALVADOR = "CODIGO_PAIS_PROVEEDOR_EL_SALVADOR";
    
    public static final String REPORTE_TITULO_METAS_POA = "REPORTE_TITULO_METAS_POA";
    
    public static final String URL_MANUAL_USUARIO = "URL_MANUAL_USUARIO";
}
