/*
 * Proyecto: Sistema Integrado de Administracion de Proyectos II
 * Organismo: Ministerio de Educacion de El Salvador
 * Desarrollado por: Sofis Solutions
 *
 */
package gob.mined.siap2.entities.constantes;

/**
 * ESta clase incluye las constantes de errores que aplican a las excepciones.
 *
 * @author Sofis
 */
public class ConstantesErrores {

    public static final String ERROR_DATO_VACIO = "DAT_VAC";
    public static final String ERROR_CODIGO_VACIO = "COD_VAC";
    public static final String ERROR_DESCRIPCION_VACIO = "DES_VAC";
    public static final String RUT_VACIO = "RUT_VAC";
    public static final String DENOMINACION_SOCIAL_VACIO = "DENOMINACION_SOCIAL_VACIO";
    public static final String CARGO_VACIO = "CARGO_VAC";
    public static final String PRIM_NOM_VACIO = "PRIM_NOM_VAC";
    public static final String PRIM_APE_VACIO = "PRIM_APE_VAC";
    public static final String EMAIL_INCORRECTO = "EMAIL_INCOR";
    public static final String EMAIL_VAC = "EMAIL_VAC";
    public static final String FECHA_INGRESO_VACIA = "FECHA_INGRESO_VACIA";
    public static final String FECHA_INGRESO_INCORRECTA = "FECHA_INGRESO_INCORRECTA";
    public static final String EMPRESA_VACIA = "EMPRESA_VACIA";
    public static final String TELEFONO_VACIO = "TEL_VAC";
    public static final String ERROR_VALOR_VACIO = "VAL_VAC";
    public static final String CI_INCORRECTA = "CI_INC";
    public static final String PERSONA_VACIA = "PER_VAC";
    public static final String ERR_GNRAL_SAVE_UPDATE = "ERR_GNRAL_SAVE_UPDATE";
    public static final String ERROR_CONFIGURACION_PERISOS_USUARIO = "ERROR_CONFIGURACION_PERISOS_USUARIO";
    public static final String ERROR_DEMASIADOS_RESULTADOS = "DEM_RES";
    public static final String ERROR_PARA_GUARDAR_ARCHIVOS_DEBE_CONFIRAR_RUTA = "ERROR_PARA_GUARDAR_ARCHIVOS_DEBE_CONFIRAR_RUTA";
    public static final String ERR_IMAGEN_NO_VALIDA = "ERR_IMAGEN_NO_VALIDA";
    public static final String ERR_EL_CODIGO_USUARIO_YA_EXISTE = "ERR_EL_CODIGO_USUARIO_YA_EXISTE";

    public static final String ERROR_GENERAL = "ERR_GRAL";

    public static final String ERROR_CODIGO_ROL_REPETIDO = "ERROR_CODIGO_ROL_REPETIDO";

     public static final String ERR_GNRAL_SAVE_UPDATE_TOPES = "ERR_GNRAL_SAVE_UPDATE_TOPES";
      public static final String ERR_GNRAL_DELETE_TOPES = "ERR_GNRAL_DELETE_TOPES";
    //multiple idioma
    public static final String ERROR_CODIGO_REPETIDO = "ERROR_CODIGO_REPETIDO";
    public static final String ERROR_CODIGO_REPETIDO_ANIO = "ERROR_CODIGO_REPETIDO_ANIO";
    public static final String ERROR_TIPO_SERVIICO_DESCONOCIDO = "ERROR_TIPO_SERVIICO_DESCONOCIDO";
    public static final String ERROR_ACTUALIZANDO_CODIGUERAS = "ERROR_ACTUALIZANDO_CODIGUERAS";
    public static final String ERROR_PLANIFICACION_LINEA_NO_ENCONTRADO = "ERROR_PLANIFICACION_LINEA_NO_ENCONTRADO";

    public static final String ERROR_HAY_PI_ASOCIADO_A_PLANIFICACION_Y_LINEA = "ERROR_HAY_PI_ASOCIADO_A_PLANIFICACION_Y_LINEA";
    public static final String ERROR_HAY_PP_ASOCIADO_A_PLANIFICACION_Y_LINEA = "ERROR_HAY_PP_ASOCIADO_A_PLANIFICACION_Y_LINEA";
    public static final String ERROR_HAY_AC_ASOCIADO_A_PLANIFICACION_Y_LINEA = "ERROR_HAY_AC_ASOCIADO_A_PLANIFICACION_Y_LINEA";
    public static final String ERROR_HAY_ANP_ASOCIADO_A_PLANIFICACION_Y_LINEA = "ERROR_HAY_ANP_ASOCIADO_A_PLANIFICACION_Y_LINEA";

    public static final String ERROR_CONTRASENIAS_NO_COINCIDEN = "ERROR_CONTRASENIAS_NO_COINCIDEN";
    public static final String ERROR_CONTRASENIA_NO_CUMPLE_EXPRESION_REGULAR = "ERROR_CONTRASENIA_NO_CUMPLE_EXPRESION_REGULAR";
    public static final String ERROR_CONTRASENIA_NO_PUEDE_INCLUIR_CODIGO_USUARIO = "ERROR_CONTRASENIA_NO_PUEDE_INCLUIR_CODIGO_USUARIO";

    //codigos numericos error
    public static final String CODIGO_NO_EXISTE_PAIS = "800";
    public static final String CODIGO_NO_HAY_HORA_DE_ENTRADA_PARA_EL_CAMION = "400";
    public static final String CODIGO_ERROR_EN_FORMATO_FECHA_HORA = "200";
    public static final String CODIGO_ERROR_INSUFICIENTES_LUGARES_DECLARADOS_EN_OPERACION = "300";
    public static final String CODIGO_ERROR_USUARIO_NO_PERTENECE_OFICINA = "600";
    public static final String CODIGO_ERROR_SIN_AUTORIZACION_PARA_OPERACION = "700";
    public static final String CODIGO_ERROR_CONTRASENIAS_NO_COINCIDEN = "750";
    public static final String CODIGO_ERROR_CONTRASENIA_NO_CUMPLE_EXPRESION_REGULAR = "780";
    public static final String CODIGO_ERROR_CONTRASENIA_NO_PUEDE_INCLUIR_CODIGO_USUARIO = "790";

    //generales
    public static final String ERR_NOMBRE_REPETIDO = "ERR_NOMBRE_REPETIDO";
    public static final String ERR_CODIGO_REPETIDO = "ERR_CODIGO_REPETIDO";
    public static final String ERR_EXISTE_ENTIDAD_ASOCIADA = "ERR_EXISTE_ENTIDAD_ASOCIADA";
    public static final String ERR_EXISTE_ENTIDAD_ASOCIADA_SIN_PARAMETROS = "ERR_EXISTE_ENTIDAD_ASOCIADA_SIN_PARAMETROS";
    public static final String ERR_NO_TIENE_PERMISO_VER_LINEA_TRABAJO = "ERR_NO_TIENE_PERMISO_VER_LINEA_TRABAJO";
    public static final String ERR_NO_TIENE_PERMISO_PARA_ACCCION_SOLICITADA = "ERR_NO_TIENE_PERMISO_PARA_ACCCION_SOLICITADA";
    public static final String ERR_SOLO_ES_EDITABLE_LINEA_TRABAJO = "ERR_SOLO_ES_EDITABLE_LINEA_TRABAJO";
    public static final String ERR_SOLO_PUEDE_TRABAJAR_SOBRE_LINEA_BASE = "ERR_SOLO_PUEDE_TRABAJAR_SOBRE_LINEA_BASE";
    public static final String ERR_NO_PUEDE_EDITAR_ELEMENTOS_SIN_PERMISO_LINEA_TRABAJO = "ERR_NO_PUEDE_EDITAR_ELEMENTOS_SIN_PERMISO_LINEA_TRABAJO";
    public static final String ERR_SOLO_EDITABLE_LINEA_TRABAJO = "ERR_SOLO_EDITABLE_LINEA_TRABAJO";
    public static final String ERROR_VALOR_PORCENTAJE_INCORRECTO = "ERROR_VALOR_PORCENTAJE_INCORRECTO";
    public static final String ERR_SOLO_PUEDE_ARRASTRAR_INSUMOS_A_UN_GRUPO = "ERR_SOLO_PUEDE_ARRASTRAR_INSUMOS_A_UN_GRUPO";

//planificacion estrategica
    public static final String ERR_PLANIFICACION_SUPERPONE_PERIODO = "ERR_PLANIFICACION_SUPERPONE_PERIODO";
    public static final String ERR_EXISTE_ENTIDAD_ASOCIADA_A_LA_RELACION_LINEA_PLANIFICACION = "ERR_EXISTE_ENTIDAD_ASOCIADA_A_LA_RELACION_LINEA_PLANIFICACION";
    public static final String ERR_FECHA_DESDE_MAYOR_QUE_HASTA = "ERR_FECHA_DESDE_MAYOR_QUE_HASTA";

    //pgrograma isntitucional
    public static final String ERR_EXISTE_PROGRAMA_PRESUPUESTARIO_ASOCIADO = "ERR_EXISTE_PROGRAMA_PRESUPUESTARIO_ASOCIADO";
    public static final String ERR_UN_SUBPROGRAMA_PERTENECE_A_LINEA_ESTRATEGICA_QUE_NO_PERTENECE_EL_PADRE = "ERR_UN_SUBPROGRAMA_PERTENECE_A_LINEA_ESTRATEGICA_QUE_NO_PERTENECE_EL_PADRE";
    public static final String ERR_UN_EXISTEN_SUBPROGRAMAS_CON_EL_MISMO_NOMBRE_0 = "ERR_UN_EXISTEN_SUBPROGRAMAS_CON_EL_MISMO_NOMBRE_0";
    public static final String ERR_SUBPROGRAMAS_TIENE_MISMO_NOMBRE_QUE_PROGRAMA_0 = "ERR_SUBPROGRAMAS_TIENE_MISMO_NOMBRE_QUE_PROGRAMA_0";
    //accion central
    public static final String ERR_YA_EXISTE_DICHO_ANIO_FISCAL = "ERR_YA_EXISTE_DICHO_ANIO_FISCAL";
    public static final String ERR_ANIO_FISCAL_Y_AÑO_INICIO_CRONO_DISTINTOS = "ERR_ANIO_FISCAL_Y_AÑO_INICIO_CRONO_DISTINTOS";
    public static final String ERR_YA_EXISTE_MONTO_PARA_UNIDAD_TECNICA = "ERR_YA_EXISTE_MONTO_PARA_UNIDAD_TECNICA";
    public static final String ERR_SUMA_UNIDADES_TECNICAS_SOBREPASA_MONTO_ANIO = "ERR_SUMA_UNIDADES_TECNICAS_SOBREPASA_MONTO_ANIO";
    public static final String ERR_UT_NO_TIENE_ASIGNADO_MONTO_PARA_ANIO = "ERR_UT_NO_TIENE_ASIGNADO_MONTO_PARA_ANIO";
    public static final String ERR_UT_MONTO_USADO_SOBREPASA_MONTO_UT = "ERR_UT_MONTO_USADO_SOBREPASA_MONTO_UT";
    public static final String ERR_DEBE_USAR_EXACTAMENTE_EL_MISMO_DINERO_QUE_EL_ASIGNADO = "ERR_DEBE_USAR_EXACTAMENTE_EL_MISMO_DINERO_QUE_EL_ASIGNADO";
    public static final String ERR_POA_NO_SE_ENCUENTRA_EN_ESTADO_ENVIADO_SOLO_PUEDE_SER_MODIFICADO_POR_UT = "ERR_POA_NO_SE_ENCUENTRA_EN_ESTADO_ENVIADO_SOLO_PUEDE_SER_MODIFICADO_POR_UT";
    public static final String ERR_POA_YA_FUE_ENVIADO_SOLO_PUEDE_SER_EDITADO_POR_PRESUPUESTO = "ERR_POA_YA_FUE_ENVIADO_SOLO_PUEDE_SER_EDITADO_POR_PRESUPUESTO";
    public static final String ERR_POA_PARA_GENERAR_LINEA_BASE_EL_POA_TIENE_QUE_ENVIARSE_Y_SER_PRESUPUESTO = "ERR_POA_PARA_GENERAR_LINEA_BASE_EL_POA_TIENE_QUE_ENVIARSE_Y_SER_PRESUPUESTO";
    public static final String ERR_POA_PARA_CONSOLIDARSE_TIENE_QUE_ESTAR_EN_ESTADO_DE_CONSOLIDACION = "ERR_POA_PARA_CONSOLIDARSE_TIENE_QUE_ESTAR_EN_ESTADO_DE_CONSOLIDACION";
    public static final String ERR_LA_SUMA_DE_TECHOS_PARA_LA_ACTIVIDAD_SOBREPASA_TECHO_PARA_EL_ANIO = "ERR_LA_SUMA_DE_TECHOS_PARA_LA_ACTIVIDAD_SOBREPASA_TECHO_PARA_EL_ANIO";
    public static final String ERR_POA_NO_SE_ENCUENTRA_GENERADO_PARA_ANIO_SELECCIONADO = "ERR_POA_NO_SE_ENCUENTRA_GENERADO_PARA_ANIO_SELECCIONADO";
    public static final String ERR_NO_SE_PUEDE_DESCERTIFICAR_MONTO_INSUMO_PERTENECIENTE_PRO_ADQ = "ERR_NO_SE_PUEDE_DESCERTIFICAR_MONTO_INSUMO_PERTENECIENTE_PRO_ADQ";
    public static final String ERR_LA_UT_NO_TIENE_MONTO_ASIGNADO_PARA_EL_POA = "ERR_LA_UT_NO_TIENE_MONTO_ASIGNADO_PARA_EL_POA";

    //programa presupuestario
    public static final String ERR_TIENE_ASOCIADO_PROG_ISNTITUCIONAL_CON_DISTITNTA_PELE = "ERR_TIENE_ASOCIADO_PROG_ISNTITUCIONAL_CON_DISTITNTA_PLANIFICACIONE_LINEAE";
    public static final String ERR_PROGRAMA_INSTITUCIONAL_YA_TIENE_ASOCIADO_PROG_PRESUPUESTARIO = "ERR_PROGRAMA_INSTITUCIONAL_YA_TIENE_ASOCIADO_PROG_PRESUPUESTARIO";
    public static final String ERR_PROGRAMA_INSTITUCIONAL_TIENE_ASOCIADA_UNA_PLANIFICACION_ESTRATEGICA_DISTINTA_AL_PRESUPUESTARIO = "ERR_PROGRAMA_INSTITUCIONAL_TIENE_ASOCIADA_UNA_PLANIFICACION_ESTRATEGICA_DISTINTA_AL_PRESUPUESTARIO";
    public static final String ERR_SUMA_DE_TECHOS_DE_SUBPROGRAMA_MAYOR_QUE_LA_DEL_PROGRAMA_0_PARA_ANIO_1 = "ERR_SUMA_DE_TECHOS_DE_SUBPROGRAMA_MAYOR_QUE_LA_DEL_PROGRAMA_0_PARA_ANIO_1";
    public static final String ERR_TECHOS_PROGRAMA_0_ANIO_1_MONTO_2_MAYORQUE_3 = "ERR_TECHOS_PROGRAMA_{0}_ANIO_{1}_MONTO_{2}_MAYORQUE{3}";
    public static final String ERR_YA_EXISTE_UN_TECHO_PARA_DICHA_FUENTE_FINANCIAMIENTO_FUENTE_RECURSO = "ERR_YA_EXISTE_UN_TECHO_PARA_DICHA_FUENTE_FINANCIAMIENTO_FUENTE_RECURSO";
    public static final String ERR_SUMA_DE_TECHOS_DE_PROYECTOS_MAYOR_QUE_LA_DEL_PROGRAMA_0_PARA_ANIO_1 = "ERR_SUMA_DE_TECHOS_DE_PROYECTOS_MAYOR_QUE_LA_DEL_PROGRAMA_0_PARA_ANIO_1";
    public static final String ERR_SUMA_DE_TECHOS_DE_FUENTES_DE_PROYECTO_MAYOR_QUE_PROYECTO_0_PARA_ANIO_1 = "ERR_SUMA_DE_TECHOS_DE_FUENTES_DE_PROYECTO_MAYOR_QUE_PROYECTO_0_PARA_ANIO_1";
    public static final String ERR_DEBE_SELECCIONAR_AL_MENOS_UNA_LINEA_ESTRATEGICA = "ERR_DEBE_SELECCIONAR_AL_MENOS_UNA_LINEA_ESTRATEGICA";
    
    //indicadores
    public static final String ERR_SUPERPONEN_COLORES = "ERR_SUPERPONEN_COLORES";
    public static final String ERR_EXISTE_ASOCIACION_PROGRAMA_INDICADOR = "ERR_EXISTE_ASOCIACION_PROGRAMA_INDICADOR";
    public static final String ERR_VERDE_MAYOR_AMARILLO = "ERR_VERDE_MAYOR_AMARILLO";
    public static final String ERR_AMARILLO_MAYOR_ROJO = "ERR_AMARILLO_MAYOR_ROJO";
    public static final String ERR_COMIENZO_INDICADOR_MAYOR_FIN = "ERR_COMIENZO_INDICADOR_MAYOR_FIN";

    //proyecto
    public static final String ERR_EXISTE_COMPONENTE_CON_UNIDAD_T_QUE_TIENE_SUBCOMPONENTE_CON_UNIDAD_T = "ERR_EXISTE_COMPONENTE_CON_UNIDAD_T_QUE_TIENE_SUBCOMPONENTE_CON_UNIDAD_T";
    public static final String ERR_EXISTE_COMPONENTE_SIN_UNIDAD_T = "ERR_EXISTE_COMPONENTE_SIN_UNIDAD_T";
    public static final String ERR_EXISTE_MACROACTIVIDAD_SIN_UNIDAD_T = "ERR_EXISTE_MACROACTIVIDAD_SIN_UNIDAD_T";
    public static final String ERR_SUMA_MONTOS_SOBREPASA_MONTO_FUETE = "ERR_SUMA_MONTOS_SOBREPASA_MONTO_FUETE";
    public static final String ERR_SUMA_PORCENTAJE_EN_TRAMOS_DE_CATEGORIAS_DISTINTO_100 = "ERR_SUMA_PORCENTAJE_EN_TRAMOS_DE_CATEGORIAS_DISTINTO_100";
    public static final String ERR_FUENTES_NO_SUMAN_MONTO_GLOBAL = "ERR_FUENTES_NO_SUMAN_MONTO_GLOBAL";
    public static final String ERR_FUENTES_NO_MONTO_INSUMO = "ERR_FUENTES_NO_MONTO_INSUMO";
    public static final String ERR_FUENTES_NO_SUMAN_CIEN = "ERR_FUENTES_NO_SUMAN_CIEN";
    public static final String ERR_AL_MENOS_TIENE_QUE_SELECCIONAR_UN_TIPO_ESTRUCTURA = "ERR_AL_MENOS_TIENE_QUE_SELECCIONAR_UN_TIPO_ESTRUCTURA";
    public static final String ERR_NO_PUEDE_CREAR_UN_DOCUEMNTO_VACIO = "ERR_NO_PUEDE_CREAR_UN_DOCUEMNTO_VACIO";
    public static final String ERR_EL_PROYECTO_TIENE_POG_ASOCIADO = "ERR_EL_PROYECTO_TIENE_POG_ASOCIADO";
    public static final String ERR_FECHA_INICIO_MAYOR_QUE_FIN = "ERR_FECHA_INICIO_MAYOR_QUE_FIN";
    public static final String ERR_HAY_DOS_TRAMOS_QUE_FINANCIAN_HASTA_EL_MISMO_MONTO = "ERR_HAY_DOS_TRAMOS_QUE_FINANCIAN_HASTA_EL_MISMO_MONTO";
    public static final String ERR_EN_FUENTE_0_HAY_DOS_TRAMOS_QUE_FINANCIAN_HASTA_EL_MISMO_PORCENTAJE = "ERR_EN_FUENTE_0_HAY_DOS_TRAMOS_QUE_FINANCIAN_HASTA_EL_MISMO_PORCENTAJE";
    public static final String ERR_EN_FUENTE_0_LOS_TRAMOS_NO_FINANCIAN_EL_100_DEL_MONTO = "ERR_EN_FUENTE_0_LOS_TRAMOS_NO_FINANCIAN_EL_100_DEL_MONTO";
    public static final String ERR_EN_FUENTE_0_LOS_TRAMOS_NO_FINANCIAN_EL_TODO_DEL_MONTO = "ERR_EN_FUENTE_0_LOS_TRAMOS_NO_FINANCIAN_EL_TODO_DEL_MONTO";
    public static final String ERR_LA_FUENTE_FINANCIA_MAS_DEL_100_DEL_PROYECTO = "ERR_LA_FUENTE_FINANCIA_MAS_DEL_100_DEL_PROYECTO";
    public static final String ERR_EL_APORTE_0_FINANCIA_MAS_DEL_100_PORCIENTO = "ERR_EL_APORTE_0_FINANCIA_MAS_DEL_100_PORCIENTO";
    public static final String ERR_EL_APORTE_0_FINANCIA_MAS_QUE_EL_APORTE_DE_LA_CATEGORIA = "ERR_EL_APORTE_0_FINANCIA_MAS_QUE_EL_APORTE_DE_LA_CATEGORIA";
    public static final String ERR_COMPONETNES_Y_MACROACTIVIDADES_SOBREPASAN_MONTOS_PARA_LA_FUENTE_0 = "ERR_COMPONETNES_Y_MACROACTIVIDADES_SOBREPASAN_MONTOS_PARA_LA_FUENTE_0";
    public static final String ERR_SOLO_PUEDE_EDITAR_PROYECTO_EN_ESTADO_EN_FORMULACION = "ERR_SOLO_PUEDE_EDITAR_PROYECTO_EN_ESTADO_EN_FORMULACION";
    public static final String ERR_PARA_CERRAR_EL_PROYECTO_LA_DIST_POR_FUENTES_DEBEN_FINCANCIAR_EXACATAMETNE_EL_MONTO_GLOBAL = "ERR_PARA_CERRAR_EL_PROYECTO_LA_DIST_POR_FUENTES_DEBEN_FINCANCIAR_EXACATAMETNE_EL_MONTO_GLOBAL";
    public static final String ERR_LA_SUMA_DE_SUBCOMPONENTES_PARA_EL_COMPONENTE_0_SOBREPASA_EN_LA_FUENTE_1 = "ERR_LA_SUMA_DE_SUBCOMPONENTES_PARA_EL_COMPONENTE_0_SOBREPASA_EN_LA_FUENTE_1";
    public static final String ERR_PARA_CERRAR_EL_PROYECTO_EN_EL_COMPONENTE_0_LA_SUMA_DE_SUBCOMOPNENTES_TIENE_QUE_SER_IGAL_EN_LA_FUENTE_1 = "ERR_PARA_CERRAR_EL_PROYECTO_EN_EL_COMPONENTE_0_LA_SUMA_DE_SUBCOMOPNENTES_TIENE_QUE_SER_IGAL_EN_LA_FUENTE_1";
    public static final String ERR_PARA_CERRAR_EL_PROYECTO_LA_SUMA_DE_COMPONETNES_Y_MACROACTIVIDADES_TIENE_QUE_SER_IGUAL_PARA_LA_FUENTE_0 = "ERR_PARA_CERRAR_EL_PROYECTO_LA_SUMA_DE_COMPONETNES_Y_MACROACTIVIDADES_TIENE_QUE_SER_IGUAL_PARA_LA_FUENTE_0";
    public static final String ERR_SUMA_DE_COMPONENTES_MACROACTIVIDADES_SOBREPASA_MONTO_PROYECTO = "ERR_SUMA_DE_COMPONENTES_MACROACTIVIDADES_SOBREPASA_MONTO_PROYECTO";
    public static final String ERR_LA_SUMA_DE_SUBCOMPONENTES_SOBREPASA_EL_COMPONENTE_0 = "ERR_LA_SUMA_DE_SUBCOMPONENTES_SOBREPASA_EL_COMPONENTE_0";
    public static final String ERR_PARA_CERAR_EL_PROYECTO_LA_SUMA_DE_SUBCOMPONENTES_DEBE_SER_IGAUL_AL_COMPONENTE_0 = "ERR_PARA_CERAR_EL_PROYECTO_LA_SUMA_DE_SUBCOMPONENTES_DEBE_SER_IGAUL_AL_COMPONENTE_0";
    public static final String ERR_PARA_CERRAR_EL_PROYECTO_LA_SUMA_DE_COMPONENTES_Y_MACROACTIVIDADES_DEBE_SER_IGUAL_AL_MONTO_DEL_PROYECTO = "ERR_PARA_CERRAR_EL_PROYECTO_LA_SUMA_DE_COMPONENTES_Y_MACROACTIVIDADES_DEBE_SER_IGUAL_AL_MONTO_DEL_PROYECTO";
    public static final String ERR_PARA_CERRAR_EL_PROYECTO_EN_LA_MACROACTIVIDAD_0_LAS_FUENTES_DEBEN_SUMAR_EL_100 = "ERR_PARA_CERRAR_EL_PROYECTO_EN_LA_MACROACTIVIDAD_0_LAS_FUENTES_DEBEN_SUMAR_EL_100";
    public static final String ERR_PARA_CERRAR_EL_PROYECTO_EN_EL_COMPONENTE_0_LAS_FUENTES_DEBEN_SUMAR_EL_100 = "ERR_PARA_CERRAR_EL_PROYECTO_EN_EL_COMPONENTE_0_LAS_FUENTES_DEBEN_SUMAR_EL_100";
    public static final String ERR_EN_INDICADOR_FIN_DE_TOLERANCIA_VERDE_DEBE_SER_MENOR_A_FIN_TOLERANCIA_AMARILLO = "ERR_EN_INDICADOR_FIN_DE_TOLERANCIA_VERDE_DEBE_SER_MENOR_A_FIN_TOLERANCIA_AMARILLO";
    public static final String ERR_DEBE_GUARDAR_EL_PROYECTO_ANTES_DE_GENERAR_REPORTE = "ERR_DEBE_GUARDAR_EL_PROYECTO_ANTES_DE_GENERAR_REPORTE";
    public static final String ERR_PARA_CERRAR_PROYECTO_ASIGNE_UT_AL_COMPONENTE_0 = "ERR_PARA_CERRAR_PROYECTO_ASIGNE_UT_AL_COMPONENTE_0";
    public static final String ERR_PARA_CERRAR_PROYECTO_ASIGNE_UT_A_LA_MACROACTIVIDAD_0 = "ERR_PARA_CERRAR_PROYECTO_ASIGNE_UT_A_LA_MACROACTIVIDAD_0";
    public static final String ERR_LA_DISTRIBUCION_POR_FUENTES_SUPERA_MONTO_DEL_PROYECTO = "ERR_LA_DISTRIBUCION_POR_FUENTES_SUPERA_MONTO_DEL_PROYECTO";
    public static final String ERR_LA_DISTRIBUCION_POR_CATEGORIAS_SUPERA_MONTO_DEL_PROYECTO = "ERR_LA_DISTRIBUCION_POR_CATEGORIAS_SUPERA_MONTO_DEL_PROYECTO";
    public static final String ERR_LA_DISTRIBUCION_DE_APORTES_SUPERA_MONTO_CATEGORIA_0 = "ERR_LA_DISTRIBUCION_DE_APORTES_SUPERA_MONTO_CATEGORIA_0";
    public static final String ERR_LA_DISTRIBUCION_DE_APORTES_SUPERA_MONTO_PARA_FUENTE_RECURSOS_0 = "ERR_LA_DISTRIBUCION_DE_APORTES_SUPERA_MONTO_PARA_FUENTE_RECURSOS_0";
    public static final String ERR_LA_DISTRIBUCION_DE_APORTES_SUPERA_100_PARA_CATEGORIA_0 = "ERR_LA_DISTRIBUCION_DE_APORTES_SUPERA_100_PARA_CATEGORIA_0";
    public static final String PROYECTO_NO_TIENE_POG_DEBE_CERRARLO = "PROYECTO_NO_TIENE_POG_DEBE_CERRARLO";
    public static final String ERR_PARA_CERRAR_EL_PROYECTO_LA_DIST_POR_CATEGORIA_DEBE_FINANCIAR_EXACATAMETNE_EL_MONTO_GLOBAL = "ERR_PARA_CERRAR_EL_PROYECTO_LA_DIST_POR_CATEGORIA_DEBE_FINANCIAR_EXACATAMETNE_EL_MONTO_GLOBAL";
    public static final String ERR_LA_DISTRIBUCION_DE_APORTES_NO_FINANCIAN_EXACTAMENTE_LA_CATEGORIA_0 = "ERR_LA_DISTRIBUCION_DE_APORTES_NO_FINANCIAN_EXACTAMENTE_LA_CATEGORIA_0";
    public static final String ERR_LA_DISTRIBUCION_DE_APORTES_DISTINTO_DE_100_PARA_LA_CATEGORIA_0 = "ERR_LA_DISTRIBUCION_DE_APORTES_DISTINTO_DE_100_PARA_LA_CATEGORIA_0";
    public static final String ERR_LA_DISTRIBUCION_DE_APORTES_NO_FINANCIA_EXACTAMENTE_FUENTE_RECURSOS_0 = "ERR_LA_DISTRIBUCION_DE_APORTES_NO_FINANCIA_EXACTAMENTE_FUENTE_RECURSOS_0";
    public static final String ERR_EL_APORTE_FINANCIA_MAS_QUE_LA_CATEGORIA = "ERR_EL_APORTE_FINANCIA_MAS_QUE_LA_CATEGORIA";
    public static final String ERR_LA_FUENTE_DE_RECURSOS_0_ESTA_FINANCIANDO_DOS_VECES_EN_EL_PROYECTO = "ERR_LA_FUENTE_DE_RECURSOS_0_ESTA_FINANCIANDO_DOS_VECES_EN_EL_PROYECTO";
    public static final String ERR_EL_PORCENTAJE_DEL_PARIPASSU_EN_LA_CATEGORIA_0_NO_SUMA_CIEN = "ERR_EL_PORCENTAJE_DEL_PARIPASSU_EN_LA_CATEGORIA_0_NO_SUMA_CIEN";
    public static final String ERR_EN_LA_CATEGORIA_0_LOS_TRAMOS_SUPERA_SU_MONTO = "ERR_EN_LA_CATEGORIA_0_LOS_TRAMOS_SUPERA_SU_MONTO";
    public static final String ERR_EN_LA_CATEGORIA_0_SU_DISTRIBUCION_POR_TRAMOS_SUPERA_100 = "ERR_EN_LA_CATEGORIA_0_SU_DISTRIBUCION_POR_TRAMOS_SUPERA_100";
    public static final String ERR_LA_MACROACTICIDAD_0_NO_TIENE_PRODUCTOS = "ERR_LA_MACROACTICIDAD_0_NO_TIENE_PRODUCTOS";
    public static final String ERR_EL_COMPONENTE_0_NO_TIENE_PRODUCTOS = "ERR_EL_COMPONENTE_0_NO_TIENE_PRODUCTOS";
    public static final String ERR_NO_SE_ENCUENTRA_HABILITADO_PLANIFICAICON_PARA_ANIO_0 = "ERR_NO_SE_ENCUENTRA_HABILITADO_PLANIFICAICON_PARA_ANIO_0";
    public static final String ERR_EXISTEN_MOTNOS_QUE_PERTENECEN_A_DISTINTAS_CATEGORIAS_EN_LA_FINANCIACION_DE_LA_ESTRUCTURA = "ERR_EXISTEN_MOTNOS_QUE_PERTENECEN_A_DISTINTAS_CATEGORIAS_EN_LA_FINANCIACION_DE_LA_ESTRUCTURA";
    public static final String ERR_LA_CATEGORIA_0_EL_TRAMO_DE_HASTA_1_TIENE_USADO_2 = "ERR_LA_CATEGORIA_0_EL_TRAMO_DE_HASTA_1_TIENE_USADO_2";
    public static final String ERR_INSUMO_EN_LA_CATEGORIA_0_POR_TRAMOS_NO_TIENE_TRAMO_SELECIONADO = "ERR_INSUMO_EN_LA_CATEGORIA_0_POR_TRAMOS_NO_TIENE_TRAMO_SELECIONADO";
    public static final String ERR_DISTRIBUCCION_POR_FUENTES_SUMA_DISTINTO_MONTO_EN_ESTRUCTURA_0 = "ERR_DISTRIBUCCION_POR_FUENTES_SUMA_DISTINTO_MONTO_EN_ESTRUCTURA_0";
    public static final String ERR_EL_PARA_CERRAR_EL_PROYECTO_ES_NECESARIO_TENER_SUB_PRES_ASOCIADO = "ERR_EL_PARA_CERRAR_EL_PROYECTO_ES_NECESARIO_TENER_SUB_PRES_ASOCIADO";
    public static final String ERR_EL_COMPONENTE_0_TIENE_ASOCIADO_PRODUCTOS_Y_SUBCOMPONENTES_SOLO_SE_ADMITEN_UNO_DE_LOS_DOS = "ERR_EL_COMPONENTE_0_TIENE_ASOCIADO_PRODUCTOS_Y_SUBCOMPONENTES_SOLO_SE_ADMITEN_UNO_DE_LOS_DOS";
    public static final String ERR_NO_EXISTE_EN_EL_POA_LA_LINEA_A_DUPLICAR = "ERR_NO_EXISTE_EN_EL_POA_LA_LINEA_A_DUPLICAR";
    public static final String ERR_NO_SE_ENCUENTRA_CREADO_EL_ANIO_FISCAL_0 = "ERR_NO_SE_ENCUENTRA_CREADO_EL_ANIO_FISCAL_0";
    public static final String ERR_LA_CANTIDAD_DEL_INSUMO_0_DEBE_SER_UN_MONTO_MAYOR_IGUAL_A_CERO = "ERR_LA_CANTIDAD_DEL_INSUMO_0_DEBE_SER_UN_MONTO_MAYOR_IGUAL_A_CERO";
    public static final String ERR_EL_MONTO_UNITARIO_DEL_INSUMO_0_DEBE_SER_UN_MONTO_MAYOR_IGUAL_A_CERO = "ERR_EL_MONTO_UNITARIO_DEL_INSUMO_0_DEBE_SER_UN_MONTO_MAYOR_IGUAL_A_CERO";
    public static final String ERR_EL_MONTO_TOTAL_DEL_INSUMO_0_DEBE_SER_UN_MONTO_MAYOR_IGUAL_A_CERO = "ERR_EL_MONTO_TOTAL_DEL_INSUMO_0_DEBE_SER_UN_MONTO_MAYOR_IGUAL_A_CERO";
    public static final String ERR_EN_EL_INSUMO_0_LAS_FUENTES_NO_SUMAN_SU_MONTO = "ERR_EN_EL_INSUMO_0_LAS_FUENTES_NO_SUMAN_SU_MONTO";
    public static final String ERR_INSUMO_0_EN_LA_CATEGORIA_1_POR_TRAMOS_NO_TIENE_TRAMO_SELECIONADO = "ERR_INSUMO_0_EN_LA_CATEGORIA_1_POR_TRAMOS_NO_TIENE_TRAMO_SELECIONADO";
    public static final String ERR_EL_PORCENTAJE_DEL_PARIPASSU_EN_LA_CATEGORIA_0_DISTINTO_DE_CIEN = "ERR_EL_PORCENTAJE_DEL_PARIPASSU_EN_LA_CATEGORIA_0_DISTINTO_DE_CIEN";
    public static final String ERR_FECHA_DE_PRORROGA_VACIA = "ERR_FECHA_DE_PRORROGA_VACIA";
    public static final String ERR_EXISTE_UN_POA_DE_LA_UT_0_PARA_EL_ANIO_1_CON_DATOS = "ERR_EXISTE_UN_POA_DE_LA_UT_0_PARA_EL_ANIO_1_CON_DATOS";
    public static final String ERR_DEBE_SELECCIONAR_ANIO_FISCAL = "ERR_DEBE_SELECCIONAR_ANIO_FISCAL";
    public static final String ERR_CIERRE_ANUAL_POA_POR_ACTIVIDADES_SIN_FINALIZAR = "ERR_CIERRE_ANUAL_POA_POR_ACTIVIDADES_SIN_FINALIZAR";
    public static final String ERR_CIERRE_ANUAL_POA_POR_INSUMOS_PENDIENTES = "ERR_CIERRE_ANUAL_POA_POR_INSUMOS_PENDIENTES";
    public static final String ERR_CIERRE_ANUAL_ANIO_FISCAL_NO_FINALIZADO = "ERR_CIERRE_ANUAL_ANIO_FISCAL_NO_FINALIZADO";
    public static final String ERR_NO_SE_PUEDE_CERRAR_ANIO_POA_PARA_ANIO_FISCAL_SELECCIONADO = "ERR_NO_SE_PUEDE_CERRAR_ANIO_POA_PARA_ANIO_FISCAL_SELECCIONADO";
    public static final String ERR_DEBE_SELECCIONAR_ANIO_FISCAL_Y_UT = "ERR_DEBE_SELECCIONAR_ANIO_FISCAL_Y_UT";
    public static final String ERR_HAY_POAS_SIN_CONSOLIDAR = "ERR_HAY_POAS_SIN_CONSOLIDAR";
    public static final String ERR_SUMA_MONTOS_FUENTES_MES_1_DIFERENTE_MONTO_INSUMO_MES="ERR_SUMA_MONTOS_FUENTES_MES_1_DIFERENTE_MONTO_INSUMO_MES";
    public static final String ERR_DEBE_INGRESAR_MES_INICIAL_Y_CANTIDAD_MESES="ERR_DEBE_INGRESAR_MES_INICIAL_Y_CANTIDAD_MESES";
    public static final String ERR_CANTIDAD_MESES_INCORRECTA="ERR_CANTIDAD_MESES_INCORRECTA";
    public static final String ERR_MONTO_FUENTE_MES_INCORRECTO="ERR_MONTO_FUENTE_MES_INCORRECTO";
    public static final String ERR_SUMA_MONTOS_FUENTE_1_SUPERA_MONTO_ASIGNADO_A_FUENTE_EN_INSUMO="ERR_SUMA_MONTOS_FUENTE_1_SUPERA_MONTO_ASIGNADO_A_FUENTE_EN_INSUMO";
    public static final String ERR_SUMA_MONTOS_INSUMO_EN_MESES_DIFERENTE_MONTO_INSUMO_TOTAL="ERR_SUMA_MONTOS_INSUMO_EN_MESES_DIFERENTE_MONTO_INSUMO_TOTAL";
    public static final String ERR_MONTO_FUENTE_INCORRECTO = "ERR_MONTO_FUENTE_INCORRECTO";
    public static final String ERR_INSUMO_TIENE_FUENTE_CON_POLIZA_ASOCIADADA = "ERR_INSUMO_TIENE_FUENTE_CON_POLIZA_ASOCIADADA";
    public static final String ERR_CODIGO_DE_INSUMO_NO_EXISTE = "ERR_CODIGO_DE_INSUMO_INGRESADO_NO_ES_VALIDO";

    //techo presupuestario goes
    public static final String ERR_YA_EXISTE_UNIDAD_T_CON_FUENTE_R = "ERR_YA_EXISTE_UNIDAD_T_CON_FUENTE_R";
    public static final String ERR_YA_EXISTE_ANIO_FISCAL_PARA_TECHO_PRESUPUESTARIO = "ERR_YA_EXISTE_ANIO_FISCAL_PARA_TECHO_PRESUPUESTARIO";

    //formulacion por anio fiscal
    public static final String ERR_PRESUPUESTO_NO_CARGO_TECHOS_FUENTE_F_GOES_PARA_ANIO_FISCAL = "ERR_PRESUPUESTO_NO_CARGO_TECHOS_FUENTE_F_GOES_PARA_ANIO_FISCAL";
    public static final String ERR_YA_EXISTE_FORMULACION_PARA_ANIO_FISCAL = "ERR_YA_EXISTE_FORMULACION_PARA_ANIO_FISCAL";

    //pog proyecto
    public static final String ERR_AL_MENOS_DEBE_SELECIONAR_COMPONENTE_O_MACROACTIVIDAD = "ERR_AL_MENOS_DEBE_SELECIONAR_COMPONENTE_O_MACROACTIVIDAD";
    public static final String ERR_EXISTEN_INSUMOS_ASOCIADOS_A_LA_ACTIVIDAD = "ERR_EXISTEN_INSUMOS_ASOCIADOS_A_LA_ACTIVIDAD";
    public static final String ERR_EXISTEN_ACTIVIDADES_ASOCIADAS_A_LA_LINEA = "ERR_EXISTEN_ACTIVIDADES_ASOCIADAS_A_LA_LINEA";
    public static final String ERR_EXISTEN_INDICADORES_ASOCIADOS_A_LA_LINEA = "ERR_EXISTEN_INDICADORES_ASOCIADOS_A_LA_LINEA";
    public static final String ERR_LA_SUMA_DE_MONTOS_SOBREPASA_MONTO_COMPONENTE = "ERR_LA_SUMA_DE_MONTOS_SOBREPASA_MONTO_COMPONENTE";
    public static final String ERR_LA_SUMA_DE_MONTOS_SOBREPASA_MONTO_MACROACTIVIDAD = "ERR_LA_SUMA_DE_MONTOS_SOBREPASA_MONTO_MACROACTIVIDAD";
    public static final String ERR_LA_SUMA_DE_MONTOS_SOBREPASA_MONTOS_FUENTES = "ERR_LA_SUMA_DE_MONTOS_SOBREPASA_MONTOS_FUENTES";
    public static final String ERR_DEBE_SELECIONAR_UN_COMPONENTE_O_UN_MACROACTIVIDAD = "ERR_DEBE_SELECIONAR_UN_COMPONENTE_O_UN_MACROACTIVIDAD";
    public static final String ERR_YA_EXISTE_INDICADOR_EN_CON_SEGUIMIENTO_ASOCIADO = "ERR_YA_EXISTE_INDICADOR_EN_CON_SEGUIMIENTO_ASOCIADO";
    public static final String ERR_POA_PARA_GENERAR_POA_YA_ENVIADO_SOLO_PUEDE_SER_EDITADO_PROY = "ERR_POA_PARA_GENERAR_POA_YA_ENVIADO_SOLO_PUEDE_SER_EDITADO_PROY";
    public static final String ERR_LA_SUMA_DE_MONTOS_DISTINTO_MONTO_ASIGNADO_MACROACTIVIDAD = "ERR_LA_SUMA_DE_MONTOS_DISTINTO_MONTO_ASIGNADO_MACROACTIVIDAD";
    public static final String ERR_LA_SUMA_DE_MONTOS_DISTINTO_MONTO_ASIGNADO_COMPONENTE = "ERR_LA_SUMA_DE_MONTOS_DISTINTO_MONTO_ASIGNADO_COMPONENTE";
    public static final String ERR_LA_FECHA_A_GENERAR_EL_FLUJO_DE_CAJA_MENSUAL_COMPRENDE_ANIOS_DISTINTOS_AL_POA = "ERR_LA_FECHA_A_GENERAR_EL_FLUJO_DE_CAJA_MENSUAL_COMPRENDE_ANIOS_DISTINTOS_AL_POA";
    public static final String ERR_EL_PROYECTO_NO_LLEVA_POG = "ERR_EL_PROYECTO_NO_LLEVA_POG";
    public static final String ERR_PARA_CREAR_POG_EL_PROYECTO_DEBE_ESTAR_BLOQUEADO = "ERR_PARA_CREAR_POG_EL_PROYECTO_DEBE_ESTAR_BLOQUEADO";
    public static final String ERR_EL_PROYECTO_YA_TIENE_POG_ASOCIADO = "ERR_EL_PROYECTO_YA_TIENE_POG_ASOCIADO";
    public static final String ERR_SUMA_DE_MONTOS_DE_INSUMOS_SOBREPASA_MONTO_DEL_PROYECTO = "ERR_SUMA_DE_MONTOS_DE_INSUMOS_SOBREPASA_MONTO_DEL_PROYECTO";
    public static final String ERR_LA_CANTIDAD_DE_PRODUCTOS_EN_EL_POG_ES_MAYOR_QUE_LA_DEL_PROYECTO = "ERR_LA_CANTIDAD_DE_PRODUCTOS_EN_EL_POG_ES_MAYOR_QUE_LA_DEL_PROYECTO";
    public static final String ERR_LA_SUMA_DE_MONTOS_SOBREPASA_MONTOS_FUENTES_0 = "ERR_LA_SUMA_DE_MONTOS_SOBREPASA_MONTOS_FUENTES_0";
    public static final String ERR_LA_SUMA_DE_MONTOS_DE_FUENTE_SOBREPASA_EL_MONTO_TOTAL_DEL_INSUMO = "ERR_LA_SUMA_DE_MONTOS_DE_FUENTE_SOBREPASA_EL_MONTO_TOTAL_DEL_INSUMO";
    public static final String ERR_LA_SUMA_DE_PORCENTAJE_DE_FUENTES_SOBREPASA_EL_100 = "ERR_LA_SUMA_DE_PORCENTAJE_DE_FUENTES_SOBREPASA_EL_100";
    public static final String ERR_EL_POG_NO_SE_ENCUENTRA_EN_UN_ESTADO_EDITABLE_POR_UT = "ERR_EL_POG_NO_SE_ENCUENTRA_EN_UN_ESTADO_EDITABLE_POR_UT";
    public static final String ERR_LA_SUMA_DE_MONTOS_DISTINTO_PARA_FUENTES_0_EN_ESTRUCTURA_1 = "ERR_LA_SUMA_DE_MONTOS_DISTINTO_PARA_FUENTES_0_EN_ESTRUCTURA_1";
    public static final String ERR_LA_SUMA_DE_INSUMOS_0_EN_LA_FUENTE_1_SOBREPASA_EL_MONTO_ASIGNADO_2 = "ERR_LA_SUMA_DE_INSUMOS_0_EN_LA_FUENTE_1_SOBREPASA_EL_MONTO_ASIGNADO_2";
    public static final String ERR_LA_DISTRIBUCION_DE_MONTOS_EN_LA_LINEA_0_SOBREPASA_EL_MONTO_ASIGNADO_PARA_LA_FUENTE_1_USADO_2_TOAL_3 = "ERR_LA_DISTRIBUCION_DE_MONTOS_EN_LA_LINEA_0_SOBREPASA_EL_MONTO_ASIGNADO_PARA_LA_FUENTE_1_USADO_2_TOAL_3";
    public static final String ERR_EN_LA_FUENTE_0_SE_CERTIFICA_POR_MONTO_MAYOR_AL_DE_LA_FUENTE = "ERR_EN_LA_FUENTE_0_SE_CERTIFICA_POR_MONTO_MAYOR_AL_DE_LA_FUENTE";
    public static final String ERR_EL_CERTIFICADO_DE_DISPONIBILIDAD_PRESUPUESTARIA_YA_FUE_APROBADO = "ERR_EL_CERTIFICADO_DE_DISPONIBILIDAD_PRESUPUESTARIA_YA_FUE_APROBADO";
    public static final String ERR_ANIO_CONTRATACION_DE_INSUMO_DINSTINTO_POA = "ERR_ANIO_CONTRATACION_DE_INSUMO_DINSTINTO_POA";
    public static final String ERR_LA_SUMA_DE_MONTOS_DE_FUENTE_DISTINTO_EL_MONTO_TOTAL_DEL_INSUMO = "ERR_LA_SUMA_DE_MONTOS_DE_FUENTE_DISTINTO_EL_MONTO_TOTAL_DEL_INSUMO";
    public static final String ERR_EN_INSUMO_0_LA_FUENTE_1_SE_CERTIFICA_POR_MONTO_MAYOR_AL_DE_LA_FUENTE = "ERR_EN_INSUMO_0_LA_FUENTE_1_SE_CERTIFICA_POR_MONTO_MAYOR_AL_DE_LA_FUENTE";
    public static final String ERR_EN_INSUMO_0_LA_DISTRIBUCION_POR_ANIOS_SUPERA_A_LA_CANTIDAD_ESTABLECIDA_EN_EL_INSUMO = "ERR_EN_INSUMO_0_LA_DISTRIBUCION_POR_ANIOS_SUPERA_A_LA_CANTIDAD_ESTABLECIDA_EN_EL_INSUMO";
    public static final String ERR_AL_MENOS_DEBE_SELECCIONAR_UN_MONTO = "ERR_AL_MENOS_DEBE_SELECCIONAR_UN_MONTO";
    public static final String ERR_AL_MENOS_DEBE_HABER_UN_MONTO_VALIDADO = "ERR_AL_MENOS_DEBE_HABER_UN_MONTO_VALIDADO";
    public static final String ERR_DEBE_INGRESAR_MONTO_CERTIFICADO_PARA_FUENTES_SELECCIONADAS = "ERR_DEBE_INGRESAR_MONTO_CERTIFICADO_PARA_FUENTES_SELECCIONADAS";
    public static final String ERR_UNA_FEUNTE_EN_EL_CERTIFICADO_YA_ESTA_APROBADA = "ERR_UNA_FEUNTE_EN_EL_CERTIFICADO_YA_ESTA_APROBADA";
    public static final String ERR_PARA_ENVIAR_A_VALIDAR_AL_MENOS_DEBE_SELECCIONAR_UN_MONTO = "ERR_PARA_ENVIAR_A_VALIDAR_AL_MENOS_DEBE_SELECCIONAR_UN_MONTO";
    public static final String ERR_SUMA_MONTOS_FUENTES_POG_EN_INSUMO_0_SUPERA_MONTO_TOTAL_INSUMO_POG = "ERR_SUMA_MONTOS_FUENTES_POG_EN_INSUMO_0_SUPERA_MONTO_TOTAL_INSUMO_POG";
    public static final String ERR_EN_INSUMO_0_LA_DISTRIBUCION_POR_ANIOS_DISTINTO_A_LA_CANTIDAD_ESTABLECIDA_EN_EL_INSUMO = "ERR_EN_INSUMO_0_LA_DISTRIBUCION_POR_ANIOS_DISTINTO_A_LA_CANTIDAD_ESTABLECIDA_EN_EL_INSUMO";
    public static final String ERR_SUMA_MONTOS_FUENTES_POG_EN_INSUMO_0_DISTINTO_MONTO_TOTAL_INSUMO_POG = "ERR_SUMA_MONTOS_FUENTES_POG_EN_INSUMO_0_DISTINTO_MONTO_TOTAL_INSUMO_POG";
    public static final String ERR_LA_SUMA_DE_MONTOS_DE_LA_FUENTE_0_1_EN_LA_DISTRIBUCION_POR_ANIOS_ES_DISTINTO_AL_TOTAL_EN_LOS_INSUMOS_2 = "ERR_LA_SUMA_DE_MONTOS_DE_LA_FUENTE_0_1_EN_LA_DISTRIBUCION_POR_ANIOS_ES_DISTINTO_AL_TOTAL_EN_LOS_INSUMOS_2";
    public static final String ERR_LA_SUMA_DE_MONTOS_DE_LA_FUENTE_0_1_EN_LA_DISTRIBUCION_POR_ANIOS_ES_MAYOR_AL_TOTAL_EN_LOS_INSUMOS_2 = "ERR_LA_SUMA_DE_MONTOS_DE_LA_FUENTE_0_1_EN_LA_DISTRIBUCION_POR_ANIOS_ES_MAYOR_AL_TOTAL_EN_LOS_INSUMOS_2";
    
    //plantilla de insumos
    public static final String ERR_ELIMINE_LOS_GRUPOS_HIJOS_ANTES_DE_ELIMINAR_GRUPO = "ERR_ELIMINE_LOS_GRUPOS_HIJOS_ANTES_DE_ELIMINAR_GRUPO";
    public static final String ERR_DESASOCIE_LOS_INSUMOS_ANTES_DE_ELIMINAR_GRUPO = "ERR_DESASOCIE_LOS_INSUMOS_ANTES_DE_ELIMINAR_GRUPO";
    public static final String ERR_DEBE_SELECCIONAR_UN_INSUMO = "ERR_DEBE_SELECCIONAR_UN_INSUMO";
    public static final String ERR_DEBE_SELECCIONAR_UN_INSUMO_EN_ARBOL_ONU = "ERR_DEBE_SELECCIONAR_UN_INSUMO_EN_ARBOL_ONU";
    public static final String ERR_DEBE_SELECCIONAR_EL_GRUPO_EN_EN_PLANTILLA = "ERR_DEBE_SELECCIONAR_EL_GRUPO_EN_EN_PLANTILLA";
    public static final String ERR_SOLO_PUEDEN_MOVERSE_INSUMOS = "ERR_SOLO_PUEDEN_MOVERSE_INSUMOS";
    public static final String ERR_DEBE_SELECCIONAR_UN_GRUPO_DESTINO = "ERR_DEBE_SELECCIONAR_UN_GRUPO_DESTINO";

    //PAC
    public static final String ERR_EL_GRUPO_NO_SE_ENCUENTRA_EN_FORMULACION = "ERR_EL_GRUPO_NO_SE_ENCUENTRA_EN_FORMULACION";
    public static final String ERR_EL_GRUPO_CONTIENE_INSUMOS = "ERR_EL_GRUPO_CONTIENE_INSUMOS";
    public static final String ERR_EL_GRUPO_SE_ENCUENTRA_CERRADO = "ERR_EL_GRUPO_SE_ENCUENTRA_CERRADO";
    public static final String ERR_DEBE_SELECCIONAR_UN_GRUPO = "ERR_DEBE_SELECCIONAR_UN_GRUPO";
    public static final String ERR_AL_MENOS_DEBE_SELECCIONAR_UN_INSUMO = "ERR_AL_MENOS_DEBE_SELECCIONAR_UN_INSUMO";
    public static final String ERR_PARA_GUARDAR_UN_PAC_CON_ESTADO_CERRADO_TODOS_SUS_GRUPOS_TIENEN_QUE_ESTAR_CERRADOS = "ERR_PARA_GUARDAR_UN_PAC_CON_ESTADO_CERRADO_TODOS_SUS_GRUPOS_TIENEN_QUE_ESTAR_CERRADOS";
    public static final String ERR_PARA_GUARDAR_UN_PAC_CON_ESTADO_CERRADO_TODOS_SUS_INSUMOS_TIENEN_QUE_TENER_GRUPO = "ERR_PARA_GUARDAR_UN_PAC_CON_ESTADO_CERRADO_TODOS_SUS_INSUMOS_TIENEN_QUE_TENER_GRUPO";
    public static final String ERR_LOS_PAC_SE_ENCUENTRAN_CERRADOS_NO_PUEDE_MODIFICARSE = "ERR_LOS_PAC_SE_ENCUENTRAN_CERRADOS_NO_PUEDE_MODIFICARSE";
    public static final String ERR_NO_SE_ENCUENTRAN_BLOQUEADOS_LOS_PAC_PARA_EL_ANIO = "ERR_NO_SE_ENCUENTRAN_BLOQUEADOS_LOS_PAC_PARA_EL_ANIO";
    public static final String ERR_EXISTEN_GRUPOS_DE_PAC_SIN_CARGA_DE_FCM = "ERR_EXISTEN_GRUPOS_DE_PAC_SIN_CARGA_DE_FCM";
    public static final String ERR_NO_SE_ENCUENTRAN_BLOQUEADOS_LOS_FCM_PARA_EL_ANIO = "ERR_NO_SE_ENCUENTRAN_BLOQUEADOS_LOS_FCM_PARA_EL_ANIO";
    public static final String ERR_PARA_CERRAR_GRUPO_EL_GRUPO_NECESITA_NOMBRE = "ERR_PARA_CERRAR_GRUPO_EL_GRUPO_NECESITA_NOMBRE";
    public static final String ERR_PARA_CERRAR_GRUPO_NECESITA_METODO_ADQUISICION = "ERR_PARA_CERRAR_GRUPO_NECESITA_METODO_ADQUISICION";
    public static final String ERR_EL_MONTO_DEL_GRUPO_NO_CUMPLE_CON_LOS_RANGOS_DEL_METODO_SELECIONADO = "ERR_EL_MONTO_DEL_GRUPO_NO_CUMPLE_CON_LOS_RANGOS_DEL_METODO_SELECIONADO";
    public static final String ERR_EL_GRUPO_NO_SE_PUEDE_ABRIR_MIENTRAS_PAC_CERRADO = "ERR_EL_GRUPO_NO_SE_PUEDE_ABRIR_MIENTRAS_PAC_CERRADO";
    public static final String ERR_DEBE_SELECIONAR_METODO_ADQ = "ERR_DEBE_SELECIONAR_METODO_ADQ";
    public static final String ERR_MONTOS_INGRESADOS_EN_FLUJO_CAJA_EXCEDEN_MONTO_TOTAL_INSUMO = "ERR_MONTOS_INGRESADOS_EN_FLUJO_CAJA_EXCEDEN_MONTO_TOTAL_INSUMO";
    public static final String ERR_MONTOS_INGRESADOS_EN_FLUJO_CAJA_DISTINTO_MONTO_TOTAL_INSUMO = "ERR_MONTOS_INGRESADOS_EN_FLUJO_CAJA_DISTINTO_MONTO_TOTAL_INSUMO";
    public static final String ERR_EN_EL_INSUMO_0_SU_MONTO_TOTAL_ES_DE_1_Y_ES_DISTINTO_AL_FLUJO_DE_CAJA_2 = "ERR_EN_EL_INSUMO_0_SU_MONTO_TOTAL_ES_DE_1_Y_ES_DISTINTO_AL_FLUJO_DE_CAJA_2";

    public static final String ERR_ANIOS_EN_FLUJO_CAJA_DUPLICADOS = "ERR_ANIOS_EN_FLUJO_CAJA_DUPLICADOS";
    public static final String ERR_EN_EL_INSUMO_0_EL_ANIO_1_ESTA_DUPLICADO = "ERR_EN_EL_INSUMO_0_EL_ANIO_1_ESTA_DUPLICADO";

    public static final String ERR_MONTOS_INGRESADOS_EN_FLUJO_CAJA_EXCEDEN_MONTO_TOTAL_GRUPO = "ERR_MONTOS_INGRESADOS_EN_FLUJO_CAJA_EXCEDEN_MONTO_TOTAL_GRUPO";
    public static final String ERR_MONTO_GENERADO_AUTO_DISTINTO_TOTAL_GRUPO = "ERR_MONTO_GENERADO_AUTO_DISTINTO_TOTAL_GRUPO";
    public static final String ERR_DEBE_SELECIONAR_UN_PAC = "ERR_DEBE_SELECIONAR_UN_PAC";
    public static final String ERR_NUMERO_PAC_INCORRECTO = "ERR_NUMERO_PAC_INCORRECTO";
    public static final String ERR_ANIO_FISCAL_YA_AGREGADO = "ERR_ANIO_FISCAL_YA_AGREGADO";
    public static final String ERR_MONTOS_INGRESADOS_DISTINTOS_MONTO_TOTAL_GRUPO = "ERR_MONTOS_INGRESADOS_DISTINTOS_MONTO_TOTAL_GRUPO";

    //Metodo de Adquisición
    public static final String ERR_NOMBRE_ADQUISICION_VACIO = "ERR_NOMBRE_ADQUISICION_VACIO";
    public static final String ERR_NOMBRE_ADQUISICION_TAREA_VACIO = "ERR_NOMBRE_ADQUISICION_TAREA_VACIO";

    public static final String ERR_ADQUISICION_TAREA_ENTREGA_TDR = "ERR_ADQUISICION_TAREA_ENTREGA_TDR";
    public static final String ERR_ADQUISICION_TAREA_INICIO_CONTRATACION = "ERR_ADQUISICION_TAREA_INICIO_CONTRATACION";
    public static final String ERR_ADQUISICION_TAREA_DURACION_DIAS = "ERR_ADQUISICION_TAREA_DURACION_DIAS";
    public static final String ERR_ADQUISICION_TAREA_INICIO_DIAS = "ERR_ADQUISICION_TAREA_INICIO_DIAS";
    public static final String ERR_NOMBRE_ADQUISICION_CANT_TAREAS = "ERR_NOMBRE_ADQUISICION_CANT_TAREAS";
    public static final String ERR_ADQUISICION_RANGO_ANIO_EXISTE = "ERR_ADQUISICION_RANGO_ANIO_EXISTE";
    public static final String ERR_ADQUISICION_RANGO_MONTO_MAX = "ERR_ADQUISICION_RANGO_MONTO_MAX";
    public static final String ERR_ADQUISICION_RANGO_MONTO_MIN = "ERR_ADQUISICION_RANGO_MONTO_MIN";
    public static final String ERR_ADQUISICION_RANGO_ANIO = "ERR_ADQUISICION_RANGO_ANIO";
    public static final String ERR_ADQUISICION_RANGO_MONTO_MAXIMO_MENOR_IGUAL_MONTO_MINIMO = "ERR_ADQUISICION_RANGO_MONTO_MAXIMO_MENOR_IGUAL_MONTO_MINIMO";
    public static final String ERR_ADQUISICION_NORMATIVA_VACIA = "ERR_ADQUISICION_NORMATIVA_VACIA";
    public static final String ERR_ADQUISICION_RANGOS_DELETE = "ERR_ADQUISICION_RANGOS_DELETE";
    public static final String ERR_ADQUISICION_TAREAS_DELETE = "ERR_ADQUISICION_TAREAS_DELETE";
    public static final String ERR_ADQUISICION_TAREA_ENTREGATDR_INICIO_CONTRATACION = "ERR_ADQUISICION_TAREA_ENTREGATDR_INICIO_CONTRATACION";
    public static final String ERR_ADQUISICION_TAREA_DELETE_PREDECESORA = "ERR_ADQUISICION_TAREA_DELETE_PREDECESORA";
    public static final String ERR_ADQUISICION_TAREA_PREDECESORA_DE_SI_MISMA = "ERR_ADQUISICION_TAREA_PREDECESORA_DE_SI_MISMA";
    public static final String ERR_ADQUISICION_TAREA_INICIO_DIAS_INCORRECTO = "ERR_ADQUISICION_TAREA_INICIO_DIAS_INCORRECTO";
    public static final String ERR_ADQUISICION_RANGO_ANIO_INVALIDO = "ERR_ADQUISICION_RANGO_ANIO_INVALIDO";
    public static final String ERR_ADQUISICION_DELETE_PACS_ASOCIADOS = "ERR_ADQUISICION_DELETE_PACS_ASOCIADOS";
    public static final String ADVERTENCIA_ADQUISICION_DEHABILITAR = "ADVERTENCIA_ADQUISICION_DEHABILITAR";
    public static final String ERR_ADQUISICION_RANGO_EXISTE_PAC_DERIVADO_POA_ANIO_NO_CERRADO = "ERR_ADQUISICION_RANGO_EXISTE_PAC_DERIVADO_POA_ANIO_NO_CERRADO";
    public static final String ERR_DEBE_SELECCIONAR_UN_ITEM = "ERR_DEBE_SELECCIONAR_UN_ITEM";
    public static final String ERR_DEBE_INGRESAR_NOMBRE_LOTE = "ERR_DEBE_INGRESAR_NOMBRE_LOTE";
    public static final String ERR_DEBE_INGRESAR_NOMBRE_ITEM = "ERR_DEBE_INGRESAR_NOMBRE_ITEM";
    public static final String ERR_DEBE_SELECCIONAR_UN_LOTE = "ERR_DEBE_SELECCIONAR_UN_LOTE";
    public static final String ERR_DEBE_SELECCIONAR_UN_LOTE_O_ITEM = "ERR_DEBE_SELECCIONAR_UN_LOTE_O_ITEM";
    public static final String ERR_NO_SELECCIONO_UN_LOTE_DEBE_SELECCIONAR_UN_LOTE = "ERR_NO_SELECCIONO_UN_LOTE_DEBE_SELECCIONAR_UN_LOTE";
    public static final String ERR_YA_EXISTE_NOMBRE_ITEM = "ERR_YA_EXISTE_NOMBRE_ITEM";
    public static final String ERR_AL_MENOS_DEBE_SELECCIONAR_UN_ITEM = "ERR_AL_MENOS_DEBE_SELECCIONAR_UN_ITEM";
    public static final String ERR_YA_EXISTE_NOMBRE_LOTE = "ERR_YA_EXISTE_NOMBRE_LOTE";
    public static final String ERR_ITEM_NO_TIENE_INSUMOS = "ERR_ITEM_NO_TIENE_INSUMOS";
    public static final String ERR_LOTE_SIN_ITEMS = "ERR_LOTE_SIN_ITEMS";
    public static final String ERR_DEBE_SELECCIONAR_UN_SOLO_ITEM = "ERR_DEBE_SELECCIONAR_UN_SOLO_ITEM";
    public static final String ERR_NO_SELECCIONO_UN_ITEM_DEBE_SELECCIONAR_UN_ITEM = "ERR_NO_SELECCIONO_UN_ITEM_DEBE_SELECCIONAR_UN_ITEM";
    public static final String ERR_DEBE_SELECCIONAR_PROVEEDOR_A_AGREGAR = "ERR_DEBE_SELECCIONAR_PROVEEDOR";
    public static final String ERR_PROVEEDOR_YA_ESTABA_AGREGADO = "ERR_PROVEEDOR_YA_ESTABA_AGREGADO";
    public static final String ERR_PROVEEDORES_YA_ESTABAN_AGREGADOS = "ERR_PROVEEDORES_YA_ESTABAN_AGREGADOS";
    public static final String ERR_ALGUNOS_PROVEEDORES_NO_SE_AGREGARON_PORQUE_YA_ESTABAN_AGREGADOS = "ERR_ALGUNOS_PROVEEDORES_NO_SE_AGREGARON_PORQUE_YA_ESTABAN_AGREGADOS";
    public static final String ERR_DEBE_SELECCIONAR_PROVEEDOR_A_BORRAR = "ERR_DEBE_SELECCIONAR_PROVEEDOR_A_BORRAR";
    public static final String ERR_DEBE_SELECCIONAR_PROVEEDOR = "ERR_DEBE_SELECCIONAR_PROVEEDOR";
    public static final String ERR_DEBE_SELECCIONAR_OFERTAS_A_BORRAR = "ERR_DEBE_SELECCIONAR_OFERTAS_A_BORRAR";
    public static final String ERR_MONTOS_ASIGNADOS_PARA_INSUMOS_MENOR_A_PRECIO_PROVEEDOR = "ERR_MONTOS_ASIGNADOS_PARA_INSUMOS_MENOR_A_PRECIO_PROVEEDOR";
    public static final String ERR_ALCANZA_PRESUPUESTO_ASIGNADO = "ERR_ALCANZA_PRESUPUESTO_ASIGNADO";
    public static final String ERR_PROVEEDOR_YA_INGRESADO = "ERR_PROVEEDOR_YA_INGRESADO";
    public static final String ERR_DEBE_SELECCIONAR_UN_PROVEEDOR = "ERR_DEBE_SELECCIONAR_UN_PROVEEDOR";
    public static final String ERR_PRESUP_PROC_INCOMPATIBLE_PRESUP_MET = "ERR_PRESUP_PROC_INCOMPATIBLE_PRESUP_MET";
    public static final String ERR_NO_SE_PUEDE_ELIMINAR_PROVEEDOR_INVITADO = "ERR_NO_SE_PUEDE_ELIMINAR_PROVEEDOR_INVITADO";
    public static final String ERR_PROC_DESIERTO = "ERR_PROC_DESIERTO";
    public static final String ERR_PROC_SIN_EFECTO = "ERR_PROC_SIN_EFECTO";
    public static final String ERR_PROCESO_ADQ_SIN_RESPONSABLE_ASIGNADO = "ERR_PROCESO_ADQ_SIN_RESPONSABLE_ASIGNADO";
    public static final String ERR_TECNICO_UACI_SELECCIONADO_DIFERENTE_USUARIO_ACTUAL = "ERR_TECNICO_UACI_SELECCIONADO_DIFERENTE_USUARIO_ACTUAL";
    public static final String ERR_MONTO_TOTAL_ASIGNADO_PARA_INSUMOS_DISTINTO_A_PRECIO_TOTAL_PROVEEDOR = "ERR_MONTO_TOTAL_ASIGNADO_PARA_INSUMOS_DISTINTO_A_PRECIO_TOTAL_PROVEEDOR";
    public static final String ERR_DEBE_INGRESAR_FECHA_INICIO_GANTT = "ERR_DEBE_INGRESAR_FECHA_INICIO_GANTT";
    public static final String ERR_DEBE_INGRESAR_METODO_ADQ = "ERR_DEBE_INGRESAR_METODO_ADQ";
    public static final String ERR_DEBE_INGRESAR_AÑO_FISCAL = "ERR_DEBE_INGRESAR_AÑO_FISCAL";
    public static final String ERR_DEBE_INGRESAR_NOMBRE_PROCESO_ADQUISICION = "ERR_DEBE_INGRESAR_NOMBRE_PROCESO_ADQUISICION";
    public static final String ERR_DEBE_INGRESAR_TECNICO_UACI = "ERR_DEBE_INGRESAR_TECNICO_UACI";
    public static final String ERROR_NUMERO_PAC_INAVLIDO = "ERROR_NUMERO_PAC_INAVLIDO";
    public static final String ERROR_NUMERO_INAVLIDO = "ERROR_NUMERO_INAVLIDO";
    public static final String ERROR_ID_OFERENTE_INVALIDO = "ERROR_ID_OFERENTE_INVALIDO";

    //tdr
    public static final String ERR_TDR_VACIO_AL_MENOS_ESCRIBA_TEXTO_O_SELECCIONE_ARCHIVO = "ERR_TDR_VACIO_AL_MENOS_ESCRIBA_TEXTO_O_SELECCIONE_ARCHIVO";
    public static final String ADV_PRECIO_PROVEEDOR_SUPERA_PRESUPUESTOS_ASIGNADOS = "ADV_PRECIO_PROVEEDOR_SUPERA_PRESUPUESTOS_ASIGNADOS";
    public static final String ERR_ITEMS_SIN_DEFINICION_O_EN_PAUSA = "ERR_ITEMS_SIN_DEFINICION_O_EN_PAUSA";
    public static final String ERR_NO_EXISTEN_ITEMS_ASOCIADOS = "ERR_NO_EXISTEN_ITEMS_ASOCIADOS";
    public static final String ERROR_PLAZO_PAUZA_ITEM_NO_EXISTE = "ERROR_PLAZO_PAUZA_ITEM_NO_EXISTE";
    public static final String ERR_DEBE_CANTIDAD_NROS_A_RESERVAR = "ERR_DEBE_CANTIDAD_NROS_A_RESERVAR";
    public static final String ERR_CONTRATO_ADMINISTRADOR_VACIO = "ERR_CONTRATO_ADMINISTRADOR_VACIO";
    public static final String ERR_CONTRATO_NRO_VACIO = "ERR_CONTRATO_NRO_VACIO";
    public static final String ERR_CARGUE_LAS_FECHAS_DEL_CONTRATO_ANTES_DE_CARGAR_PROG_DE_PAGOS = "ERR_CARGUE_LAS_FECHAS_DEL_CONTRATO_ANTES_DE_CARGAR_PROG_DE_PAGOS";
    public static final String ERR_CONTRATO_FECHA_INICIO_VACIA = "ERR_CONTRATO_FECHA_INICIO_VACIA";
    public static final String ERR_CONTRATO_FECHA_FIN_VACIA = "ERR_CONTRATO_FECHA_FIN_VACIA";
    public static final String ERR_CONTRATO_DEBE_INGRESAR_MONTO_ADJUDICADO = "ERR_CONTRATO_DEBE_INGRESAR_MONTO_ADJUDICADO";
    public static final String ERR_FECHA_DE_INICIO_MAS_PLAZO_EN_DIAS_NO_COINCIDE_CON_FECHA_FIN = "ERR_FECHA_DE_INICIO_MAS_PLAZO_EN_DIAS_NO_COINCIDE_CON_FECHA_FIN";
    public static final String ERR_CONTRATO_FECHA_INICIO_MAYOR_A_FECHA_FIN = "ERR_CONTRATO_FECHA_INICIO_MAYOR_A_FECHA_FIN";
    public static final String ERROR_REPORTE_NO_ENCONTRADO = "ERROR_REPORTE_NO_ENCONTRADO";
    public static final String ERR_PARA_EMITIR_QUEDAN_MONTOTOTAL_FACTURAS_0_DEBE_COINCIDIR_CON_MONTO_ACTA_1 = "ERR_PARA_EMITIR_QUEDAN_MONTOTOTAL_FACTURAS_0_DEBE_COINCIDIR_CON_MONTO_ACTA_1";
    public static final String ERROR_REPORTE_GENERANDO = "ERROR_REPORTE_GENERANDO";
    public static final String ERR_PROCESO_ADQ_METODO_ADQ_VACIO = "ERR_PROCESO_ADQ_METODO_ADQ_VACIO";
    public static final String ERR_EL_INSUMO_0_NO_TINE_ARCHIVO_CERTIFICADO_DISP_CARGADO = "ERR_EL_INSUMO_0_NO_TINE_ARCHIVO_CERTIFICADO_DISP_CARGADO";
    public static final String ERR_INSUMOS_SIN_ITEM = "ERR_INSUMOS_SIN_ITEM";
    public static final String ERR_PROCESO_DEBE_TENER_AL_MENOS_TRES_INVITADOS = "ERR_PROCESO_DEBE_TENER_AL_MENOS_TRES_INVITADOS";
    public static final String ERR_INSUMO_SIN_TDR_ET = "ERR_INSUMO_SIN_TDR_ET";
    public static final String ERR_INSUMO_SIN_RECEPCION_TDR_ET = "ERR_INSUMO_SIN_RECEPCION_TDR_ET";
    public static final String ERR_INSUMO_SIN_CERT_DISP_VALIDADO = "ERR_INSUMO_SIN_CERT_DISP_VALIDADO";
    public static final String ERR_INSUMO_SIN_CERT_DISP = "ERR_INSUMO_SIN_CERT_DISP";
    public static final String ERR_PROCESO_DEBE_TENER_AL_MENOS_UN_PROVEEDOR = "ERR_PROCESO_DEBE_TENER_AL_MENOS_UN_PROVEEDOR";
    public static final String ERR_ITEMS_EN_PAUSA_O_SIN_DEFINICION = "ERR_ITEMS_EN_PAUSA_O_SIN_DEFINICION";
    public static final String ERR_ITEMS_SIN_DEFINICION = "ERR_ITEMS_SIN_DEFINICION";
    public static final String ERR_PROCESO_ESTADO_INVALIDO = "ERR_PROCESO_ESTADO_INVALIDO";
    public static final String ERR_PROCESO_SIN_TDR = "ERR_PROCESO_SIN_TDR";
    public static final String ERR_PROCESO_ITEM_SIN_TDR = "ERR_PROCESO_ITEM_SIN_TDR";
    public static final String ERR_DEBE_AGREGAR_MONTO_OFERTA_PARA_TODOS_LOS_INSUMOS = "ERR_DEBE_AGREGAR_MONTO_OFERTA_PARA_TODOS_LOS_INSUMOS";
    public static final String ERR_DEBE_AGREGAR_CANTIDAD_OFERTA_PARA_TODOS_LOS_INSUMOS = "ERR_DEBE_AGREGAR_CANTIDAD_OFERTA_PARA_TODOS_LOS_INSUMOS";
    public static final String ERROR_PLAZO_PAUZA_ITEM_NO_ES_NUMERICO = "ERROR_PLAZO_PAUZA_ITEM_NO_ES_NUMERICO";
    public static final String ERR_PROCESO_CONTRATOS_SIN_ORDEN_INICIO = "ERR_PROCESO_CONTRATOS_SIN_ORDEN_INICIO";
    public static final String ERR_ITEM_TIENE_OFERTAS_ASOCIADAS = "ERR_ITEM_TIENE_OFERTAS_ASOCIADAS";
    public static final String ERR_ITEM_LOTE_TIENE_OFERTAS_ASOCIADAS = "ERR_ITEM_LOTE_TIENE_OFERTAS_ASOCIADAS";
    public static final String ADV_METODO_ADQUISICION_NO_VALIDO_PARA_NUEVOS_MONTOS = "ADV_METODO_ADQUISICION_NO_VALIDO_PARA_NUEVOS_MONTOS";
    public static final String ERR_PROCESO_DEBE_TENER_AL_MENOS_UN_INVITADO = "ERR_PROCESO_DEBE_TENER_AL_MENOS_UN_INVITADO";
    public static final String ERR_NO_SE_PERMITE_INSUMOS_DISTINTO_TIPO_EN_ITEM = "ERR_NO_SE_PERMITE_INSUMOS_DISTINTO_TIPO_EN_ITEM";
    public static final String ERR_EL_INSUMO_YA_ESTA_ASIGNADO_AL_ITEM = "ERR_EL_INSUMO_YA_ESTA_ASIGNADO_AL_ITEM";
    public static final String ERR_CANTIDAD_ACTUAL_INSUMO_DEBE_SER_MAYOR_CANTIDAD_SOLICITAR = "ERR_CANTIDAD_ACTUAL_INSUMO_DEBE_SER_MAYOR_CANTIDAD_SOLICITAR";
    public static final String ERR_CANTIDAD_ACTUAL_INSUMO_DEBE_SER_MAYOR_IGUAL_CANTIDAD_UTILIZAR = "ERR_CANTIDAD_ACTUAL_INSUMO_DEBE_SER_MAYOR_IGUAL_CANTIDAD_UTILIZAR";
    public static final String ERR_CANTIDAD_UTILIZAR_INSUMO_DEBE_SER_MAYOR_0 = "ERR_CANTIDAD_UTILIZAR_INSUMO_DEBE_SER_MAYOR_0";
    public static final String ERROR_NO_HAY_OFERTAS_POR_INSUMOS = "ERROR_NO_HAY_OFERTAS_POR_INSUMOS";
    public static final String ERROR_DEBE_ASOCIAR_PROVEEDOR_OFERTA = "ERROR_DEBE_ASOCIAR_PROVEEDOR_OFERTA";
    public static final String ERROR_DEBE_AGREGAR_PRECIO_UNITARIO = "ERROR_DEBE_AGREGAR_PRECIO_UNITARIO";
    public static final String ERR_DEBE_INGRESAR_NRO_ITEM = "ERR_DEBE_INGRESAR_NRO_ITEM";
    public static final String ERR_NRO_ITEM_INVALIDO = "ERR_NRO_ITEM_INVALIDO";
    public static final String ERR_YA_EXISTE_NRO_ITEM = "ERR_YA_EXISTE_NRO_ITEM";
    public static final String ERR_INSUMO_DE_ITEM_ASOCIADO_OTRO_PROCESO = "ERR_INSUMO_DE_ITEM_ASOCIADO_OTRO_PROCESO";
    public static final String ERR_CONTRATO_TIENE_ORDEN_INICIO = "ERR_CONTRATO_TIENE_ORDEN_INICIO";
    public static final String ERR_EXITE_CONTRATO_ASOCIADO_AL_ITEM = "ERR_EXITE_CONTRATO_ASOCIADO_AL_ITEM";
    public static final String ERR_ITEM_SIN_OFERTAS = "ERR_ITEM_SIN_OFERTAS";
    public static final String ERR_HAY_INSUMOS_NO_SE_PUEDEN_COMPRAR = "ERR_HAY_INSUMOS_NO_SE_PUEDEN_COMPRAR";
    public static final String ERR_CANTIDAD_DEBE_SER_IGUAL_AL_INSUMO = "ERR_CANTIDAD_DEBE_SER_IGUAL_AL_INSUMO";
    public static final String ERR_CANTIDAD_INSUMO_MENOR_QUE_1 = "ERR_CANTIDAD_INSUMO_MENOR_QUE_1";
    public static final String ERR_NO_SE_PUEDE_EDITAR_CANTIDAD_POR_ESTADO_ITEM = "ERR_NO_SE_PUEDE_EDITAR_CANTIDAD_POR_ESTADO_ITEM";
    public static final String ERR_NO_HAY_CONTRATOS_GENERADOS = "ERR_NO_HAY_CONTRATOS_GENERADOS";
    public static final String ERR_HAY_CONTRATOS_SIN_GENERAR = "ERR_HAY_CONTRATOS_SIN_GENERAR";
    public static final String ERR_PROC_YA_EXISTE_POR_NOMBRE_ANIO = "ERR_PROC_YA_EXISTE_POR_NOMBRE_ANIO";
    public static final String ERR_INSUMO_ASOCIADO_A_OTRO_PROCESO = "ERR_INSUMO_ASOCIADO_A_OTRO_PROCESO";
    public static final String ERR_PROCESO_EN_PAUSA = "ERR_PROCESO_EN_PAUSA";
    public static final String ERR_PROCESO_ADQ_SIN_INSUMOS = "ERR_PROCESO_ADQ_SIN_INSUMOS";
    public static final String ERR_CANTIDAD_NO_PUEDE_SER_CERO = "ERR_CANTIDAD_NO_PUEDE_SER_CERO";
    public static final String ERR_INSUMOS_CON_TIPO_PROYECTO_INADECUADO_PARA_ADJUDICAR_SIN_COMPROMISO = "ERR_INSUMOS_CON_TIPO_PROYECTO_INADECUADO_PARA_ADJUDICAR_SIN_COMPROMISO";
    public static final String ERR_EL_ITEM_0_YA_FUE_ASIGNADO_NO_PUEDE_RETROCEDER = "ERR_EL_ITEM_0_YA_FUE_ASIGNADO_NO_PUEDE_RETROCEDER";
    public static final String ERR_QUEDAN_YA_FUE_EMITIDO = "ERR_QUEDAN_YA_FUE_EMITIDO";
    public static final String ERR_NO_DEFINIDO_SI_PROVEEDOR_PERSONA_FISICA_O_JURDICA = "ERR_NO_DEFINIDO_SI_PROVEEDOR_PERSONA_FISICA_O_JURDICA";
    public static final String ERR_EL_PROCESO_YA_TIENE_UN_COMPROMISO_PRESUPUESTARIO_GENERADO = "ERR_EL_PROCESO_YA_TIENE_UN_COMPROMISO_PRESUPUESTARIO_GENERADO";
    public static final String ERR_PARA_EMITIR_COMPROMISO_PRESUPUESTARIO_DEBE_ESTAR_PENDIENTE = "ERR_PARA_EMITIR_COMPROMISO_PRESUPUESTARIO_DEBE_ESTAR_PENDIENTE";
    public static final String ERR_MONTO_ADJUDICADO_MAYOR_A_MONTO_CERTIFICADO_PARA_INSUMO_0 = "ERR_MONTO_ADJUDICADO_MAYOR_A_MONTO_CERTIFICADO_PARA_INSUMO_0";
    public static final String ERR_PARA_VALIDAR_COMPROMISO_PRESUPUESTARIO_DEBE_ESTAR_EMITIDO = "ERR_PARA_VALIDAR_COMPROMISO_PRESUPUESTARIO_DEBE_ESTAR_EMITIDO";
    public static final String ERR_QUEDAN_NO_EMITIDO = "ERR_QUEDAN_NO_EMITIDO";
    public static final String ERR_FECHA_RECEPCION_OFERTAS_INCORRECTA = "ERR_FECHA_RECEPCION_OFERTAS_INCORRECTA";
    public static final String ERROR_FALTA_INGRESAR_FECHA_FIN_RECEPCION_OFERTAS = "ERROR_FALTA_INGRESAR_FECHA_FIN_RECEPCION_OFERTAS";
    public static final String ERROR_FALTA_INGRESAR_HORA_FIN_RECEPCION_OFERTAS = "ERROR_FALTA_INGRESAR_HORA_FIN_RECEPCION_OFERTAS";
    public static final String ERR_HORA_RECEPCION_OFERTAS_INCORRECTA = "ERR_HORA_RECEPCION_OFERTAS_INCORRECTA";
    public static final String YA_SE_CAMBIO_EL_ESTADO_DEL_CERTIFICADO = "YA_SE_CAMBIO_EL_ESTADO_DEL_CERTIFICADO";
    public static final String ERR_MONTO_A_DESCOMPROMETER_DEBE_SER_MENOR_A_MONTO_COMPROMETIDO = "ERR_MONTO_A_DESCOMPROMETER_DEBE_SER_MENOR_A_MONTO_COMPROMETIDO";
    public static final String ERR_MONTO_A_DESCOMPROMETER_DEBE_SER_MAYOR_A_CERO="ERR_MONTO_A_DESCOMPROMETER_DEBE_SER_MAYOR_A_CERO";
    public static final String ERR_EL_INSUMO_0_YA_ESTA_ASOCIADO_AL_PROCESO_1="ERR_EL_INSUMO_0_YA_ESTA_ASOCIADO_AL_PROCESO_1";
    public static final String ERR_INSUMO_NO_TIENE_MONTO_COMPROMETIDO = "ERR_INSUMO_NO_TIENE_MONTO_COMPROMETIDO";
    public static final String ERR_PARA_EMITIR_QUEDAN_MONTO_TOTAL_FACTURAS_0_DEBE_COINCIDIR_CON_MONTO_ACTAS_MENOS_PORC_ANT_1 = "ERR_PARA_EMITIR_QUEDAN_MONTO_TOTAL_FACTURAS_0_DEBE_COINCIDIR_CON_MONTO_ACTAS_MENOS_PORC_ANT_1";
    public static final String ERR_EL_PROCESO_YA_TIENE_COMPROMISOS_PRESUPUESTARIOS_GENERADOS = "ERR_EL_PROCESO_YA_TIENE_COMPROMISOS_PRESUPUESTARIOS_GENERADOS";
    
    //contrato oc
    public static final String ERR_SUMA_DE_PAGOS_A_NIVEL_DE_UT_DISTINTO_DE_IMPORTE_NETO = "ERR_SUMA_DE_PAGOS_A_NIVEL_DE_UT_DISTINTO_DE_IMPORTE_NETO";
    public static final String ERR_HAY_CONTRATOS_NO_VALIDAN = "ERR_HAY_CONTRATOS_NO_VALIDAN";
    public static final String ERR_El_CONTRATO_CON_NRO_0_NO_VALIDA = "ERR_El_CONTRATO_CON_NRO_0_NO_VALIDA";
    public static final String ERR_EN_EL_CONTRATO_0_EL_MONTO_DE_PROGRAMACION_PAGOS_1_DISTINTO_DEL_MOTNO_ADJUDICADO_2 = "ERR_EN_EL_CONTRATO_0_EL_MONTO_DE_PROGRAMACION_PAGOS_1_DISTINTO_DEL_MOTNO_ADJUDICADO_2";
    public static final String ERR_CONTRATOS_YA_GENERADOS_NO_PUEDE_CAMBIAR_GENERACION = "ERR_CONTRATOS_YA_GENERADOS_NO_PUEDE_CAMBIAR_GENERACION";
    public static final String ERR_EXISTE_PROGRAMACION_PAGO_SIN_ANIO = "ERR_EXISTE_PROGRAMACION_PAGO_SIN_ANIO";
    public static final String ERR_EXISTEN_DOS_PROGRAMACIONES_PAGO_PARA_ANIO_0 = "ERR_EXISTEN_DOS_PROGRAMACIONES_PAGO_PARA_ANIO_0";
    public static final String ERR_MONTO_DE_PROGRAMACION_PAGOS_0_DISTINTO_DEL_MOTNO_ADJUDICADO_1 = "ERR_MONTO_DE_PROGRAMACION_PAGOS_0_DISTINTO_DEL_MOTNO_ADJUDICADO_1";
    public static final String ERR_LA_SUMA_DE_PROGRAMACION_PAGOS_0_NO_COINCIDE_CON_MONTO_ADJ_DEL_CONTRATO_1 = "ERR_LA_SUMA_DE_PROGRAMACION_PAGOS_0_NO_COINCIDE_CON_MONTO_ADJ_DEL_CONTRATO_1";
    public static final String ERR_CONTRATO_SIN_INICIAR = "ERR_CONTRATO_SIN_INICIAR";
    public static final String ERR_ARCHIVO_ORDEN_INICIO_VACIO = "ERR_ARCHIVO_ORDEN_INICIO_VACIO";
    public static final String ERR_FIRMANTE_ORDEN_INICIO_VACIO = "ERR_FIRMANTE_ORDEN_INICIO_VACIO";
    public static final String ERR_PARA_DESCARGAR_REPORTE_ES_NECESARIO_GENERAR_NUMERO_COMPROBANTE_RECEPCION_PAGO = "ERR_PARA_DESCARGAR_REPORTE_ES_NECESARIO_GENERAR_NUMERO_COMPROBANTE_RECEPCION_PAGO";
    public static final String ERR_FECHA_FIN_ORDEN_INICIO_MENOR_FECHA_INICIO = "ERR_FECHA_FIN_ORDEN_INICIO_MENOR_FECHA_INICIO";
    public static final String ERR_FECHA_INICIO_ORDEN_INICIO_MENOR_FECHA_EMISION = "ERR_FECHA_INICIO_ORDEN_INICIO_MENOR_FECHA_EMISION";
    public static final String ERR_DEBE_SELECCIONAR_FIRMANTE_CONTRATO_OC = "ERR_DEBE_SELECCIONAR_FIRMANTE_CONTRATO_OC";
    public static final String ERR_DEBE_SELECCIONAR_ADMIN_CONTRATO_OC = "ERR_DEBE_SELECCIONAR_ADMIN_CONTRATO_OC";
    public static final String ERR_DEBE_CARGAR_ORDEN_INICIO_PARA_INICIAR = "ERR_DEBE_CARGAR_ORDEN_INICIO_PARA_INICIAR";
    public static final String ERROR_CANTIDAD_RECIBIDA_ITEM_MAYOR_CANTIDAD_ADJUDICADA = "ERROR_CANTIDAD_RECIBIDA_ITEM_MAYOR_CANTIDAD_ADJUDICADA";
    public static final String ERROR_MONTO_RECIBIDO_ITEM_MAYOR_MONTO_ADJUDICADO = "ERROR_MONTO_RECIBIDO_ITEM_MAYOR_MONTO_ADJUDICADO";
    public static final String ERROR_CANTIDAD_RECIBIDA_INSUMO_MAYOR_CANTIDAD_ADJUDICADA = "ERROR_CANTIDAD_RECIBIDA_INSUMO_MAYOR_CANTIDAD_ADJUDICADA";
    public static final String ERROR_MONTO_UNIT_RECIBIDO_ITEM_MAYOR_MONTO_UNIT_ADJUDICADO = "ERROR_MONTO_UNIT_RECIBIDO_ITEM_MAYOR_MONTO_UNIT_ADJUDICADO";
    public static final String ERROR_FECHA_RECEPCION_MAYOR_DIA_ACTUAL = "ERROR_FECHA_RECEPCION_MAYOR_DIA_ACTUAL";
    public static final String ERROR_ITEMS_DE_ACTA_CON_TODOS_LOS_VALORES_VACIOS = "ERROR_ITEMS_DE_ACTA_CON_TODOS_LOS_VALORES_VACIOS";
    public static final String ERROR_IMPORTE_PAGOS_ACTAS_CON_MISMO_PAGO_ASOCIADO_SUPERA_PAGO_SELECCIONADO = "ERROR_IMPORTE_PAGOS_ACTAS_CON_MISMO_PAGO_ASOCIADO_SUPERA_PAGO_SELECCIONADO";
    public static final String ERROR_CANTIDAD_RECIBIDA_INSUMO_MAYOR_A_CANTIDAD_ADJUDICADA = "ERROR_CANTIDAD_RECIBIDA_INSUMO_MAYOR_A_CANTIDAD_ADJUDICADA";
    public static final String ERROR_QUEDAN_EMITIDO_POR_TESORERIA = "ERROR_QUEDAN_EMITIDO_POR_TESORERIA";
    public static final String ERROR_NO_SE_PUEDE_REVERTIR_ACTA_NO_APROBADA = "ERROR_NO_SE_PUEDE_REVERTIR_ACTA_NO_APROBADA";
    public static final String ERROR_SOLO_SE_PUEDE_ELIMINAR_ACTA_EN_DIGITACION = "ERROR_SOLO_SE_PUEDE_ELIMINAR_ACTA_EN_DIGITACION";
    public static final String ERR_NO_SE_PUEDE_CREAR_ACTA_DE_ANTICIPO_PORQUE_EL_CONTRATO_ES_SIN_ANTICIPO = "ERR_NO_SE_PUEDE_CREAR_ACTA_DE_ANTICIPO_PORQUE_EL_CONTRATO_ES_SIN_ANTICIPO";
    public static final String ERR_PORCENTAJE_ANTICIPO_ACTA_SUPERA_PORCENTAJE_ANTICIPO_CONTRATO = "ERR_PORCENTAJE_ANTICIPO_ACTA_SUPERA_PORCENTAJE_ANTICIPO_CONTRATO";
    public static final String ERR_MONTO_FIJO_ANTICIPO_ACTA_SUPERA_MONTO_FIJO_ANTICIPO_CONTRATO = "ERR_MONTO_FIJO_ANTICIPO_ACTA_SUPERA_MONTO_FIJO_ANTICIPO_CONTRATO";
    public static final String ERROR_FECHAGENERACION_MAYOR_DIA_ACTUAL = "ERROR_FECHAGENERACION_MAYOR_DIA_ACTUAL";
    public static final String ERROR_YA_EXISTE_ACTA_ANTICIPO_APROBADA = "ERROR_YA_EXISTE_ACTA_ANTICIPO_APROBADA";
    public static final String ERROR_YA_EXISTE_ACTA_DEVOLUCION_APROBADA = "ERROR_YA_EXISTE_ACTA_DEVOLUCION_APROBADA";
    public static final String ERROR_YA_EXISTE_ACTA_DEVOLUCION = "ERROR_YA_EXISTE_ACA_DEVOLUCION";
    public static final String ERR_NO_SE_PUEDE_CREAR_ACTA_DE_DEVOLUCION_PORQUE_EL_CONTRATO_ES_SIN_DEVOLUCION = "ERR_NO_SE_PUEDE_CREAR_ACTA_DE_DEVOLUCION_PORQUE_EL_CONTRATO_ES_SIN_DEVOLUCION";
    public static final String ERR_PORCENTAJE_DEVOLUCION_ACTA_SUPERA_PORCENTAJE_DEVOLUCION_CONTRATO = "ERR_PORCENTAJE_DEVOLUCION_ACTA_SUPERA_PORCENTAJE_DEVOLUCION_CONTRATO";
    public static final String ERR_MONTO_FIJO_DEVOLUCION_ACTA_SUPERA_MONTO_FIJO_DEVOLUCION_CONTRATO = "ERR_MONTO_FIJO_DEVOLUCION_ACTA_SUPERA_MONTO_FIJO_DEVOLUCION_CONTRATO";
    public static final String ERR_FECHAS_CONTRATO_INVALIDAS = "ERR_FECHAS_CONTRATO_INVALIDAS";
    public static final String ERR_PAGOS_DEBEN_SER_POSTERIORES_A_FECHA_INCIO_CONTRATO = "ERR_PAGOS_DEBEN_SER_POSTERIORES_A_FECHA_INCIO_CONTRATO";
    public static final String ERROR_PARA_CARGAR_ORDEN_INICIO_DEBE_SELECCIONAR_ADMIN_CONTRATO = "ERROR_PARA_CARGAR_ORDEN_INICIO_DEBE_SELECCIONAR_ADMIN_CONTRATO";
    public static final String ERROR_PARA_CARGAR_ORDEN_INICIO_DEBE_SELECCIONAR_FECH_EMISION = "ERROR_PARA_CARGAR_ORDEN_INICIO_DEBE_SELECCIONAR_FECH_EMISION";
    public static final String ERROR_PARA_CARGAR_ORDEN_INICIO_DEBE_SELECCIONAR_FECH_INICIO = "ERROR_PARA_CARGAR_ORDEN_INICIO_DEBE_SELECCIONAR_FECH_INICIO";
    public static final String ERROR_PARA_CARGAR_ORDEN_INICIO_DEBE_SELECCIONAR_FECH_FIN = "ERROR_PARA_CARGAR_ORDEN_INICIO_DEBE_SELECCIONAR_FECH_FIN";
    public static final String ERROR_PARA_CARGAR_ORDEN_INICIO_DEBE_SELECCIONAR_FIRM_CONTRATO = "ERROR_PARA_CARGAR_ORDEN_INICIO_DEBE_SELECCIONAR_FIRM_CONTRATO";
    public static final String ERR_PORCENTAJE_ACTA_INCORRECTO = "ERR_PORCENTAJE_ACTA_INCORRECTO";
    public static final String ERR_MONTO_FIJO_ACTA_INCORRECTO = "ERR_MONTO_FIJO_ACTA_INCORRECTO";
    public static final String ERR_CANTIDAD_RECIBIDA_EN_ACTA_RECEPCION_INCORRECTA = "ERR_CANTIDAD_RECIBIDA_EN_ACTA_RECEPCION_INCORRECTA";
    public static final String ERR_MONTO_RECIBIDO_EN_ACTA_RECEPCION_INCORRECTO = "ERR_MONTO_RECIBIDO_EN_ACTA_RECEPCION_INCORRECTO";
    public static final String ERR_CANT_RECIBIDA_EN_ACTA_RECEPCION_MAYOR_MONT_ADJ = "ERR_CANT_RECIBIDA_EN_ACTA_RECEPCION_MAYOR_MONT_ADJ";
    public static final String ERR_MONTO_RECIBIDO_EN_ACTA_RECEPCION_MAYOR_MONT_ADJ = "ERR_MONTO_RECIBIDO_EN_ACTA_RECEPCION_MAYOR_MONT_ADJ";
    public static final String ERR_MONTO_RESCINDIDO_PARA_INSUMO_SUPERA_MONTO_INGRESADO_EN_ACTAS = "ERR_MONTO_RESCINDIDO_PARA_INSUMO_SUPERA_MONTO_INGRESADO_EN_ACTAS";
    public static final String ERR_MONTO_RESCINDIDO_INSUMO_MAYOR_MONTO_ADJUDICADO = "ERR_MONTO_RESCINDIDO_INSUMO_MAYOR_MONTO_ADJUDICADO";
    public static final String ERR_MES_INICIAL_INCORRECTO = "ERR_MES_INICIAL_INCORRECTO";
    public static final String ERR_CONTRATO_YA_RESCINDIDO = "ERR_CONTRATO_YA_RESCINDIDO";
    public static final String ERR_MONTO_RESCINDIDO_INSUMO_NEGATIVO = "ERR_MONTO_RESCINDIDO_INSUMO_NEGATIVO";
    public static final String ERR_MONTO_RESCINDIDO_CONTRATO_ES_CERO = "ERR_MONTO_RESCINDIDO_CONTRATO_ES_CERO";
    public static final String ERROR_MONTO_RECIBIDO_INSUMO_MAYOR_A_MONTO_ADJUDICADO = "ERROR_MONTO_RECIBIDO_INSUMO_MAYOR_A_MONTO_ADJUDICADO";
    public static final String ERROR_FECHA_EXTENSION_CONTRATO_INCORRECTA = "ERROR_FECHA_EXTENSION_CONTRATO_INCORRECTA";
    public static final String ERR_NO_SELECCIONO_INSUMO_PARA_AGREGAR_A_MODIFICATIVA = "ERR_NO_SELECCIONO_INSUMO_PARA_AGREGAR_A_MODIFICATIVA";
    public static final String ERR_EXISTE_INSUMO_ASOCIADOS_A_PROCESO_ADQUISICION = "ERR_EXISTE_INSUMO_ASOCIADOS_A_PROCESO_ADQUISICION";
    public static final String ERR_EXISTE_INSUMO_ASOCIADOS_A_OTRA_MODIFICATIVA = "ERR_EXISTE_INSUMO_ASOCIADOS_A_OTRA_MODIFICATIVA";
    public static final String ERR_FALTA_PROGRAMACION_PAGOS_MODIFICATIVA = "ERR_ERROR_FALTA_PROGRAMACION_PAGOS_MODIFICATIVA";
    public static final String ERR_LA_MODIFICATIVA_YA_TIENE_UN_COMPROMISO_PRESUPUESTARIO_GENERADO = "ERR_LA_MODIFICATIVA_YA_TIENE_UN_COMPROMISO_PRESUPUESTARIO_GENERADO";
    public static final String ERR_LA_SUMA_DE_PROGRAMACION_PAGOS_0_NO_COINCIDE_CON_MONTO_TOTAL_DE_LA_MODIFICATIVA_1 = "ERR_LA_SUMA_DE_PROGRAMACION_PAGOS_0_NO_COINCIDE_CON_MONTO_TOTAL_DE_LA_MODIFICATIVA_1";
    public static final String ERR_MODIFICATIVA_SIN_INSUMOS_ASOCIADOS = "ERR_MODIFICATIVA_SIN_INSUMOS_ASOCIADOS";
    public static final String ERROR_COMPORMISO_SELECIONADO_YA_TIENE_RESERVA_DE_FONDOS_GENERADA = "ERROR_COMPORMISO_SELECIONADO_YA_TIENE_RESERVA_DE_FONDOS_GENERADA";

//insumos
    public static final String ERR_SELECCIONE_UN_OEG_EXISTENTE = "ERR_SELECCIONE_UN_OEG_EXISTENTE";
    public static final String ERR_AL_AUTOGENERAR_CODIGO_INSUMO = "ERR_AL_AUTOGENERAR_CODIGO_INSUMO";

    public static final String ERR_GEST_UNIDAD_TECNICA_NOMBRE_VACIO = "ERR_GEST_UNIDAD_TECNICA_NOMBRE_VACIO";
    public static final String ERR_GEST_UNIDAD_TECNICA_CODIGO_VACIO = "ERR_GEST_UNIDAD_TECNICA_CODIGO_VACIO";
    public static final String ERR_GEST_UNIDAD_TECNICA_PADRE_VACIO = "ERR_GEST_UNIDAD_TECNICA_PADRE_VACIO";
    public static final String ERR_GEST_UNIDAD_RESPONSABLE_VACIO = "ERR_GEST_UNIDAD_RESPONSABLE_VACIO";
    public static final String ERR_GEST_UNIDAD_DIRECCION_VACIA = "ERR_GEST_UNIDAD_DIRECCION_VACIA";
    public static final String ERR_CODIGO_UT_YA_EXISTE = "ERR_CODIGO_UT_YA_EXISTE";
    public static final String ERR_CODIGO_UT_DEMASIADO_LARGO = "ERR_CODIGO_UT_DEMASIADO_LARGO";

    public static final String ERR_GEST_UNIDAD_TECNICA_ID_PADRE_NO_DETERMINADO = "ERR_GEST_UNIDAD_TECNICA_ID_PADRE_NO_DETERMINADO";
    public static final String ERR_GEST_UNIDAD_TECNICA_PADRE_NO_DETERMINADO = "ERR_GEST_UNIDAD_TECNICA_PADRE_NO_DETERMINADO";
    public static final String ERR_GEST_UNIDAD_TECNICA_ID_NO_DETERMINADO = "ERR_GEST_UNIDAD_TECNICA_ID_NO_DETERMINADO";
    public static final String ERR_GEST_UNIDAD_TECNICA_DETERMINADA = "ERR_GEST_UNIDAD_TECNICA_DETERMINADA";

    //CONTRASENIA
    public static final String ERR_CONTRASENIA_VACIA = "ERR_PASSWORD_VACIA";
    public static final String ERR_CONTRASENIA_NO_COINCIDEN = "ERR_PASSWORD_NO_COINCIDEN";

    //calculo en sugerencia de montos
    public static final String ERR_EXISTE_CIRCULARIDAD_EN_FORMULA = "ERR_EXISTE_CIRCULARIDAD_EN_FORMULA";

    //carga metas    
    public static final String ERR_DEBE_SELECIONAR_UN_ANIO_FISCAL = "ERR_DEBE_SELECIONAR_UN_ANIO_FISCAL";

    public static final String ERR_DEBE_SELECIONAR_UNA_PLANIFICACION = "ERR_DEBE_SELECIONAR_UNA_PLANIFICACION";

    public static final String ERR_DEBE_SELECIONAR_UN_PROYECTO = "ERR_DEBE_SELECIONAR_UN_PROYECTO";

    public static final String ERR_CAMPO_REQUERIDO = "Error.CampoRequerido";

    public static final String ERR_REP_MONTO_CERTIFICADO = "ERR_REP_MONTO_CERTIFICADO";
    public static final String ERR_EL_NUEVO_MONTO_NO_PUEDE_SERMENOR_AL_MONTO_CERTIFICADO_0 = "ERR_EL_NUEVO_MONTO_NO_PUEDE_SERMENOR_AL_MONTO_CERTIFICADO_0";
    public static final String ERR_EL_NUEVO_MONTO_NO_PUEDE_SERMENOR_AL_MONTO_ADJUDICADO_0 = "ERR_EL_NUEVO_MONTO_NO_PUEDE_SERMENOR_AL_MONTO_ADJUDICADO_0";

    public static final String ERR_REP_MONTO_ADJUDICADO = "ERR_REP_MONTO_ADJUDICADO";
    public static final String ERR_REP_NO_SE_SELECCIONO_ACTIVIDAD = "ERR_REP_NO_SE_SELECCIONO_ACTIVIDAD";
    public static final String ERR_REP_NO_COINCIDE_MONTO_TOTAL = "ERR_REP_NO_COINCIDE_MONTO_TOTAL";
    public static final String ERR_REP_EL_FLUJO_DE_CAJA_NO_COINCIDE_CON_TOTAL_INSUMO = "ERR_REP_EL_FLUJO_DE_CAJA_NO_COINCIDE_CON_TOTAL_INSUMO";
    public static final String ERROR_INSUMO_SIN_GRUPO = "ERROR_INSUMO_SIN_GRUPO";
    public static final String ERR_DEBE_SELECIONAR_UN_ANIO_SEGUIMIENTO = "ERR_DEBE_SELECIONAR_UN_ANIO_SEGUIMIENTO";
    public static final String ERR_DEBE_SELECIONAR_UNIDAD_TECNICA = "ERR_DEBE_SELECIONAR_UNIDAD_TECNICA";

    public static final String ERR_EXISTE_DETALLE_EN_REPROGRAMACION_NO_ASOCIADO_A_NINGUN_POA = "ERR_EXISTE_DETALLE_EN_REPROGRAMACION_NO_ASOCIADO_A_NINGUN_POA";
    public static final String ERR_MONTO_POLIZA_SUPERA_MONTO_DE_PAGO_SELECCIONADO = "ERR_MONTO_POLIZA_SUPERA_MONTO_DE_PAGO_SELECCIONADO";
    public static final String ERR_MONTO_POLIZA_INCORRECTO="ERR_MONTO_POLIZA_INCORRECTO";
    public static final String ERR_MONTO_FACTURAS_0_DEBE_COINCIDIR_CON_MONTO_POLIZA="ERR_MONTO_FACTURAS_0_DEBE_COINCIDIR_CON_MONTO_POLIZA";
    public static final String ERR_SUMA_MONTOS_POLIZAS_APLICADAS_SUPERA_MONTO_DE_PAGO_ASOCIADO="ERR_SUMA_MONTOS_POLIZAS_APLICADAS_SUPERA_MONTO_DE_PAGO_ASOCIADO";
    public static final String ERR_DEBE_AGREGAR_FACTURAS_POR_MONTO_POLIZA="ERR_DEBE_AGREGAR_FACTURAS_POR_MONTO_POLIZA";
    public static final String ERR_DEBE_SELECCIONAR_UN_PAGO_PARA_LA_POLIZA = "ERR_DEBE_SELECCIONAR_UN_PAGO_PARA_LA_POLIZA";

    public static final String ERR_GNRAL_FORMATO_INCORRECTO = "ERR_GNRAL_FORMATO_INCORRECTO";
    public static final String ERR_DEBE_SELECIONAR_ARCHIVO = "ERR_DEBE_SELECIONAR_ARCHIVO";
    public static final String ERR_FUENTE_0_ASOCIADA_A_POLIZA_CON_PAGO_1_EN_MES_2 = "ERR_FUENTE_0_ASOCIADA_A_POLIZA_CON_PAGO_1_EN_MES_2";
    public static final String ERR_LAS_FUENTES_NO_PUEDEN_DISMINUIR_EL_MONTO_CERTIFICADO = "ERR_LAS_FUENTES_NO_PUEDEN_DISMINUIR_EL_MONTO_CERTIFICADO";
    
    public static final String ERR_CAMPOS_REQUERIDOS_NO_COMPLETADOS = "ERR_CAMPOS_REQUERIDOS_NO_COMPLETADOS";
    public static final String ERR_CODIGO_INSUMO_REPETIDO = "ERR_CODIGO_INSUMO_REPETIDO";
    public static final String ERR_SUBMODALIDAD_SIN_RELACION = "ERR_SUBMODALIDAD_SIN_RELACION";
    
    
    public static final String ERR_SUBCUENTA_VACIA = "ERR_SUBCUENTA_VACIA";
    public static final String ERR_COMPONENTE_PRESUPUESTO_ESCOLAR_VACIO = "ERR_COMPONENTE_PRESUPUESTO_ESCOLAR_VACIO";
    public static final String ERR_CODIGO_SUBCUENTA_INEXISTENTE = "ERR_CODIGO_SUBCUENTA_INEXISTENTE";
    public static final String ERR_CODIGO_SUBCUENTA_INEXISTENTE_EN_PRESUPUESTO = "ERR_CODIGO_SUBCUENTA_INEXISTENTE_EN_PRESUPUESTO";
    public static final String ERR_PRESUPUESTO_SIN_FUENTES_FINANCIAMIENTO= "ERR_PRESUPUESTO_SIN_FUENTES_FINANCIAMIENTO";
    public static final String ERR_CODIGO_SEDE_INEXISTENTE = "ERR_CODIGO_SEDE_INEXISTENTE";
    
    public static final String ERR_COMPONENTE_VACIO = "ERR_COMPONENTE_VACIO";
    public static final String ERR_SUBCOMPONENTE_VACIO = "ERR_SUBCOMPONENTE_VACIO";
    public static final String ERR_UNIDAD_PRESUPUESTARIA_VACIO = "ERR_UNIDAD_PRESUPUESTARIA_VACIO";
    public static final String ERR_ESTADO_VACIO = "ERR_ESTADO_VACIO";
    public static final String ERR_ANIO_VACIO = "ERR_ANIO_VACIO";

    public static final String ERR_ANIO_ORIGEN_VACIO = "ERR_ANIO_ORIGEN_VACIO";
    public static final String ERR_ANIO_DESTINO_VACIO = "ERR_ANIO_DESTINO_VACIO";
    public static final String ERR_ANIO_ORIGEN_IGUAL_ANIO_DESTINO = "ERR_ANIO_ORIGEN_IGUAL_ANIO_DESTINO";
    
    public static final String ERR_COMPONENTES_NO_ENCONTRADOS = "ERR_COMPONENTES_NO_ENCONTRADOS";
    
    public static final String ERR_FECHA_MATRICULA_VACIA = "ERR_FECHA_MATRICULA_VACIA";
    public static final String ERR_MONTO_POR_MATRICULA_VACIO = "ERR_MONTO_POR_MATRICULA_VACIO";
    
    public static final String ERR_TRANSFERENCIA_COMPONENTE_VACIO = "ERR_TRANSFERENCIA_COMPONENTE_VACIO";
    
    public static final String ERR_LIMITE_PORCENTAJES_ALCANZADO = "ERR_LIMITE_PORCENTAJES_ALCANZADO";
    public static final String ERR_NINGUN_REGISTRO_SELECCIONADO = "ERR_NINGUN_REGISTRO_SELECCIONADO";
    public static final String ERR_NINGUN_ESTADO_SELECCIONADO = "ERR_NINGUN_ESTADO_SELECCIONADO";
    public static final String ERR_CODIGO_DE_CENTRO_EDUCATIVO_NO_VALIDO = "ERR_CODIGO_DE_CENTRO_EDUCATIVO_NO_VALIDO";
    public static final String ERR_PORCENTAJE_INGRESADO_NO_VALIDO = "ERR_PORCENTAJE_INGRESADO_NO_VALIDO";
    public static final String ERR_MONTO_APROBADO_NO_VALIDO = "ERR_MONTO_APROBADO_NO_VALIDO";
    public static final String ERR_CENTRO_EDUCATIVO_NO_ENCONTRADO = "ERR_CENTRO_EDUCATIVO_NO_ENCONTRADO";
    public static final String ERR_DIRECCION_DEPARTAMENTAL_NO_ENCONTRADA = "ERR_DIRECCION_DEPARTAMENTAL_NO_ENCONTRADA";
    public static final String ERR_BENEFICIARIOS_VACIO = "ERR_BENEFICIARIOS_VACIO";
    public static final String ERR_SEDES_VACIO = "ERR_SEDES_VACIO";
    public static final String ERR_OPCION_PORCENTAJE_NO_SELECCION = "ERR_OPCION_PORCENTAJE_NO_SELECCION";
    
    public static final String ERR_NO_ELIMINAR_REGISTROS_TOPE = "ERR_NO_ELIMINAR_REGISTROS_TOPE";
    public static final String ERR_NO_ELIMINAR_REGISTROS_TRANSFERENCIA_COMPONENTE = "ERR_NO_ELIMINAR_REGISTROS_TRANSFERENCIA_COMPONENTE";
    public static final String ERR_REGISTRO_NO_ENCONTRADO = "ERR_REGISTRO_NO_ENCONTRADO";
    public static final String ERR_TECHO_EXISTENTE_ENCONTRADO = "ERR_TECHO_EXISTENTE_ENCONTRADO";
    public static final String ERR_GENERACION_RESULTADOS = "ERR_GENERACION_RESULTADOS";
    public static final String ERR_SUBCOMPONENTE_NO_SELECCIONADO = "ERR_SUBCOMPONENTE_NO_SELECCIONADO";
    public static final String ERR_LINEA_PRESUPUESTARIA_NO_SELECCIONADA = "ERR_LINEA_PRESUPUESTARIA_NO_SELECCIONADA";
    public static final String ERR_DIRECCION_DEPARTAMENTAL_NO_SELECCIONADA = "ERR_DIRECCION_DEPARTAMENTAL_NO_SELECCIONADA";
    public static final String ERR_ESTADO_NO_SELECCIONADO = "ERR_ESTADO_NO_SELECCIONADO";
    public static final String ERR_ANIO_FISCAL_NO_SELECCIONADO = "ERR_ANIO_FISCAL_NO_SELECCIONADO";
    public static final String ERR_MONTO_APROBADO_NO_INGRESADO = "ERR_MONTO_APROBADO_NO_INGRESADO";
    public static final String ERR_FUENTE_FINANCIAMIENTO_NO_SELECCIONADA = "ERR_FUENTE_FINANCIAMIENTO_NO_SELECCIONADA";
    public static final String ERR_FUENTE_RECURSOS_NO_SELECCIONADA = "ERR_FUENTE_RECURSOS_NO_SELECCIONADA";
    
    public static final String ERR_TECHOS_NO_ENCONTRADOS = "ERR_TECHOS_NO_ENCONTRADOS";
    public static final String ERR_MONTO_TOTAL_FORMULADO_MENOR = "ERR_MONTO_TOTAL_FORMULADO_MENOR";
    public static final String ERR_MONTO_TOTAL_APROBADO_MENOR = "ERR_MONTO_TOTAL_APROBADO_MENOR";
    public static final String ERR_TIPO_MONTO_NO_INGRESADO = "ERR_TIPO_MONTO_NO_INGRESADO";
    public static final String ERR_CTDAD_RANGO_MATRICULA_NO_INGRESADO = "ERR_CTDAD_RANGO_MATRICULA_NO_INGRESADO";
    public static final String ERR_OEG_NO_INGRESADO = "ERR_OEG_NO_INGRESADO";
    public static final String ERR_OEG_NO_INGRESADO_NO_VALIDO = "ERR_OEG_NO_INGRESADO_NO_VALIDO";
    public static final String ERR_NINGUN_RANGO_MATRICULA_CREADO = "ERR_NINGUN_RANGO_MATRICULA_CREADO";
 
    public static final String ERR_CUENTA_RELACION_COMPONENTE = "ERR_CUENTA_RELACION_COMPONENTE";
    public static final String ERR_CUENTA_RELACION_TRANSFERENCIA = "ERR_CUENTA_RELACION_TRANSFERENCIA";
    public static final String ERR_COMPONENTE_RELACION_PRESUPUESTO_SUBCOMPONENTE = "ERR_COMPONENTE_RELACION_PRESUPUESTO_SUBCOMPONENTE";
    public static final String ERR_NO_POSIBLE_ELIMINAR = "ERR_NO_POSIBLE_ELIMINAR";
 
    public static final String ERR_PERSUPUESTO_NO_TIENE_REL_FINANCIAMIENTO = "ERR_PERSUPUESTO_NO_TIENE_REL_FINANCIAMIENTO";
    public static final String ERR_NO_EXISTE_REL_COMPONENTE_ANIO_FISCAL = "ERR_NO_EXISTE_REL_COMPONENTE_ANIO_FISCAL";
    
    public static final String ERR_RANGOS_NO_ENCONTRADOS = "ERR_RANGOS_NO_ENCONTRADOS";
    
    public static final String ERR_FUENTE_FINANCIAMIENTO_PRESUPUESTO_EXISTENTE = "ERR_FUENTE_FINANCIAMIENTO_PRESUPUESTO_EXISTENTE";
    
    public static final String ERR_ELIMINE_LOS_MOVIMIENTOS_DE_PRESUPUESTO_DE_TECHO = "ERR_ELIMINE_LOS_MOVIMIENTOS_DE_PRESUPUESTO_DE_TECHO";
    
    public static final String ERR_DESEMBOLSO_SIN_TECHOS = "ERR_DESEMBOLSO_SIN_TECHOS";
    public static final String ERR_NOMBRE_COMPLEMENTO_NO_INGRESADO = "ERR_NOMBRE_COMPLEMENTO_NO_INGRESADO";
    public static final String ERR_BASE_PRESUPUESTO_ANIO_YA_CREADA = "ERR_BASE_PRESUPUESTO_ANIO_YA_CREADA";
    
    public static final String ERR_RELACION_ANIO_FINANCIAMIENTO_NO_ENCONTRADA = "ERR_RELACION_ANIO_FINANCIAMIENTO_NO_ENCONTRADA";
    public static final String ERR_RELACION_PRESUPUESTO_ANIO_FISCAL_NO_ENCONTRADA = "ERR_RELACION_PRESUPUESTO_ANIO_FISCAL_NO_ENCONTRADA";
    public static final String ERR_TIPO_CLASIFICACION_PRESUPUESTO_NO_SELECCIONADO = "ERR_TIPO_CLASIFICACION_PRESUPUESTO_NO_SELECCIONADO";
    
    public static final String ERR_UNIDAD_TECNICA_VACIA = "ERR_UNIDAD_TECNICA_VACIA";
    public static final String ERR_PROGRAMA_INSTITUCIONAL_VACIO = "ERR_PROGRAMA_INSTITUCIONAL_VACIO";
    
    public static final String ERR_META_ANUAL_VACIO = "ERR_META_ANUAL_VACIO";
    public static final String ERR_INDICADOR_VACIO = "ERR_INDICADOR_VACIO";
    public static final String ERR_MEDIO_VERIFICACION_VACIO = "ERR_MEDIO_VERIFICACION_VACIO";
    public static final String ERR_PROGRAMA_TRIMESTRAL_VACIO = "ERR_PROGRAMA_TRIMESTRAL_VACIO";

    public static final String ERR_PROGRAMA_TRIMESTRAL_REAL_VACIO = "ERR_PROGRAMA_TRIMESTRAL_REAL_VACIO";
    public static final String ERR_META_ANUAL_LARGO_500 = "ERR_META_ANUAL_LARGO_500";
    public static final String ERR_MEDIO_VERIFICACION_LARGO_500 = "ERR_MEDIO_VERIFICACION_LARGO_500";
    public static final String ERR_METAS_DATOS_INCOMPLETOS= "ERR_METAS_DATOS_INCOMPLETOS";
    
    public static final String ERR_NOMBRE_VACIO= "ERR_NOMBRE_VACIO";
    public static final String ERR_NOMBRE_LARGO_500= "ERR_NOMBRE_LARGO_500";
    public static final String ERR_NOMBRE_LARGO_100= "ERR_NOMBRE_LARGO_100";
    public static final String ERR_NOMBRE_LARGO_255= "ERR_NOMBRE_LARGO_255";
    public static final String ERR_USUARIO_VACIO= "ERR_USUARIO_VACIO";
    public static final String ERR_PERIOD0_EJECUCION_DESDE_VACIO= "ERR_PERIOD0_EJECUCION_DESDE_VACIO";
    public static final String ERR_PERIOD0_EJECUCION_HASTA_VACIO= "ERR_PERIOD0_EJECUCION_HASTA_VACIO";
    public static final String ERR_PERIOD0_EJECUCION_FECHA_MAYOR_MENOR= "ERR_PERIOD0_EJECUCION_FECHA_MAYOR_MENOR";
    public static final String ERR_FUNCIONARIO_RESPONSABLE_VACIO= "ERR_FUNCIONARIO_RESPONSABLE_VACIO";
    public static final String ERR_FUNCIONARIO_RESPONSABLE_LARGO_50= "ERR_FUNCIONARIO_RESPONSABLE_LARGO_50";
    public static final String ERR_ACTIVIDADES_DATOS_INCOMPLETOS= "ERR_ACTIVIDADES_DATOS_INCOMPLETOS";
    
    public static final String ERR_FECHA_DESDE_FUERA_ANIO_FISCAL= "ERR_FECHA_DESDE_FUERA_ANIO_FISCAL";
    public static final String ERR_FECHA_HASTA_FUERA_ANIO_FISCAL= "ERR_FECHA_HASTA_FUERA_ANIO_FISCAL";
    public static final String ERR_FORMA_MEDICION_VACIO= "ERR_FORMA_MEDICION_VACIO";

    public static final String ERR_PORCENTAJE_PRIMER_TRIMESTRE_INVALIDO= "ERR_PORCENTAJE_PRIMER_TRIMESTRE_INVALIDO";
    public static final String ERR_PORCENTAJE_SEGUNDO_TRIMESTRE_INVALIDO= "ERR_PORCENTAJE_SEGUNDO_TRIMESTRE_INVALIDO";
    public static final String ERR_PORCENTAJE_TERCER_TRIMESTRE_INVALIDO= "ERR_PORCENTAJE_TERCER_TRIMESTRE_INVALIDO";
    public static final String ERR_PORCENTAJE_CUARTO_TRIMESTRE_INVALIDO= "ERR_PORCENTAJE_CUARTO_TRIMESTRE_INVALIDO";
    
    public static final String ERR_USUARIO_NO_TIENE_PERMISO_REGISTRAR_APOYO_EN_UNIDAD_TECNICA_POA = "ERR_USUARIO_NO_TIENE_PERMISO_REGISTRAR_APOYO_EN_UNIDAD_TECNICA_POA";
    
    public static final String ERR_DEBE_AGREGAR_ALMENOS_UNA_TAREA_POA = "ERR_DEBE_AGREGAR_ALMENOS_UNA_TAREA_POA";
    public static final String ERR_DEBE_AGREGAR_ALMENOS_UNA_ACTIVIDAD_A_TAREA_POA = "ERR_DEBE_AGREGAR_ALMENOS_UNA_ACTIVIDAD_A_TAREA_POA";

    public static final String ERR_PRIMER_TRIMESTRE_FECHA_DESDE_MAYOR_FECHA_HASTA = "ERR_PRIMER_TRIMESTRE_FECHA_DESDE_MAYOR_FECHA_HASTA";
    public static final String ERR_SEGUNDO_TRIMESTRE_FECHA_DESDE_MAYOR_FECHA_HASTA = "ERR_SEGUNDO_TRIMESTRE_FECHA_DESDE_MAYOR_FECHA_HASTA";
    public static final String ERR_TERCER_TRIMESTRE_FECHA_DESDE_MAYOR_FECHA_HASTA = "ERR_TERCER_TRIMESTRE_FECHA_DESDE_MAYOR_FECHA_HASTA";
    public static final String ERR_CUARTO_TRIMESTRE_FECHA_DESDE_MAYOR_FECHA_HASTA = "ERR_CUARTO_TRIMESTRE_FECHA_DESDE_MAYOR_FECHA_HASTA";
    
    public static final String ERR_PRIMER_TRIMESTRE_FECHA_DESDE_BLIGATORIO = "ERR_PRIMER_TRIMESTRE_FECHA_DESDE_BLIGATORIO";
    public static final String ERR_SEGUNDO_TRIMESTRE_FECHA_DESDE_BLIGATORIO = "ERR_SEGUNDO_TRIMESTRE_FECHA_DESDE_BLIGATORIO";
    public static final String ERR_TERCER_TRIMESTRE_FECHA_DESDE_BLIGATORIO = "ERR_TERCER_TRIMESTRE_FECHA_DESDE_BLIGATORIO";
    public static final String ERR_CUARTO_TRIMESTRE_FECHA_DESDE_BLIGATORIO = "ERR_CUARTO_TRIMESTRE_FECHA_DESDE_BLIGATORIO";
    
    public static final String ERR_PRIMER_TRIMESTRE_FECHA_HASTA_BLIGATORIO = "ERR_PRIMER_TRIMESTRE_FECHA_HASTA_BLIGATORIO";
    public static final String ERR_SEGUNDO_TRIMESTRE_FECHA_HASTA_BLIGATORIO = "ERR_SEGUNDO_TRIMESTRE_FECHA_HASTA_BLIGATORIO";
    public static final String ERR_TERCER_TRIMESTRE_FECHA_HASTA_BLIGATORIO = "ERR_TERCER_TRIMESTRE_FECHA_HASTA_BLIGATORIO";
    public static final String ERR_CUARTO_TRIMESTRE_FECHA_HASTA_BLIGATORIO = "ERR_CUARTO_TRIMESTRE_FECHA_HASTA_BLIGATORIO";
    
    public static final String ERR_PRIMER_TRIMESTRE_FECHA_FUERA_RANGO = "ERR_PRIMER_TRIMESTRE_FECHA_FUERA_RANGO";
    public static final String ERR_SEGUNDO_TRIMESTRE_FECHA_FUERA_RANGO = "ERR_SEGUNDO_TRIMESTRE_FECHA_FUERA_RANGO";
    public static final String ERR_TERCER_TRIMESTRE_FECHA_FUERA_RANGO = "ERR_TERCER_TRIMESTRE_FECHA_FUERA_RANGO";
    public static final String ERR_CUARTO_TRIMESTRE_FECHA_FUERA_RANGO = "ERR_CUARTO_TRIMESTRE_FECHA_FUERA_RANGO";
    
    public static final String ERR_TIPO_BIEN_VACIO = "ERR_TIPO_BIEN_VACIO";
    public static final String ERR_CATEGORIA_BIEN_VACIO = "ERR_CATEGORIA_BIEN_VACIO";
    public static final String ERR_DESCRIPCION_VACIO = "ERR_DESCRIPCION_VACIO";
    public static final String ERR_CODIGO_FUENTE_RECURSO_INEXISTENTE = "ERR_CODIGO_FUENTE_RECURSO_INEXISTENTE";
    
    public static final String ERR_TRANSFERENCIA_INEXISTENTE = "ERR_TRANSFERENCIA_INEXISTENTE";
    public static final String ERR_TRANSFERENCIA_INEXISTENTE_EN_COMPONENTE = "ERR_TRANSFERENCIA_INEXISTENTE_EN_COMPONENTE";
    public static final String ERR_CODIGO_FUENTE_RECURSO_INEXISTENTE_EN_COMPONENTE = "ERR_CODIGO_FUENTE_RECURSO_INEXISTENTE_EN_COMPONENTE";
    
    public static final String ERR_COMPONENTE_SIN_FUENTES_RECURSOS = "ERR_COMPONENTE_SIN_FUENTES_RECURSOS";
    public static final String ERR_TIPO_CALCULO_VACIO = "ERR_TIPO_CALCULO_VACIO";
    public static final String ERR_LINEA_PRESUPUESTARIA_VACIO = "ERR_LINEA_PRESUPUESTARIA_VACIO";
    public static final String ERR_YA_EXISTE_PROCESO_PRESUPUESTO_EJECUTANDOSE = "ERR_YA_EXISTE_PROCESO_PRESUPUESTO_EJECUTANDOSE";
    
    public static final String ERR_SEGUIMIENTO_ALCANCE_LIMITACIONES_VACIO = "ERR_SEGUIMIENTO_ALCANCE_LIMITACIONES_VACIO";
    public static final String ERR_SEGUIMIENTO_MEDIO_VERIFICACION_VACIO = "ERR_SEGUIMIENTO_MEDIO_VERIFICACION_VACIO";
    public static final String ERR_PRESUPUESTO_FORMULADO = "ERR_PRESUPUESTO_FORMULADO";
    public static final String ERR_PRESUPUESTO_CERRADO = "ERR_PRESUPUESTO_CERRADO";
    
    public static final String ERR_DEBE_SELECIONAR_AREA_INVERSION = "ERR_DEBE_SELECIONAR_AREA_INVERSION";
    public static final String ERR_DEBE_SELECIONAR_SUB_AREA_INVERSION = "ERR_DEBE_SELECIONAR_SUB_AREA_INVERSION";
    
    public static final String ERR_CODIGO_INSUMO_INEXISTENTE = "ERR_CODIGO_INSUMO_INEXISTENTE";
    public static final String ERR_NO_EXISTE_DIRECCION_DEPARTAMENTAl_SEDE = "ERR_NO_EXISTE_DIRECCION_DEPARTAMENTAl_SEDE";
}

