/*
 * Proyecto: Sistema Integrado de Administracion de Proyectos II
 * Organismo: Ministerio de Educacion de El Salvador
 * Desarrollado por: Sofis Solutions
 *
 */
package gob.mined.siap2.entities.enums;

/**
 *
 * @author Sofis Solutions
 */
public enum TipoNotificacion {
    GENERAL("GENERAL"),
    NUEVO_POA_ACCION_CENTRAL_PARA_VALIDAR("TipoNotificacion.NUEVO_POA_ACCION_CENTRAL_PARA_VALIDAR"),
    POA_ACCION_CENTRAL_FUE_VALIDADO("TipoNotificacion.POA_ACCION_CENTRAL_FUE_VALIDADO"),
    POA_ACCION_CENTRAL_FUE_RECHAZADO("TipoNotificacion.POA_ACCION_CENTRAL_FUE_RECHAZADO"),
    NUEVO_POA_ASIGNACION_NO_PROGRAMABLE_PARA_VALIDAR("TipoNotificacion.NUEVO_POA_ASIGNACION_NO_PROGRAMABLE_PARA_VALIDAR"),
    POA_ASIGNACION_NO_PROGRAMABLE_FUE_VALIDADO("TipoNotificacion.POA_ASIGNACION_NO_PROGRAMABLE_FUE_VALIDADO"),
    POA_ASIGNACION_NO_PROGRAMABLE_FUE_RECHAZADO("TipoNotificacion.POA_ASIGNACION_NO_PROGRAMABLE_FUE_RECHAZADO"),
    NUEVO_POA_PROYECTO_PARA_VALIDAR("TipoNotificacion.NUEVO_POA_PROYECTO_PARA_VALIDAR"),
    POA_PROYECTO_FUE_VALIDADO("TipoNotificacion.POA_PROYECTO_FUE_VALIDADO"),
    POA_PROYECTO_FUE_RECHAZADO("TipoNotificacion.POA_PROYECTO_FUE_RECHAZADO"),
    INGRESO_TDR_CERT_DISP_INSUMO_PROY("TipoNotificacion.INGRESO_TDR_CERT_DISP_INSUMO_PROY"),
    INGRESO_TDR_CERT_DISP_INSUMO_ACC_CENTR("TipoNotificacion.INGRESO_TDR_CERT_DISP_INSUMO_ACC_CENTR"),
    INGRESO_TDR_CERT_DISP_INSUMO_ASIG_NP("TipoNotificacion.INGRESO_TDR_CERT_DISP_INSUMO_ASIG_NP"),
    PROCESO_ADQUISICION_EN_PAUSA("TipoNotificacion.PROCESO_ADQUISICION_EN_PAUSA"),
    ITEM_DESIERTO("TipoNotificacion.ITEM_DESIERTO"),
    ITEM_SIN_EFECTO("TipoNotificacion.ITEM_SIN_EFECTO"),
    INGRESO_ORDEN_INICIO_CONTRATO("TipoNotificacion.INGRESO_ORDEN_INICIO_CONTRATO"),
    INSUMOS_PROCESO_ADQ_PENDIENTE_CARGA_TDR_ET("TipoNotificacion.INSUMOS_PROCESO_ADQ_PENDIENTE_CARGA_TDR_ET"),
    INSUMOS_PROCESO_ADQ_PENDIENTE_CARGA_TDR_ET_POA_PROYECTO("TipoNotificacion.INSUMOS_PROCESO_ADQ_PENDIENTE_CARGA_TDR_ET_POA_PROYECTO"),
    CERTIFICADO_DISPONIBILIDAD_PRESUPUESTARIA_PARA_VALIDAR("TipoNotificacion.CERTIFICADO_DISPONIBILIDAD_PRESUPUESTARIA_PARA_VALIDAR"),
    VALIDAR_IMPUESTOS_CONTRATO("TipoNotificacion.VALIDAR_IMPUESTOS_CONTRATO"),
    PROCESO_ADQ_ASIGNADO_A_ORDEN_INICIO("TipoNotificacion.PROCESO_ADQ_ASIGNADO_A_ORDEN_INICIO"),
    CERTIFICADO_DISP_PRESUPUESTARIA_COMETNARIO_PARA_SOLICITANTE("TipoNotificacion.CERTIFICADO_DISP_PRESUPUESTARIA_COMETNARIO_PARA_SOLICITANTE"),
    CERTIFICADO_DISP_PRESUPUESTARIA_COMETNARIO_PARA_VALIDADOR("TipoNotificacion.CERTIFICADO_DISP_PRESUPUESTARIA_COMETNARIO_PARA_VALIDADOR"),
    VALIDACION_COMPROMISO_PRESUPUESTARIO("TipoNotificacion.VALIDACION_COMPROMISO_PRESUPUESTARIO"),
    DESCERTIFICACION_MONTO_FUENTE_INSUMO_PARA_VALIDAR("TipoNotificacion.DESCERTIFICACION_MONTO_FUENTE_INSUMO_PARA_VALIDAR"),
    CERTIFICADO_DISPONIBILIDAD_PRESUPUESTARIA_PARA_VALIDAR_POR_PROCESO("TipoNotificacion.CERTIFICADO_DISPONIBILIDAD_PRESUPUESTARIA_PARA_VALIDAR_POR_PROCESO"),
    DESCOMPROMISO_INSUMO("TipoNotificacion.DESCOMPROMISO_INSUMO"),
    NUEVO_POA_PARA_VALIDAR("TipoNotificacion.NUEVO_POA_PARA_VALIDAR"),
    NUEVO_POA_PARA_EVALUAR("TipoNotificacion.NUEVO_POA_PARA_EVALUAR"),
    POA_FUE_APROBADO("TipoNotificacion.POA_FUE_APROBADO"),
    POA_FUE_RECHAZADO("TipoNotificacion.POA_FUE_RECHAZADO"),
    EJECUCION_PROCESO_TRANSFERENCIAS_ARCHIVO("TipoNotificacion.EJECUCION_PROCESO_TRANSFERENCIAS_ARCHIVO"),
    EJECUCION_PROCESO_TECHOS_ARCHIVO("TipoNotificacion.EJECUCION_PROCESO_TECHOS_ARCHIVO"),
    EJECUCION_PROCESO_TECHOS_SISTEMA("TipoNotificacion.EJECUCION_PROCESO_TECHOS_SISTEMA");
    private String label;

    private TipoNotificacion(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }

}
